// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: wevibe/identity/v1/state.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Params } from "./params";

export const protobufPackage = "wevibe.identity.v1";

export interface StoredIdentityAlias {
  /** ed25519 hex — the canonical identity key (map key) */
  passkeyPubkey: string;
  /** bech32 secp256k1 wallet */
  walletAddress: string;
  isMigrated: boolean;
  migratedAtEpoch: string;
}

export interface GenesisState {
  aliases: StoredIdentityAlias[];
  params?: Params | undefined;
}

function createBaseStoredIdentityAlias(): StoredIdentityAlias {
  return { passkeyPubkey: "", walletAddress: "", isMigrated: false, migratedAtEpoch: "0" };
}

export const StoredIdentityAlias: MessageFns<StoredIdentityAlias> = {
  encode(message: StoredIdentityAlias, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.passkeyPubkey !== "") {
      writer.uint32(10).string(message.passkeyPubkey);
    }
    if (message.walletAddress !== "") {
      writer.uint32(18).string(message.walletAddress);
    }
    if (message.isMigrated !== false) {
      writer.uint32(24).bool(message.isMigrated);
    }
    if (message.migratedAtEpoch !== "0") {
      writer.uint32(32).uint64(message.migratedAtEpoch);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StoredIdentityAlias {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoredIdentityAlias();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.passkeyPubkey = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.walletAddress = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.isMigrated = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.migratedAtEpoch = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoredIdentityAlias {
    return {
      passkeyPubkey: isSet(object.passkeyPubkey)
        ? globalThis.String(object.passkeyPubkey)
        : isSet(object.passkey_pubkey)
        ? globalThis.String(object.passkey_pubkey)
        : "",
      walletAddress: isSet(object.walletAddress)
        ? globalThis.String(object.walletAddress)
        : isSet(object.wallet_address)
        ? globalThis.String(object.wallet_address)
        : "",
      isMigrated: isSet(object.isMigrated)
        ? globalThis.Boolean(object.isMigrated)
        : isSet(object.is_migrated)
        ? globalThis.Boolean(object.is_migrated)
        : false,
      migratedAtEpoch: isSet(object.migratedAtEpoch)
        ? globalThis.String(object.migratedAtEpoch)
        : isSet(object.migrated_at_epoch)
        ? globalThis.String(object.migrated_at_epoch)
        : "0",
    };
  },

  toJSON(message: StoredIdentityAlias): unknown {
    const obj: any = {};
    if (message.passkeyPubkey !== "") {
      obj.passkeyPubkey = message.passkeyPubkey;
    }
    if (message.walletAddress !== "") {
      obj.walletAddress = message.walletAddress;
    }
    if (message.isMigrated !== false) {
      obj.isMigrated = message.isMigrated;
    }
    if (message.migratedAtEpoch !== "0") {
      obj.migratedAtEpoch = message.migratedAtEpoch;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StoredIdentityAlias>, I>>(base?: I): StoredIdentityAlias {
    return StoredIdentityAlias.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StoredIdentityAlias>, I>>(object: I): StoredIdentityAlias {
    const message = createBaseStoredIdentityAlias();
    message.passkeyPubkey = object.passkeyPubkey ?? "";
    message.walletAddress = object.walletAddress ?? "";
    message.isMigrated = object.isMigrated ?? false;
    message.migratedAtEpoch = object.migratedAtEpoch ?? "0";
    return message;
  },
};

function createBaseGenesisState(): GenesisState {
  return { aliases: [], params: undefined };
}

export const GenesisState: MessageFns<GenesisState> = {
  encode(message: GenesisState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.aliases) {
      StoredIdentityAlias.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenesisState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenesisState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.aliases.push(StoredIdentityAlias.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenesisState {
    return {
      aliases: globalThis.Array.isArray(object?.aliases)
        ? object.aliases.map((e: any) => StoredIdentityAlias.fromJSON(e))
        : [],
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
    };
  },

  toJSON(message: GenesisState): unknown {
    const obj: any = {};
    if (message.aliases?.length) {
      obj.aliases = message.aliases.map((e) => StoredIdentityAlias.toJSON(e));
    }
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GenesisState>, I>>(base?: I): GenesisState {
    return GenesisState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GenesisState>, I>>(object: I): GenesisState {
    const message = createBaseGenesisState();
    message.aliases = object.aliases?.map((e) => StoredIdentityAlias.fromPartial(e)) || [];
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
