// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               unknown
// source: wevibe/attestation/v1/query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Params } from "./params";
import { StoredSessionAttestation } from "./state";

export const protobufPackage = "wevibe.attestation.v1";

export interface QueryGetSessionAttestationRequest {
  orgId: string;
  sessionHash: Uint8Array;
}

export interface QueryGetSessionAttestationResponse {
  attestation?: StoredSessionAttestation | undefined;
}

export interface QueryListSessionAttestationsRequest {
  orgId: string;
  epoch: string;
}

export interface QueryListSessionAttestationsResponse {
  attestations: StoredSessionAttestation[];
}

export interface QueryParamsRequest {
}

export interface QueryParamsResponse {
  params?: Params | undefined;
}

function createBaseQueryGetSessionAttestationRequest(): QueryGetSessionAttestationRequest {
  return { orgId: "", sessionHash: new Uint8Array(0) };
}

export const QueryGetSessionAttestationRequest: MessageFns<QueryGetSessionAttestationRequest> = {
  encode(message: QueryGetSessionAttestationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orgId !== "") {
      writer.uint32(10).string(message.orgId);
    }
    if (message.sessionHash.length !== 0) {
      writer.uint32(18).bytes(message.sessionHash);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetSessionAttestationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetSessionAttestationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orgId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sessionHash = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetSessionAttestationRequest {
    return {
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
        ? globalThis.String(object.org_id)
        : "",
      sessionHash: isSet(object.sessionHash)
        ? bytesFromBase64(object.sessionHash)
        : isSet(object.session_hash)
        ? bytesFromBase64(object.session_hash)
        : new Uint8Array(0),
    };
  },

  toJSON(message: QueryGetSessionAttestationRequest): unknown {
    const obj: any = {};
    if (message.orgId !== "") {
      obj.orgId = message.orgId;
    }
    if (message.sessionHash.length !== 0) {
      obj.sessionHash = base64FromBytes(message.sessionHash);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetSessionAttestationRequest>, I>>(
    base?: I,
  ): QueryGetSessionAttestationRequest {
    return QueryGetSessionAttestationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetSessionAttestationRequest>, I>>(
    object: I,
  ): QueryGetSessionAttestationRequest {
    const message = createBaseQueryGetSessionAttestationRequest();
    message.orgId = object.orgId ?? "";
    message.sessionHash = object.sessionHash ?? new Uint8Array(0);
    return message;
  },
};

function createBaseQueryGetSessionAttestationResponse(): QueryGetSessionAttestationResponse {
  return { attestation: undefined };
}

export const QueryGetSessionAttestationResponse: MessageFns<QueryGetSessionAttestationResponse> = {
  encode(message: QueryGetSessionAttestationResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.attestation !== undefined) {
      StoredSessionAttestation.encode(message.attestation, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetSessionAttestationResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetSessionAttestationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.attestation = StoredSessionAttestation.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetSessionAttestationResponse {
    return {
      attestation: isSet(object.attestation) ? StoredSessionAttestation.fromJSON(object.attestation) : undefined,
    };
  },

  toJSON(message: QueryGetSessionAttestationResponse): unknown {
    const obj: any = {};
    if (message.attestation !== undefined) {
      obj.attestation = StoredSessionAttestation.toJSON(message.attestation);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetSessionAttestationResponse>, I>>(
    base?: I,
  ): QueryGetSessionAttestationResponse {
    return QueryGetSessionAttestationResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetSessionAttestationResponse>, I>>(
    object: I,
  ): QueryGetSessionAttestationResponse {
    const message = createBaseQueryGetSessionAttestationResponse();
    message.attestation = (object.attestation !== undefined && object.attestation !== null)
      ? StoredSessionAttestation.fromPartial(object.attestation)
      : undefined;
    return message;
  },
};

function createBaseQueryListSessionAttestationsRequest(): QueryListSessionAttestationsRequest {
  return { orgId: "", epoch: "0" };
}

export const QueryListSessionAttestationsRequest: MessageFns<QueryListSessionAttestationsRequest> = {
  encode(message: QueryListSessionAttestationsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orgId !== "") {
      writer.uint32(10).string(message.orgId);
    }
    if (message.epoch !== "0") {
      writer.uint32(16).uint64(message.epoch);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryListSessionAttestationsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryListSessionAttestationsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orgId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.epoch = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryListSessionAttestationsRequest {
    return {
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
        ? globalThis.String(object.org_id)
        : "",
      epoch: isSet(object.epoch) ? globalThis.String(object.epoch) : "0",
    };
  },

  toJSON(message: QueryListSessionAttestationsRequest): unknown {
    const obj: any = {};
    if (message.orgId !== "") {
      obj.orgId = message.orgId;
    }
    if (message.epoch !== "0") {
      obj.epoch = message.epoch;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryListSessionAttestationsRequest>, I>>(
    base?: I,
  ): QueryListSessionAttestationsRequest {
    return QueryListSessionAttestationsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryListSessionAttestationsRequest>, I>>(
    object: I,
  ): QueryListSessionAttestationsRequest {
    const message = createBaseQueryListSessionAttestationsRequest();
    message.orgId = object.orgId ?? "";
    message.epoch = object.epoch ?? "0";
    return message;
  },
};

function createBaseQueryListSessionAttestationsResponse(): QueryListSessionAttestationsResponse {
  return { attestations: [] };
}

export const QueryListSessionAttestationsResponse: MessageFns<QueryListSessionAttestationsResponse> = {
  encode(message: QueryListSessionAttestationsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.attestations) {
      StoredSessionAttestation.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryListSessionAttestationsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryListSessionAttestationsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.attestations.push(StoredSessionAttestation.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryListSessionAttestationsResponse {
    return {
      attestations: globalThis.Array.isArray(object?.attestations)
        ? object.attestations.map((e: any) => StoredSessionAttestation.fromJSON(e))
        : [],
    };
  },

  toJSON(message: QueryListSessionAttestationsResponse): unknown {
    const obj: any = {};
    if (message.attestations?.length) {
      obj.attestations = message.attestations.map((e) => StoredSessionAttestation.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryListSessionAttestationsResponse>, I>>(
    base?: I,
  ): QueryListSessionAttestationsResponse {
    return QueryListSessionAttestationsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryListSessionAttestationsResponse>, I>>(
    object: I,
  ): QueryListSessionAttestationsResponse {
    const message = createBaseQueryListSessionAttestationsResponse();
    message.attestations = object.attestations?.map((e) => StoredSessionAttestation.fromPartial(e)) || [];
    return message;
  },
};

function createBaseQueryParamsRequest(): QueryParamsRequest {
  return {};
}

export const QueryParamsRequest: MessageFns<QueryParamsRequest> = {
  encode(_: QueryParamsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryParamsRequest {
    return {};
  },

  toJSON(_: QueryParamsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(base?: I): QueryParamsRequest {
    return QueryParamsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(_: I): QueryParamsRequest {
    const message = createBaseQueryParamsRequest();
    return message;
  },
};

function createBaseQueryParamsResponse(): QueryParamsResponse {
  return { params: undefined };
}

export const QueryParamsResponse: MessageFns<QueryParamsResponse> = {
  encode(message: QueryParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryParamsResponse {
    return { params: isSet(object.params) ? Params.fromJSON(object.params) : undefined };
  },

  toJSON(message: QueryParamsResponse): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(base?: I): QueryParamsResponse {
    return QueryParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(object: I): QueryParamsResponse {
    const message = createBaseQueryParamsResponse();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
