// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: wevibe/org/v1/params.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "wevibe.org.v1";

export interface Params {
  minRegistrationFee: string;
  annualRenewalFee: string;
  defaultStorageQuota: string;
  defaultRetrievalBudget: string;
  gracePeriodEpochs: string;
  burnPriceDecayEpochs: string;
  baseBurnPrice: string;
  burnPriceIncreasePercent: string;
  slotCap: string;
}

function createBaseParams(): Params {
  return {
    minRegistrationFee: "0",
    annualRenewalFee: "0",
    defaultStorageQuota: "0",
    defaultRetrievalBudget: "0",
    gracePeriodEpochs: "0",
    burnPriceDecayEpochs: "0",
    baseBurnPrice: "0",
    burnPriceIncreasePercent: "0",
    slotCap: "0",
  };
}

export const Params: MessageFns<Params> = {
  encode(message: Params, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.minRegistrationFee !== "0") {
      writer.uint32(8).uint64(message.minRegistrationFee);
    }
    if (message.annualRenewalFee !== "0") {
      writer.uint32(16).uint64(message.annualRenewalFee);
    }
    if (message.defaultStorageQuota !== "0") {
      writer.uint32(24).uint64(message.defaultStorageQuota);
    }
    if (message.defaultRetrievalBudget !== "0") {
      writer.uint32(32).uint64(message.defaultRetrievalBudget);
    }
    if (message.gracePeriodEpochs !== "0") {
      writer.uint32(40).uint64(message.gracePeriodEpochs);
    }
    if (message.burnPriceDecayEpochs !== "0") {
      writer.uint32(48).uint64(message.burnPriceDecayEpochs);
    }
    if (message.baseBurnPrice !== "0") {
      writer.uint32(56).uint64(message.baseBurnPrice);
    }
    if (message.burnPriceIncreasePercent !== "0") {
      writer.uint32(64).uint64(message.burnPriceIncreasePercent);
    }
    if (message.slotCap !== "0") {
      writer.uint32(72).uint64(message.slotCap);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Params {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.minRegistrationFee = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.annualRenewalFee = reader.uint64().toString();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.defaultStorageQuota = reader.uint64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.defaultRetrievalBudget = reader.uint64().toString();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.gracePeriodEpochs = reader.uint64().toString();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.burnPriceDecayEpochs = reader.uint64().toString();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.baseBurnPrice = reader.uint64().toString();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.burnPriceIncreasePercent = reader.uint64().toString();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.slotCap = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Params {
    return {
      minRegistrationFee: isSet(object.minRegistrationFee)
        ? globalThis.String(object.minRegistrationFee)
        : isSet(object.min_registration_fee)
        ? globalThis.String(object.min_registration_fee)
        : "0",
      annualRenewalFee: isSet(object.annualRenewalFee)
        ? globalThis.String(object.annualRenewalFee)
        : isSet(object.annual_renewal_fee)
        ? globalThis.String(object.annual_renewal_fee)
        : "0",
      defaultStorageQuota: isSet(object.defaultStorageQuota)
        ? globalThis.String(object.defaultStorageQuota)
        : isSet(object.default_storage_quota)
        ? globalThis.String(object.default_storage_quota)
        : "0",
      defaultRetrievalBudget: isSet(object.defaultRetrievalBudget)
        ? globalThis.String(object.defaultRetrievalBudget)
        : isSet(object.default_retrieval_budget)
        ? globalThis.String(object.default_retrieval_budget)
        : "0",
      gracePeriodEpochs: isSet(object.gracePeriodEpochs)
        ? globalThis.String(object.gracePeriodEpochs)
        : isSet(object.grace_period_epochs)
        ? globalThis.String(object.grace_period_epochs)
        : "0",
      burnPriceDecayEpochs: isSet(object.burnPriceDecayEpochs)
        ? globalThis.String(object.burnPriceDecayEpochs)
        : isSet(object.burn_price_decay_epochs)
        ? globalThis.String(object.burn_price_decay_epochs)
        : "0",
      baseBurnPrice: isSet(object.baseBurnPrice)
        ? globalThis.String(object.baseBurnPrice)
        : isSet(object.base_burn_price)
        ? globalThis.String(object.base_burn_price)
        : "0",
      burnPriceIncreasePercent: isSet(object.burnPriceIncreasePercent)
        ? globalThis.String(object.burnPriceIncreasePercent)
        : isSet(object.burn_price_increase_percent)
        ? globalThis.String(object.burn_price_increase_percent)
        : "0",
      slotCap: isSet(object.slotCap)
        ? globalThis.String(object.slotCap)
        : isSet(object.slot_cap)
        ? globalThis.String(object.slot_cap)
        : "0",
    };
  },

  toJSON(message: Params): unknown {
    const obj: any = {};
    if (message.minRegistrationFee !== "0") {
      obj.minRegistrationFee = message.minRegistrationFee;
    }
    if (message.annualRenewalFee !== "0") {
      obj.annualRenewalFee = message.annualRenewalFee;
    }
    if (message.defaultStorageQuota !== "0") {
      obj.defaultStorageQuota = message.defaultStorageQuota;
    }
    if (message.defaultRetrievalBudget !== "0") {
      obj.defaultRetrievalBudget = message.defaultRetrievalBudget;
    }
    if (message.gracePeriodEpochs !== "0") {
      obj.gracePeriodEpochs = message.gracePeriodEpochs;
    }
    if (message.burnPriceDecayEpochs !== "0") {
      obj.burnPriceDecayEpochs = message.burnPriceDecayEpochs;
    }
    if (message.baseBurnPrice !== "0") {
      obj.baseBurnPrice = message.baseBurnPrice;
    }
    if (message.burnPriceIncreasePercent !== "0") {
      obj.burnPriceIncreasePercent = message.burnPriceIncreasePercent;
    }
    if (message.slotCap !== "0") {
      obj.slotCap = message.slotCap;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Params>, I>>(base?: I): Params {
    return Params.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Params>, I>>(object: I): Params {
    const message = createBaseParams();
    message.minRegistrationFee = object.minRegistrationFee ?? "0";
    message.annualRenewalFee = object.annualRenewalFee ?? "0";
    message.defaultStorageQuota = object.defaultStorageQuota ?? "0";
    message.defaultRetrievalBudget = object.defaultRetrievalBudget ?? "0";
    message.gracePeriodEpochs = object.gracePeriodEpochs ?? "0";
    message.burnPriceDecayEpochs = object.burnPriceDecayEpochs ?? "0";
    message.baseBurnPrice = object.baseBurnPrice ?? "0";
    message.burnPriceIncreasePercent = object.burnPriceIncreasePercent ?? "0";
    message.slotCap = object.slotCap ?? "0";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
