// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               unknown
// source: wevibe/org/v1/state.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "wevibe.org.v1";

export interface StoredOrg {
  orgId: string;
  leader: string;
  createdAt: string;
  renewalHeight: string;
  storageQuota: string;
  retrievalBudget: string;
  status: number;
  domain: string;
  totalCommittedMemories: string;
  totalActiveMembers: string;
  totalEpochRotations: string;
  totalUpheldReports: string;
  lastActivityEpoch: string;
}

export interface StoredMemberRecord {
  orgId: string;
  pubkey: string;
  role: string;
}

export interface StoredDynamicPrice {
  price: string;
  lastCreation: string;
  creationCount: string;
}

export interface StoredTreasury {
  orgId: string;
  balance: string;
}

export interface StoredRepTierConfig {
  orgId: string;
  tiers: RepTier[];
}

export interface RepTier {
  minReputation: string;
  maxReputation: string;
  maxContributionsPerEpoch: string;
  payoutPerMemory: string;
}

export interface StoredOrgConfig {
  orgId: string;
  serveAttestationRequired: boolean;
  contestStakeVibe: string;
  minContributionsPerEpoch: string;
}

function createBaseStoredOrg(): StoredOrg {
  return {
    orgId: "",
    leader: "",
    createdAt: "0",
    renewalHeight: "0",
    storageQuota: "0",
    retrievalBudget: "0",
    status: 0,
    domain: "",
    totalCommittedMemories: "0",
    totalActiveMembers: "0",
    totalEpochRotations: "0",
    totalUpheldReports: "0",
    lastActivityEpoch: "0",
  };
}

export const StoredOrg: MessageFns<StoredOrg> = {
  encode(message: StoredOrg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orgId !== "") {
      writer.uint32(10).string(message.orgId);
    }
    if (message.leader !== "") {
      writer.uint32(18).string(message.leader);
    }
    if (message.createdAt !== "0") {
      writer.uint32(24).uint64(message.createdAt);
    }
    if (message.renewalHeight !== "0") {
      writer.uint32(32).uint64(message.renewalHeight);
    }
    if (message.storageQuota !== "0") {
      writer.uint32(40).uint64(message.storageQuota);
    }
    if (message.retrievalBudget !== "0") {
      writer.uint32(48).uint64(message.retrievalBudget);
    }
    if (message.status !== 0) {
      writer.uint32(56).int32(message.status);
    }
    if (message.domain !== "") {
      writer.uint32(66).string(message.domain);
    }
    if (message.totalCommittedMemories !== "0") {
      writer.uint32(72).uint64(message.totalCommittedMemories);
    }
    if (message.totalActiveMembers !== "0") {
      writer.uint32(80).uint64(message.totalActiveMembers);
    }
    if (message.totalEpochRotations !== "0") {
      writer.uint32(88).uint64(message.totalEpochRotations);
    }
    if (message.totalUpheldReports !== "0") {
      writer.uint32(96).uint64(message.totalUpheldReports);
    }
    if (message.lastActivityEpoch !== "0") {
      writer.uint32(104).uint64(message.lastActivityEpoch);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StoredOrg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoredOrg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orgId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.leader = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.createdAt = reader.uint64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.renewalHeight = reader.uint64().toString();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.storageQuota = reader.uint64().toString();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.retrievalBudget = reader.uint64().toString();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.status = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.domain = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.totalCommittedMemories = reader.uint64().toString();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.totalActiveMembers = reader.uint64().toString();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.totalEpochRotations = reader.uint64().toString();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.totalUpheldReports = reader.uint64().toString();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.lastActivityEpoch = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoredOrg {
    return {
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
        ? globalThis.String(object.org_id)
        : "",
      leader: isSet(object.leader) ? globalThis.String(object.leader) : "",
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.String(object.created_at)
        : "0",
      renewalHeight: isSet(object.renewalHeight)
        ? globalThis.String(object.renewalHeight)
        : isSet(object.renewal_height)
        ? globalThis.String(object.renewal_height)
        : "0",
      storageQuota: isSet(object.storageQuota)
        ? globalThis.String(object.storageQuota)
        : isSet(object.storage_quota)
        ? globalThis.String(object.storage_quota)
        : "0",
      retrievalBudget: isSet(object.retrievalBudget)
        ? globalThis.String(object.retrievalBudget)
        : isSet(object.retrieval_budget)
        ? globalThis.String(object.retrieval_budget)
        : "0",
      status: isSet(object.status) ? globalThis.Number(object.status) : 0,
      domain: isSet(object.domain) ? globalThis.String(object.domain) : "",
      totalCommittedMemories: isSet(object.totalCommittedMemories)
        ? globalThis.String(object.totalCommittedMemories)
        : isSet(object.total_committed_memories)
        ? globalThis.String(object.total_committed_memories)
        : "0",
      totalActiveMembers: isSet(object.totalActiveMembers)
        ? globalThis.String(object.totalActiveMembers)
        : isSet(object.total_active_members)
        ? globalThis.String(object.total_active_members)
        : "0",
      totalEpochRotations: isSet(object.totalEpochRotations)
        ? globalThis.String(object.totalEpochRotations)
        : isSet(object.total_epoch_rotations)
        ? globalThis.String(object.total_epoch_rotations)
        : "0",
      totalUpheldReports: isSet(object.totalUpheldReports)
        ? globalThis.String(object.totalUpheldReports)
        : isSet(object.total_upheld_reports)
        ? globalThis.String(object.total_upheld_reports)
        : "0",
      lastActivityEpoch: isSet(object.lastActivityEpoch)
        ? globalThis.String(object.lastActivityEpoch)
        : isSet(object.last_activity_epoch)
        ? globalThis.String(object.last_activity_epoch)
        : "0",
    };
  },

  toJSON(message: StoredOrg): unknown {
    const obj: any = {};
    if (message.orgId !== "") {
      obj.orgId = message.orgId;
    }
    if (message.leader !== "") {
      obj.leader = message.leader;
    }
    if (message.createdAt !== "0") {
      obj.createdAt = message.createdAt;
    }
    if (message.renewalHeight !== "0") {
      obj.renewalHeight = message.renewalHeight;
    }
    if (message.storageQuota !== "0") {
      obj.storageQuota = message.storageQuota;
    }
    if (message.retrievalBudget !== "0") {
      obj.retrievalBudget = message.retrievalBudget;
    }
    if (message.status !== 0) {
      obj.status = Math.round(message.status);
    }
    if (message.domain !== "") {
      obj.domain = message.domain;
    }
    if (message.totalCommittedMemories !== "0") {
      obj.totalCommittedMemories = message.totalCommittedMemories;
    }
    if (message.totalActiveMembers !== "0") {
      obj.totalActiveMembers = message.totalActiveMembers;
    }
    if (message.totalEpochRotations !== "0") {
      obj.totalEpochRotations = message.totalEpochRotations;
    }
    if (message.totalUpheldReports !== "0") {
      obj.totalUpheldReports = message.totalUpheldReports;
    }
    if (message.lastActivityEpoch !== "0") {
      obj.lastActivityEpoch = message.lastActivityEpoch;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StoredOrg>, I>>(base?: I): StoredOrg {
    return StoredOrg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StoredOrg>, I>>(object: I): StoredOrg {
    const message = createBaseStoredOrg();
    message.orgId = object.orgId ?? "";
    message.leader = object.leader ?? "";
    message.createdAt = object.createdAt ?? "0";
    message.renewalHeight = object.renewalHeight ?? "0";
    message.storageQuota = object.storageQuota ?? "0";
    message.retrievalBudget = object.retrievalBudget ?? "0";
    message.status = object.status ?? 0;
    message.domain = object.domain ?? "";
    message.totalCommittedMemories = object.totalCommittedMemories ?? "0";
    message.totalActiveMembers = object.totalActiveMembers ?? "0";
    message.totalEpochRotations = object.totalEpochRotations ?? "0";
    message.totalUpheldReports = object.totalUpheldReports ?? "0";
    message.lastActivityEpoch = object.lastActivityEpoch ?? "0";
    return message;
  },
};

function createBaseStoredMemberRecord(): StoredMemberRecord {
  return { orgId: "", pubkey: "", role: "" };
}

export const StoredMemberRecord: MessageFns<StoredMemberRecord> = {
  encode(message: StoredMemberRecord, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orgId !== "") {
      writer.uint32(10).string(message.orgId);
    }
    if (message.pubkey !== "") {
      writer.uint32(18).string(message.pubkey);
    }
    if (message.role !== "") {
      writer.uint32(26).string(message.role);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StoredMemberRecord {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoredMemberRecord();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orgId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pubkey = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.role = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoredMemberRecord {
    return {
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
        ? globalThis.String(object.org_id)
        : "",
      pubkey: isSet(object.pubkey) ? globalThis.String(object.pubkey) : "",
      role: isSet(object.role) ? globalThis.String(object.role) : "",
    };
  },

  toJSON(message: StoredMemberRecord): unknown {
    const obj: any = {};
    if (message.orgId !== "") {
      obj.orgId = message.orgId;
    }
    if (message.pubkey !== "") {
      obj.pubkey = message.pubkey;
    }
    if (message.role !== "") {
      obj.role = message.role;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StoredMemberRecord>, I>>(base?: I): StoredMemberRecord {
    return StoredMemberRecord.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StoredMemberRecord>, I>>(object: I): StoredMemberRecord {
    const message = createBaseStoredMemberRecord();
    message.orgId = object.orgId ?? "";
    message.pubkey = object.pubkey ?? "";
    message.role = object.role ?? "";
    return message;
  },
};

function createBaseStoredDynamicPrice(): StoredDynamicPrice {
  return { price: "0", lastCreation: "0", creationCount: "0" };
}

export const StoredDynamicPrice: MessageFns<StoredDynamicPrice> = {
  encode(message: StoredDynamicPrice, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.price !== "0") {
      writer.uint32(8).uint64(message.price);
    }
    if (message.lastCreation !== "0") {
      writer.uint32(16).uint64(message.lastCreation);
    }
    if (message.creationCount !== "0") {
      writer.uint32(24).uint64(message.creationCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StoredDynamicPrice {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoredDynamicPrice();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.price = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.lastCreation = reader.uint64().toString();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.creationCount = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoredDynamicPrice {
    return {
      price: isSet(object.price) ? globalThis.String(object.price) : "0",
      lastCreation: isSet(object.lastCreation)
        ? globalThis.String(object.lastCreation)
        : isSet(object.last_creation)
        ? globalThis.String(object.last_creation)
        : "0",
      creationCount: isSet(object.creationCount)
        ? globalThis.String(object.creationCount)
        : isSet(object.creation_count)
        ? globalThis.String(object.creation_count)
        : "0",
    };
  },

  toJSON(message: StoredDynamicPrice): unknown {
    const obj: any = {};
    if (message.price !== "0") {
      obj.price = message.price;
    }
    if (message.lastCreation !== "0") {
      obj.lastCreation = message.lastCreation;
    }
    if (message.creationCount !== "0") {
      obj.creationCount = message.creationCount;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StoredDynamicPrice>, I>>(base?: I): StoredDynamicPrice {
    return StoredDynamicPrice.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StoredDynamicPrice>, I>>(object: I): StoredDynamicPrice {
    const message = createBaseStoredDynamicPrice();
    message.price = object.price ?? "0";
    message.lastCreation = object.lastCreation ?? "0";
    message.creationCount = object.creationCount ?? "0";
    return message;
  },
};

function createBaseStoredTreasury(): StoredTreasury {
  return { orgId: "", balance: "" };
}

export const StoredTreasury: MessageFns<StoredTreasury> = {
  encode(message: StoredTreasury, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orgId !== "") {
      writer.uint32(10).string(message.orgId);
    }
    if (message.balance !== "") {
      writer.uint32(18).string(message.balance);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StoredTreasury {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoredTreasury();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orgId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.balance = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoredTreasury {
    return {
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
        ? globalThis.String(object.org_id)
        : "",
      balance: isSet(object.balance) ? globalThis.String(object.balance) : "",
    };
  },

  toJSON(message: StoredTreasury): unknown {
    const obj: any = {};
    if (message.orgId !== "") {
      obj.orgId = message.orgId;
    }
    if (message.balance !== "") {
      obj.balance = message.balance;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StoredTreasury>, I>>(base?: I): StoredTreasury {
    return StoredTreasury.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StoredTreasury>, I>>(object: I): StoredTreasury {
    const message = createBaseStoredTreasury();
    message.orgId = object.orgId ?? "";
    message.balance = object.balance ?? "";
    return message;
  },
};

function createBaseStoredRepTierConfig(): StoredRepTierConfig {
  return { orgId: "", tiers: [] };
}

export const StoredRepTierConfig: MessageFns<StoredRepTierConfig> = {
  encode(message: StoredRepTierConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orgId !== "") {
      writer.uint32(10).string(message.orgId);
    }
    for (const v of message.tiers) {
      RepTier.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StoredRepTierConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoredRepTierConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orgId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tiers.push(RepTier.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoredRepTierConfig {
    return {
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
        ? globalThis.String(object.org_id)
        : "",
      tiers: globalThis.Array.isArray(object?.tiers) ? object.tiers.map((e: any) => RepTier.fromJSON(e)) : [],
    };
  },

  toJSON(message: StoredRepTierConfig): unknown {
    const obj: any = {};
    if (message.orgId !== "") {
      obj.orgId = message.orgId;
    }
    if (message.tiers?.length) {
      obj.tiers = message.tiers.map((e) => RepTier.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StoredRepTierConfig>, I>>(base?: I): StoredRepTierConfig {
    return StoredRepTierConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StoredRepTierConfig>, I>>(object: I): StoredRepTierConfig {
    const message = createBaseStoredRepTierConfig();
    message.orgId = object.orgId ?? "";
    message.tiers = object.tiers?.map((e) => RepTier.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRepTier(): RepTier {
  return { minReputation: "0", maxReputation: "0", maxContributionsPerEpoch: "0", payoutPerMemory: "" };
}

export const RepTier: MessageFns<RepTier> = {
  encode(message: RepTier, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.minReputation !== "0") {
      writer.uint32(8).uint64(message.minReputation);
    }
    if (message.maxReputation !== "0") {
      writer.uint32(16).uint64(message.maxReputation);
    }
    if (message.maxContributionsPerEpoch !== "0") {
      writer.uint32(24).uint64(message.maxContributionsPerEpoch);
    }
    if (message.payoutPerMemory !== "") {
      writer.uint32(34).string(message.payoutPerMemory);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RepTier {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRepTier();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.minReputation = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.maxReputation = reader.uint64().toString();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.maxContributionsPerEpoch = reader.uint64().toString();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.payoutPerMemory = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RepTier {
    return {
      minReputation: isSet(object.minReputation)
        ? globalThis.String(object.minReputation)
        : isSet(object.min_reputation)
        ? globalThis.String(object.min_reputation)
        : "0",
      maxReputation: isSet(object.maxReputation)
        ? globalThis.String(object.maxReputation)
        : isSet(object.max_reputation)
        ? globalThis.String(object.max_reputation)
        : "0",
      maxContributionsPerEpoch: isSet(object.maxContributionsPerEpoch)
        ? globalThis.String(object.maxContributionsPerEpoch)
        : isSet(object.max_contributions_per_epoch)
        ? globalThis.String(object.max_contributions_per_epoch)
        : "0",
      payoutPerMemory: isSet(object.payoutPerMemory)
        ? globalThis.String(object.payoutPerMemory)
        : isSet(object.payout_per_memory)
        ? globalThis.String(object.payout_per_memory)
        : "",
    };
  },

  toJSON(message: RepTier): unknown {
    const obj: any = {};
    if (message.minReputation !== "0") {
      obj.minReputation = message.minReputation;
    }
    if (message.maxReputation !== "0") {
      obj.maxReputation = message.maxReputation;
    }
    if (message.maxContributionsPerEpoch !== "0") {
      obj.maxContributionsPerEpoch = message.maxContributionsPerEpoch;
    }
    if (message.payoutPerMemory !== "") {
      obj.payoutPerMemory = message.payoutPerMemory;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RepTier>, I>>(base?: I): RepTier {
    return RepTier.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RepTier>, I>>(object: I): RepTier {
    const message = createBaseRepTier();
    message.minReputation = object.minReputation ?? "0";
    message.maxReputation = object.maxReputation ?? "0";
    message.maxContributionsPerEpoch = object.maxContributionsPerEpoch ?? "0";
    message.payoutPerMemory = object.payoutPerMemory ?? "";
    return message;
  },
};

function createBaseStoredOrgConfig(): StoredOrgConfig {
  return { orgId: "", serveAttestationRequired: false, contestStakeVibe: "0", minContributionsPerEpoch: "0" };
}

export const StoredOrgConfig: MessageFns<StoredOrgConfig> = {
  encode(message: StoredOrgConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orgId !== "") {
      writer.uint32(10).string(message.orgId);
    }
    if (message.serveAttestationRequired !== false) {
      writer.uint32(16).bool(message.serveAttestationRequired);
    }
    if (message.contestStakeVibe !== "0") {
      writer.uint32(32).uint64(message.contestStakeVibe);
    }
    if (message.minContributionsPerEpoch !== "0") {
      writer.uint32(80).uint64(message.minContributionsPerEpoch);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StoredOrgConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoredOrgConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orgId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.serveAttestationRequired = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.contestStakeVibe = reader.uint64().toString();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.minContributionsPerEpoch = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoredOrgConfig {
    return {
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
        ? globalThis.String(object.org_id)
        : "",
      serveAttestationRequired: isSet(object.serveAttestationRequired)
        ? globalThis.Boolean(object.serveAttestationRequired)
        : isSet(object.serve_attestation_required)
        ? globalThis.Boolean(object.serve_attestation_required)
        : false,
      contestStakeVibe: isSet(object.contestStakeVibe)
        ? globalThis.String(object.contestStakeVibe)
        : isSet(object.contest_stake_vibe)
        ? globalThis.String(object.contest_stake_vibe)
        : "0",
      minContributionsPerEpoch: isSet(object.minContributionsPerEpoch)
        ? globalThis.String(object.minContributionsPerEpoch)
        : isSet(object.min_contributions_per_epoch)
        ? globalThis.String(object.min_contributions_per_epoch)
        : "0",
    };
  },

  toJSON(message: StoredOrgConfig): unknown {
    const obj: any = {};
    if (message.orgId !== "") {
      obj.orgId = message.orgId;
    }
    if (message.serveAttestationRequired !== false) {
      obj.serveAttestationRequired = message.serveAttestationRequired;
    }
    if (message.contestStakeVibe !== "0") {
      obj.contestStakeVibe = message.contestStakeVibe;
    }
    if (message.minContributionsPerEpoch !== "0") {
      obj.minContributionsPerEpoch = message.minContributionsPerEpoch;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StoredOrgConfig>, I>>(base?: I): StoredOrgConfig {
    return StoredOrgConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StoredOrgConfig>, I>>(object: I): StoredOrgConfig {
    const message = createBaseStoredOrgConfig();
    message.orgId = object.orgId ?? "";
    message.serveAttestationRequired = object.serveAttestationRequired ?? false;
    message.contestStakeVibe = object.contestStakeVibe ?? "0";
    message.minContributionsPerEpoch = object.minContributionsPerEpoch ?? "0";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
