// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: wevibe/org/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Params } from "./params";

export const protobufPackage = "wevibe.org.v1";

export interface MsgRegisterOrg {
  signer: string;
  leader: string;
  storageQuota: string;
  retrievalBudget: string;
  domain: string;
  /**
   * CO-044 (D-S32-CO044-KEY-SEPARATION): the per-org hub serving key chain
   * address (signs serves/denials only) and the leader's chain wallet address
   * (the on-chain authority for org decisions).
   */
  hubServingKey: string;
  leaderWallet: string;
  description: string;
  techStack: string;
  focusAreas: string;
  name: string;
}

export interface MsgRegisterOrgResponse {
  orgId: string;
}

/**
 * CO-044: rotate/revoke the org's hub serving key. Authorized by the leader's
 * chain wallet (msg.signer must equal the org's leader_wallet_address).
 */
export interface MsgSetServingKey {
  signer: string;
  orgId: string;
  newServingKey: string;
}

export interface MsgSetServingKeyResponse {
}

export interface MsgSetServingInfo {
  /** leader's secp256k1 chain wallet (Bech32) */
  signer: string;
  orgId: string;
  /** ordered 1-3 transport URLs (D-CHAIN-RESOLVED-HUB-ENDPOINT) */
  hubEndpoints: string[];
  /** optional lowercase hex ed25519 pubkey (32 bytes) */
  hubResponsePubkey: string;
}

export interface MsgSetServingInfoResponse {
}

export interface MsgAddMember {
  signer: string;
  orgId: string;
  pubkey: string;
  role: string;
  x25519Pubkey: string;
  canContribute: boolean;
  canModerate: boolean;
}

export interface MsgAddMemberResponse {
}

export interface MsgRemoveMember {
  signer: string;
  orgId: string;
  pubkey: string;
}

export interface MsgRemoveMemberResponse {
}

export interface MsgUpdateParams {
  authority: string;
  params?: Params | undefined;
}

export interface MsgUpdateParamsResponse {
}

export interface MsgSetOrgConfig {
  signer: string;
  orgId: string;
  serveReceiptRequired: boolean;
  minContributionsPerEpoch: string;
  contestStakeVibe: string;
  vocabHash: string;
  embeddingModelId: string;
}

export interface MsgSetOrgConfigResponse {
}

export interface MsgGrantTrialAllowance {
  signer: string;
  orgId: string;
  grantee: string;
  dailySubmissions: string;
  trialDays: string;
}

export interface MsgGrantTrialAllowanceResponse {
}

export interface MsgSetMemberCapabilities {
  signer: string;
  orgId: string;
  pubkey: string;
  canContribute: boolean;
  canModerate: boolean;
}

export interface MsgSetMemberCapabilitiesResponse {
}

export interface MsgRotateEpoch {
  signer: string;
  orgId: string;
}

export interface MsgRotateEpochResponse {
  newEpoch: string;
}

export interface MsgTransferLeadership {
  signer: string;
  orgId: string;
  newLeader: string;
  newLeaderWallet: string;
}

export interface MsgTransferLeadershipResponse {
}

export interface MsgCloseOrg {
  signer: string;
  orgId: string;
}

export interface MsgCloseOrgResponse {
}

function createBaseMsgRegisterOrg(): MsgRegisterOrg {
  return {
    signer: "",
    leader: "",
    storageQuota: "0",
    retrievalBudget: "0",
    domain: "",
    hubServingKey: "",
    leaderWallet: "",
    description: "",
    techStack: "",
    focusAreas: "",
    name: "",
  };
}

export const MsgRegisterOrg: MessageFns<MsgRegisterOrg> = {
  encode(message: MsgRegisterOrg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.signer !== "") {
      writer.uint32(10).string(message.signer);
    }
    if (message.leader !== "") {
      writer.uint32(26).string(message.leader);
    }
    if (message.storageQuota !== "0") {
      writer.uint32(32).uint64(message.storageQuota);
    }
    if (message.retrievalBudget !== "0") {
      writer.uint32(40).uint64(message.retrievalBudget);
    }
    if (message.domain !== "") {
      writer.uint32(50).string(message.domain);
    }
    if (message.hubServingKey !== "") {
      writer.uint32(58).string(message.hubServingKey);
    }
    if (message.leaderWallet !== "") {
      writer.uint32(66).string(message.leaderWallet);
    }
    if (message.description !== "") {
      writer.uint32(74).string(message.description);
    }
    if (message.techStack !== "") {
      writer.uint32(82).string(message.techStack);
    }
    if (message.focusAreas !== "") {
      writer.uint32(90).string(message.focusAreas);
    }
    if (message.name !== "") {
      writer.uint32(98).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRegisterOrg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRegisterOrg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signer = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.leader = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.storageQuota = reader.uint64().toString();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.retrievalBudget = reader.uint64().toString();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.domain = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.hubServingKey = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.leaderWallet = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.techStack = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.focusAreas = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgRegisterOrg {
    return {
      signer: isSet(object.signer) ? globalThis.String(object.signer) : "",
      leader: isSet(object.leader) ? globalThis.String(object.leader) : "",
      storageQuota: isSet(object.storageQuota)
        ? globalThis.String(object.storageQuota)
        : isSet(object.storage_quota)
        ? globalThis.String(object.storage_quota)
        : "0",
      retrievalBudget: isSet(object.retrievalBudget)
        ? globalThis.String(object.retrievalBudget)
        : isSet(object.retrieval_budget)
        ? globalThis.String(object.retrieval_budget)
        : "0",
      domain: isSet(object.domain) ? globalThis.String(object.domain) : "",
      hubServingKey: isSet(object.hubServingKey)
        ? globalThis.String(object.hubServingKey)
        : isSet(object.hub_serving_key)
        ? globalThis.String(object.hub_serving_key)
        : "",
      leaderWallet: isSet(object.leaderWallet)
        ? globalThis.String(object.leaderWallet)
        : isSet(object.leader_wallet)
        ? globalThis.String(object.leader_wallet)
        : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      techStack: isSet(object.techStack)
        ? globalThis.String(object.techStack)
        : isSet(object.tech_stack)
        ? globalThis.String(object.tech_stack)
        : "",
      focusAreas: isSet(object.focusAreas)
        ? globalThis.String(object.focusAreas)
        : isSet(object.focus_areas)
        ? globalThis.String(object.focus_areas)
        : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
    };
  },

  toJSON(message: MsgRegisterOrg): unknown {
    const obj: any = {};
    if (message.signer !== "") {
      obj.signer = message.signer;
    }
    if (message.leader !== "") {
      obj.leader = message.leader;
    }
    if (message.storageQuota !== "0") {
      obj.storageQuota = message.storageQuota;
    }
    if (message.retrievalBudget !== "0") {
      obj.retrievalBudget = message.retrievalBudget;
    }
    if (message.domain !== "") {
      obj.domain = message.domain;
    }
    if (message.hubServingKey !== "") {
      obj.hubServingKey = message.hubServingKey;
    }
    if (message.leaderWallet !== "") {
      obj.leaderWallet = message.leaderWallet;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.techStack !== "") {
      obj.techStack = message.techStack;
    }
    if (message.focusAreas !== "") {
      obj.focusAreas = message.focusAreas;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRegisterOrg>, I>>(base?: I): MsgRegisterOrg {
    return MsgRegisterOrg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRegisterOrg>, I>>(object: I): MsgRegisterOrg {
    const message = createBaseMsgRegisterOrg();
    message.signer = object.signer ?? "";
    message.leader = object.leader ?? "";
    message.storageQuota = object.storageQuota ?? "0";
    message.retrievalBudget = object.retrievalBudget ?? "0";
    message.domain = object.domain ?? "";
    message.hubServingKey = object.hubServingKey ?? "";
    message.leaderWallet = object.leaderWallet ?? "";
    message.description = object.description ?? "";
    message.techStack = object.techStack ?? "";
    message.focusAreas = object.focusAreas ?? "";
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseMsgRegisterOrgResponse(): MsgRegisterOrgResponse {
  return { orgId: "" };
}

export const MsgRegisterOrgResponse: MessageFns<MsgRegisterOrgResponse> = {
  encode(message: MsgRegisterOrgResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orgId !== "") {
      writer.uint32(10).string(message.orgId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRegisterOrgResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRegisterOrgResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orgId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgRegisterOrgResponse {
    return {
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
        ? globalThis.String(object.org_id)
        : "",
    };
  },

  toJSON(message: MsgRegisterOrgResponse): unknown {
    const obj: any = {};
    if (message.orgId !== "") {
      obj.orgId = message.orgId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRegisterOrgResponse>, I>>(base?: I): MsgRegisterOrgResponse {
    return MsgRegisterOrgResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRegisterOrgResponse>, I>>(object: I): MsgRegisterOrgResponse {
    const message = createBaseMsgRegisterOrgResponse();
    message.orgId = object.orgId ?? "";
    return message;
  },
};

function createBaseMsgSetServingKey(): MsgSetServingKey {
  return { signer: "", orgId: "", newServingKey: "" };
}

export const MsgSetServingKey: MessageFns<MsgSetServingKey> = {
  encode(message: MsgSetServingKey, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.signer !== "") {
      writer.uint32(10).string(message.signer);
    }
    if (message.orgId !== "") {
      writer.uint32(18).string(message.orgId);
    }
    if (message.newServingKey !== "") {
      writer.uint32(26).string(message.newServingKey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSetServingKey {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSetServingKey();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signer = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.orgId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.newServingKey = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgSetServingKey {
    return {
      signer: isSet(object.signer) ? globalThis.String(object.signer) : "",
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
        ? globalThis.String(object.org_id)
        : "",
      newServingKey: isSet(object.newServingKey)
        ? globalThis.String(object.newServingKey)
        : isSet(object.new_serving_key)
        ? globalThis.String(object.new_serving_key)
        : "",
    };
  },

  toJSON(message: MsgSetServingKey): unknown {
    const obj: any = {};
    if (message.signer !== "") {
      obj.signer = message.signer;
    }
    if (message.orgId !== "") {
      obj.orgId = message.orgId;
    }
    if (message.newServingKey !== "") {
      obj.newServingKey = message.newServingKey;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSetServingKey>, I>>(base?: I): MsgSetServingKey {
    return MsgSetServingKey.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSetServingKey>, I>>(object: I): MsgSetServingKey {
    const message = createBaseMsgSetServingKey();
    message.signer = object.signer ?? "";
    message.orgId = object.orgId ?? "";
    message.newServingKey = object.newServingKey ?? "";
    return message;
  },
};

function createBaseMsgSetServingKeyResponse(): MsgSetServingKeyResponse {
  return {};
}

export const MsgSetServingKeyResponse: MessageFns<MsgSetServingKeyResponse> = {
  encode(_: MsgSetServingKeyResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSetServingKeyResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSetServingKeyResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgSetServingKeyResponse {
    return {};
  },

  toJSON(_: MsgSetServingKeyResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSetServingKeyResponse>, I>>(base?: I): MsgSetServingKeyResponse {
    return MsgSetServingKeyResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSetServingKeyResponse>, I>>(_: I): MsgSetServingKeyResponse {
    const message = createBaseMsgSetServingKeyResponse();
    return message;
  },
};

function createBaseMsgSetServingInfo(): MsgSetServingInfo {
  return { signer: "", orgId: "", hubEndpoints: [], hubResponsePubkey: "" };
}

export const MsgSetServingInfo: MessageFns<MsgSetServingInfo> = {
  encode(message: MsgSetServingInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.signer !== "") {
      writer.uint32(10).string(message.signer);
    }
    if (message.orgId !== "") {
      writer.uint32(18).string(message.orgId);
    }
    for (const v of message.hubEndpoints) {
      writer.uint32(26).string(v!);
    }
    if (message.hubResponsePubkey !== "") {
      writer.uint32(34).string(message.hubResponsePubkey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSetServingInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSetServingInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signer = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.orgId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.hubEndpoints.push(reader.string());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.hubResponsePubkey = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgSetServingInfo {
    return {
      signer: isSet(object.signer) ? globalThis.String(object.signer) : "",
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
        ? globalThis.String(object.org_id)
        : "",
      hubEndpoints: globalThis.Array.isArray(object?.hubEndpoints)
        ? object.hubEndpoints.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.hub_endpoints)
        ? object.hub_endpoints.map((e: any) => globalThis.String(e))
        : [],
      hubResponsePubkey: isSet(object.hubResponsePubkey)
        ? globalThis.String(object.hubResponsePubkey)
        : isSet(object.hub_response_pubkey)
        ? globalThis.String(object.hub_response_pubkey)
        : "",
    };
  },

  toJSON(message: MsgSetServingInfo): unknown {
    const obj: any = {};
    if (message.signer !== "") {
      obj.signer = message.signer;
    }
    if (message.orgId !== "") {
      obj.orgId = message.orgId;
    }
    if (message.hubEndpoints?.length) {
      obj.hubEndpoints = message.hubEndpoints;
    }
    if (message.hubResponsePubkey !== "") {
      obj.hubResponsePubkey = message.hubResponsePubkey;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSetServingInfo>, I>>(base?: I): MsgSetServingInfo {
    return MsgSetServingInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSetServingInfo>, I>>(object: I): MsgSetServingInfo {
    const message = createBaseMsgSetServingInfo();
    message.signer = object.signer ?? "";
    message.orgId = object.orgId ?? "";
    message.hubEndpoints = object.hubEndpoints?.map((e) => e) || [];
    message.hubResponsePubkey = object.hubResponsePubkey ?? "";
    return message;
  },
};

function createBaseMsgSetServingInfoResponse(): MsgSetServingInfoResponse {
  return {};
}

export const MsgSetServingInfoResponse: MessageFns<MsgSetServingInfoResponse> = {
  encode(_: MsgSetServingInfoResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSetServingInfoResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSetServingInfoResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgSetServingInfoResponse {
    return {};
  },

  toJSON(_: MsgSetServingInfoResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSetServingInfoResponse>, I>>(base?: I): MsgSetServingInfoResponse {
    return MsgSetServingInfoResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSetServingInfoResponse>, I>>(_: I): MsgSetServingInfoResponse {
    const message = createBaseMsgSetServingInfoResponse();
    return message;
  },
};

function createBaseMsgAddMember(): MsgAddMember {
  return { signer: "", orgId: "", pubkey: "", role: "", x25519Pubkey: "", canContribute: false, canModerate: false };
}

export const MsgAddMember: MessageFns<MsgAddMember> = {
  encode(message: MsgAddMember, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.signer !== "") {
      writer.uint32(10).string(message.signer);
    }
    if (message.orgId !== "") {
      writer.uint32(18).string(message.orgId);
    }
    if (message.pubkey !== "") {
      writer.uint32(26).string(message.pubkey);
    }
    if (message.role !== "") {
      writer.uint32(34).string(message.role);
    }
    if (message.x25519Pubkey !== "") {
      writer.uint32(42).string(message.x25519Pubkey);
    }
    if (message.canContribute !== false) {
      writer.uint32(48).bool(message.canContribute);
    }
    if (message.canModerate !== false) {
      writer.uint32(56).bool(message.canModerate);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgAddMember {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgAddMember();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signer = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.orgId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.pubkey = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.role = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.x25519Pubkey = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.canContribute = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.canModerate = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgAddMember {
    return {
      signer: isSet(object.signer) ? globalThis.String(object.signer) : "",
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
        ? globalThis.String(object.org_id)
        : "",
      pubkey: isSet(object.pubkey) ? globalThis.String(object.pubkey) : "",
      role: isSet(object.role) ? globalThis.String(object.role) : "",
      x25519Pubkey: isSet(object.x25519Pubkey)
        ? globalThis.String(object.x25519Pubkey)
        : isSet(object.x25519_pubkey)
        ? globalThis.String(object.x25519_pubkey)
        : "",
      canContribute: isSet(object.canContribute)
        ? globalThis.Boolean(object.canContribute)
        : isSet(object.can_contribute)
        ? globalThis.Boolean(object.can_contribute)
        : false,
      canModerate: isSet(object.canModerate)
        ? globalThis.Boolean(object.canModerate)
        : isSet(object.can_moderate)
        ? globalThis.Boolean(object.can_moderate)
        : false,
    };
  },

  toJSON(message: MsgAddMember): unknown {
    const obj: any = {};
    if (message.signer !== "") {
      obj.signer = message.signer;
    }
    if (message.orgId !== "") {
      obj.orgId = message.orgId;
    }
    if (message.pubkey !== "") {
      obj.pubkey = message.pubkey;
    }
    if (message.role !== "") {
      obj.role = message.role;
    }
    if (message.x25519Pubkey !== "") {
      obj.x25519Pubkey = message.x25519Pubkey;
    }
    if (message.canContribute !== false) {
      obj.canContribute = message.canContribute;
    }
    if (message.canModerate !== false) {
      obj.canModerate = message.canModerate;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgAddMember>, I>>(base?: I): MsgAddMember {
    return MsgAddMember.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgAddMember>, I>>(object: I): MsgAddMember {
    const message = createBaseMsgAddMember();
    message.signer = object.signer ?? "";
    message.orgId = object.orgId ?? "";
    message.pubkey = object.pubkey ?? "";
    message.role = object.role ?? "";
    message.x25519Pubkey = object.x25519Pubkey ?? "";
    message.canContribute = object.canContribute ?? false;
    message.canModerate = object.canModerate ?? false;
    return message;
  },
};

function createBaseMsgAddMemberResponse(): MsgAddMemberResponse {
  return {};
}

export const MsgAddMemberResponse: MessageFns<MsgAddMemberResponse> = {
  encode(_: MsgAddMemberResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgAddMemberResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgAddMemberResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgAddMemberResponse {
    return {};
  },

  toJSON(_: MsgAddMemberResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgAddMemberResponse>, I>>(base?: I): MsgAddMemberResponse {
    return MsgAddMemberResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgAddMemberResponse>, I>>(_: I): MsgAddMemberResponse {
    const message = createBaseMsgAddMemberResponse();
    return message;
  },
};

function createBaseMsgRemoveMember(): MsgRemoveMember {
  return { signer: "", orgId: "", pubkey: "" };
}

export const MsgRemoveMember: MessageFns<MsgRemoveMember> = {
  encode(message: MsgRemoveMember, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.signer !== "") {
      writer.uint32(10).string(message.signer);
    }
    if (message.orgId !== "") {
      writer.uint32(18).string(message.orgId);
    }
    if (message.pubkey !== "") {
      writer.uint32(26).string(message.pubkey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRemoveMember {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRemoveMember();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signer = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.orgId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.pubkey = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgRemoveMember {
    return {
      signer: isSet(object.signer) ? globalThis.String(object.signer) : "",
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
        ? globalThis.String(object.org_id)
        : "",
      pubkey: isSet(object.pubkey) ? globalThis.String(object.pubkey) : "",
    };
  },

  toJSON(message: MsgRemoveMember): unknown {
    const obj: any = {};
    if (message.signer !== "") {
      obj.signer = message.signer;
    }
    if (message.orgId !== "") {
      obj.orgId = message.orgId;
    }
    if (message.pubkey !== "") {
      obj.pubkey = message.pubkey;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRemoveMember>, I>>(base?: I): MsgRemoveMember {
    return MsgRemoveMember.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRemoveMember>, I>>(object: I): MsgRemoveMember {
    const message = createBaseMsgRemoveMember();
    message.signer = object.signer ?? "";
    message.orgId = object.orgId ?? "";
    message.pubkey = object.pubkey ?? "";
    return message;
  },
};

function createBaseMsgRemoveMemberResponse(): MsgRemoveMemberResponse {
  return {};
}

export const MsgRemoveMemberResponse: MessageFns<MsgRemoveMemberResponse> = {
  encode(_: MsgRemoveMemberResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRemoveMemberResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRemoveMemberResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgRemoveMemberResponse {
    return {};
  },

  toJSON(_: MsgRemoveMemberResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRemoveMemberResponse>, I>>(base?: I): MsgRemoveMemberResponse {
    return MsgRemoveMemberResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRemoveMemberResponse>, I>>(_: I): MsgRemoveMemberResponse {
    const message = createBaseMsgRemoveMemberResponse();
    return message;
  },
};

function createBaseMsgUpdateParams(): MsgUpdateParams {
  return { authority: "", params: undefined };
}

export const MsgUpdateParams: MessageFns<MsgUpdateParams> = {
  encode(message: MsgUpdateParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.authority = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateParams {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
    };
  },

  toJSON(message: MsgUpdateParams): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(base?: I): MsgUpdateParams {
    return MsgUpdateParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(object: I): MsgUpdateParams {
    const message = createBaseMsgUpdateParams();
    message.authority = object.authority ?? "";
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseMsgUpdateParamsResponse(): MsgUpdateParamsResponse {
  return {};
}

export const MsgUpdateParamsResponse: MessageFns<MsgUpdateParamsResponse> = {
  encode(_: MsgUpdateParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgUpdateParamsResponse {
    return {};
  },

  toJSON(_: MsgUpdateParamsResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(base?: I): MsgUpdateParamsResponse {
    return MsgUpdateParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(_: I): MsgUpdateParamsResponse {
    const message = createBaseMsgUpdateParamsResponse();
    return message;
  },
};

function createBaseMsgSetOrgConfig(): MsgSetOrgConfig {
  return {
    signer: "",
    orgId: "",
    serveReceiptRequired: false,
    minContributionsPerEpoch: "0",
    contestStakeVibe: "0",
    vocabHash: "",
    embeddingModelId: "",
  };
}

export const MsgSetOrgConfig: MessageFns<MsgSetOrgConfig> = {
  encode(message: MsgSetOrgConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.signer !== "") {
      writer.uint32(10).string(message.signer);
    }
    if (message.orgId !== "") {
      writer.uint32(18).string(message.orgId);
    }
    if (message.serveReceiptRequired !== false) {
      writer.uint32(24).bool(message.serveReceiptRequired);
    }
    if (message.minContributionsPerEpoch !== "0") {
      writer.uint32(32).uint64(message.minContributionsPerEpoch);
    }
    if (message.contestStakeVibe !== "0") {
      writer.uint32(40).uint64(message.contestStakeVibe);
    }
    if (message.vocabHash !== "") {
      writer.uint32(50).string(message.vocabHash);
    }
    if (message.embeddingModelId !== "") {
      writer.uint32(58).string(message.embeddingModelId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSetOrgConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSetOrgConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signer = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.orgId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.serveReceiptRequired = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.minContributionsPerEpoch = reader.uint64().toString();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.contestStakeVibe = reader.uint64().toString();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.vocabHash = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.embeddingModelId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgSetOrgConfig {
    return {
      signer: isSet(object.signer) ? globalThis.String(object.signer) : "",
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
        ? globalThis.String(object.org_id)
        : "",
      serveReceiptRequired: isSet(object.serveReceiptRequired)
        ? globalThis.Boolean(object.serveReceiptRequired)
        : isSet(object.serve_receipt_required)
        ? globalThis.Boolean(object.serve_receipt_required)
        : false,
      minContributionsPerEpoch: isSet(object.minContributionsPerEpoch)
        ? globalThis.String(object.minContributionsPerEpoch)
        : isSet(object.min_contributions_per_epoch)
        ? globalThis.String(object.min_contributions_per_epoch)
        : "0",
      contestStakeVibe: isSet(object.contestStakeVibe)
        ? globalThis.String(object.contestStakeVibe)
        : isSet(object.contest_stake_vibe)
        ? globalThis.String(object.contest_stake_vibe)
        : "0",
      vocabHash: isSet(object.vocabHash)
        ? globalThis.String(object.vocabHash)
        : isSet(object.vocab_hash)
        ? globalThis.String(object.vocab_hash)
        : "",
      embeddingModelId: isSet(object.embeddingModelId)
        ? globalThis.String(object.embeddingModelId)
        : isSet(object.embedding_model_id)
        ? globalThis.String(object.embedding_model_id)
        : "",
    };
  },

  toJSON(message: MsgSetOrgConfig): unknown {
    const obj: any = {};
    if (message.signer !== "") {
      obj.signer = message.signer;
    }
    if (message.orgId !== "") {
      obj.orgId = message.orgId;
    }
    if (message.serveReceiptRequired !== false) {
      obj.serveReceiptRequired = message.serveReceiptRequired;
    }
    if (message.minContributionsPerEpoch !== "0") {
      obj.minContributionsPerEpoch = message.minContributionsPerEpoch;
    }
    if (message.contestStakeVibe !== "0") {
      obj.contestStakeVibe = message.contestStakeVibe;
    }
    if (message.vocabHash !== "") {
      obj.vocabHash = message.vocabHash;
    }
    if (message.embeddingModelId !== "") {
      obj.embeddingModelId = message.embeddingModelId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSetOrgConfig>, I>>(base?: I): MsgSetOrgConfig {
    return MsgSetOrgConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSetOrgConfig>, I>>(object: I): MsgSetOrgConfig {
    const message = createBaseMsgSetOrgConfig();
    message.signer = object.signer ?? "";
    message.orgId = object.orgId ?? "";
    message.serveReceiptRequired = object.serveReceiptRequired ?? false;
    message.minContributionsPerEpoch = object.minContributionsPerEpoch ?? "0";
    message.contestStakeVibe = object.contestStakeVibe ?? "0";
    message.vocabHash = object.vocabHash ?? "";
    message.embeddingModelId = object.embeddingModelId ?? "";
    return message;
  },
};

function createBaseMsgSetOrgConfigResponse(): MsgSetOrgConfigResponse {
  return {};
}

export const MsgSetOrgConfigResponse: MessageFns<MsgSetOrgConfigResponse> = {
  encode(_: MsgSetOrgConfigResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSetOrgConfigResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSetOrgConfigResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgSetOrgConfigResponse {
    return {};
  },

  toJSON(_: MsgSetOrgConfigResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSetOrgConfigResponse>, I>>(base?: I): MsgSetOrgConfigResponse {
    return MsgSetOrgConfigResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSetOrgConfigResponse>, I>>(_: I): MsgSetOrgConfigResponse {
    const message = createBaseMsgSetOrgConfigResponse();
    return message;
  },
};

function createBaseMsgGrantTrialAllowance(): MsgGrantTrialAllowance {
  return { signer: "", orgId: "", grantee: "", dailySubmissions: "0", trialDays: "0" };
}

export const MsgGrantTrialAllowance: MessageFns<MsgGrantTrialAllowance> = {
  encode(message: MsgGrantTrialAllowance, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.signer !== "") {
      writer.uint32(10).string(message.signer);
    }
    if (message.orgId !== "") {
      writer.uint32(18).string(message.orgId);
    }
    if (message.grantee !== "") {
      writer.uint32(26).string(message.grantee);
    }
    if (message.dailySubmissions !== "0") {
      writer.uint32(32).uint64(message.dailySubmissions);
    }
    if (message.trialDays !== "0") {
      writer.uint32(40).uint64(message.trialDays);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgGrantTrialAllowance {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgGrantTrialAllowance();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signer = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.orgId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.grantee = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.dailySubmissions = reader.uint64().toString();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.trialDays = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgGrantTrialAllowance {
    return {
      signer: isSet(object.signer) ? globalThis.String(object.signer) : "",
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
        ? globalThis.String(object.org_id)
        : "",
      grantee: isSet(object.grantee) ? globalThis.String(object.grantee) : "",
      dailySubmissions: isSet(object.dailySubmissions)
        ? globalThis.String(object.dailySubmissions)
        : isSet(object.daily_submissions)
        ? globalThis.String(object.daily_submissions)
        : "0",
      trialDays: isSet(object.trialDays)
        ? globalThis.String(object.trialDays)
        : isSet(object.trial_days)
        ? globalThis.String(object.trial_days)
        : "0",
    };
  },

  toJSON(message: MsgGrantTrialAllowance): unknown {
    const obj: any = {};
    if (message.signer !== "") {
      obj.signer = message.signer;
    }
    if (message.orgId !== "") {
      obj.orgId = message.orgId;
    }
    if (message.grantee !== "") {
      obj.grantee = message.grantee;
    }
    if (message.dailySubmissions !== "0") {
      obj.dailySubmissions = message.dailySubmissions;
    }
    if (message.trialDays !== "0") {
      obj.trialDays = message.trialDays;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgGrantTrialAllowance>, I>>(base?: I): MsgGrantTrialAllowance {
    return MsgGrantTrialAllowance.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgGrantTrialAllowance>, I>>(object: I): MsgGrantTrialAllowance {
    const message = createBaseMsgGrantTrialAllowance();
    message.signer = object.signer ?? "";
    message.orgId = object.orgId ?? "";
    message.grantee = object.grantee ?? "";
    message.dailySubmissions = object.dailySubmissions ?? "0";
    message.trialDays = object.trialDays ?? "0";
    return message;
  },
};

function createBaseMsgGrantTrialAllowanceResponse(): MsgGrantTrialAllowanceResponse {
  return {};
}

export const MsgGrantTrialAllowanceResponse: MessageFns<MsgGrantTrialAllowanceResponse> = {
  encode(_: MsgGrantTrialAllowanceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgGrantTrialAllowanceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgGrantTrialAllowanceResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgGrantTrialAllowanceResponse {
    return {};
  },

  toJSON(_: MsgGrantTrialAllowanceResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgGrantTrialAllowanceResponse>, I>>(base?: I): MsgGrantTrialAllowanceResponse {
    return MsgGrantTrialAllowanceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgGrantTrialAllowanceResponse>, I>>(_: I): MsgGrantTrialAllowanceResponse {
    const message = createBaseMsgGrantTrialAllowanceResponse();
    return message;
  },
};

function createBaseMsgSetMemberCapabilities(): MsgSetMemberCapabilities {
  return { signer: "", orgId: "", pubkey: "", canContribute: false, canModerate: false };
}

export const MsgSetMemberCapabilities: MessageFns<MsgSetMemberCapabilities> = {
  encode(message: MsgSetMemberCapabilities, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.signer !== "") {
      writer.uint32(10).string(message.signer);
    }
    if (message.orgId !== "") {
      writer.uint32(18).string(message.orgId);
    }
    if (message.pubkey !== "") {
      writer.uint32(26).string(message.pubkey);
    }
    if (message.canContribute !== false) {
      writer.uint32(32).bool(message.canContribute);
    }
    if (message.canModerate !== false) {
      writer.uint32(40).bool(message.canModerate);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSetMemberCapabilities {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSetMemberCapabilities();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signer = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.orgId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.pubkey = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.canContribute = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.canModerate = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgSetMemberCapabilities {
    return {
      signer: isSet(object.signer) ? globalThis.String(object.signer) : "",
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
        ? globalThis.String(object.org_id)
        : "",
      pubkey: isSet(object.pubkey) ? globalThis.String(object.pubkey) : "",
      canContribute: isSet(object.canContribute)
        ? globalThis.Boolean(object.canContribute)
        : isSet(object.can_contribute)
        ? globalThis.Boolean(object.can_contribute)
        : false,
      canModerate: isSet(object.canModerate)
        ? globalThis.Boolean(object.canModerate)
        : isSet(object.can_moderate)
        ? globalThis.Boolean(object.can_moderate)
        : false,
    };
  },

  toJSON(message: MsgSetMemberCapabilities): unknown {
    const obj: any = {};
    if (message.signer !== "") {
      obj.signer = message.signer;
    }
    if (message.orgId !== "") {
      obj.orgId = message.orgId;
    }
    if (message.pubkey !== "") {
      obj.pubkey = message.pubkey;
    }
    if (message.canContribute !== false) {
      obj.canContribute = message.canContribute;
    }
    if (message.canModerate !== false) {
      obj.canModerate = message.canModerate;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSetMemberCapabilities>, I>>(base?: I): MsgSetMemberCapabilities {
    return MsgSetMemberCapabilities.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSetMemberCapabilities>, I>>(object: I): MsgSetMemberCapabilities {
    const message = createBaseMsgSetMemberCapabilities();
    message.signer = object.signer ?? "";
    message.orgId = object.orgId ?? "";
    message.pubkey = object.pubkey ?? "";
    message.canContribute = object.canContribute ?? false;
    message.canModerate = object.canModerate ?? false;
    return message;
  },
};

function createBaseMsgSetMemberCapabilitiesResponse(): MsgSetMemberCapabilitiesResponse {
  return {};
}

export const MsgSetMemberCapabilitiesResponse: MessageFns<MsgSetMemberCapabilitiesResponse> = {
  encode(_: MsgSetMemberCapabilitiesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSetMemberCapabilitiesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSetMemberCapabilitiesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgSetMemberCapabilitiesResponse {
    return {};
  },

  toJSON(_: MsgSetMemberCapabilitiesResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSetMemberCapabilitiesResponse>, I>>(
    base?: I,
  ): MsgSetMemberCapabilitiesResponse {
    return MsgSetMemberCapabilitiesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSetMemberCapabilitiesResponse>, I>>(
    _: I,
  ): MsgSetMemberCapabilitiesResponse {
    const message = createBaseMsgSetMemberCapabilitiesResponse();
    return message;
  },
};

function createBaseMsgRotateEpoch(): MsgRotateEpoch {
  return { signer: "", orgId: "" };
}

export const MsgRotateEpoch: MessageFns<MsgRotateEpoch> = {
  encode(message: MsgRotateEpoch, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.signer !== "") {
      writer.uint32(10).string(message.signer);
    }
    if (message.orgId !== "") {
      writer.uint32(18).string(message.orgId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRotateEpoch {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRotateEpoch();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signer = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.orgId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgRotateEpoch {
    return {
      signer: isSet(object.signer) ? globalThis.String(object.signer) : "",
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
        ? globalThis.String(object.org_id)
        : "",
    };
  },

  toJSON(message: MsgRotateEpoch): unknown {
    const obj: any = {};
    if (message.signer !== "") {
      obj.signer = message.signer;
    }
    if (message.orgId !== "") {
      obj.orgId = message.orgId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRotateEpoch>, I>>(base?: I): MsgRotateEpoch {
    return MsgRotateEpoch.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRotateEpoch>, I>>(object: I): MsgRotateEpoch {
    const message = createBaseMsgRotateEpoch();
    message.signer = object.signer ?? "";
    message.orgId = object.orgId ?? "";
    return message;
  },
};

function createBaseMsgRotateEpochResponse(): MsgRotateEpochResponse {
  return { newEpoch: "0" };
}

export const MsgRotateEpochResponse: MessageFns<MsgRotateEpochResponse> = {
  encode(message: MsgRotateEpochResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.newEpoch !== "0") {
      writer.uint32(8).uint64(message.newEpoch);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgRotateEpochResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgRotateEpochResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.newEpoch = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgRotateEpochResponse {
    return {
      newEpoch: isSet(object.newEpoch)
        ? globalThis.String(object.newEpoch)
        : isSet(object.new_epoch)
        ? globalThis.String(object.new_epoch)
        : "0",
    };
  },

  toJSON(message: MsgRotateEpochResponse): unknown {
    const obj: any = {};
    if (message.newEpoch !== "0") {
      obj.newEpoch = message.newEpoch;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgRotateEpochResponse>, I>>(base?: I): MsgRotateEpochResponse {
    return MsgRotateEpochResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgRotateEpochResponse>, I>>(object: I): MsgRotateEpochResponse {
    const message = createBaseMsgRotateEpochResponse();
    message.newEpoch = object.newEpoch ?? "0";
    return message;
  },
};

function createBaseMsgTransferLeadership(): MsgTransferLeadership {
  return { signer: "", orgId: "", newLeader: "", newLeaderWallet: "" };
}

export const MsgTransferLeadership: MessageFns<MsgTransferLeadership> = {
  encode(message: MsgTransferLeadership, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.signer !== "") {
      writer.uint32(10).string(message.signer);
    }
    if (message.orgId !== "") {
      writer.uint32(18).string(message.orgId);
    }
    if (message.newLeader !== "") {
      writer.uint32(26).string(message.newLeader);
    }
    if (message.newLeaderWallet !== "") {
      writer.uint32(34).string(message.newLeaderWallet);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgTransferLeadership {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgTransferLeadership();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signer = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.orgId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.newLeader = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.newLeaderWallet = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgTransferLeadership {
    return {
      signer: isSet(object.signer) ? globalThis.String(object.signer) : "",
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
        ? globalThis.String(object.org_id)
        : "",
      newLeader: isSet(object.newLeader)
        ? globalThis.String(object.newLeader)
        : isSet(object.new_leader)
        ? globalThis.String(object.new_leader)
        : "",
      newLeaderWallet: isSet(object.newLeaderWallet)
        ? globalThis.String(object.newLeaderWallet)
        : isSet(object.new_leader_wallet)
        ? globalThis.String(object.new_leader_wallet)
        : "",
    };
  },

  toJSON(message: MsgTransferLeadership): unknown {
    const obj: any = {};
    if (message.signer !== "") {
      obj.signer = message.signer;
    }
    if (message.orgId !== "") {
      obj.orgId = message.orgId;
    }
    if (message.newLeader !== "") {
      obj.newLeader = message.newLeader;
    }
    if (message.newLeaderWallet !== "") {
      obj.newLeaderWallet = message.newLeaderWallet;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgTransferLeadership>, I>>(base?: I): MsgTransferLeadership {
    return MsgTransferLeadership.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgTransferLeadership>, I>>(object: I): MsgTransferLeadership {
    const message = createBaseMsgTransferLeadership();
    message.signer = object.signer ?? "";
    message.orgId = object.orgId ?? "";
    message.newLeader = object.newLeader ?? "";
    message.newLeaderWallet = object.newLeaderWallet ?? "";
    return message;
  },
};

function createBaseMsgTransferLeadershipResponse(): MsgTransferLeadershipResponse {
  return {};
}

export const MsgTransferLeadershipResponse: MessageFns<MsgTransferLeadershipResponse> = {
  encode(_: MsgTransferLeadershipResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgTransferLeadershipResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgTransferLeadershipResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgTransferLeadershipResponse {
    return {};
  },

  toJSON(_: MsgTransferLeadershipResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgTransferLeadershipResponse>, I>>(base?: I): MsgTransferLeadershipResponse {
    return MsgTransferLeadershipResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgTransferLeadershipResponse>, I>>(_: I): MsgTransferLeadershipResponse {
    const message = createBaseMsgTransferLeadershipResponse();
    return message;
  },
};

function createBaseMsgCloseOrg(): MsgCloseOrg {
  return { signer: "", orgId: "" };
}

export const MsgCloseOrg: MessageFns<MsgCloseOrg> = {
  encode(message: MsgCloseOrg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.signer !== "") {
      writer.uint32(10).string(message.signer);
    }
    if (message.orgId !== "") {
      writer.uint32(18).string(message.orgId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCloseOrg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCloseOrg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signer = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.orgId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgCloseOrg {
    return {
      signer: isSet(object.signer) ? globalThis.String(object.signer) : "",
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
        ? globalThis.String(object.org_id)
        : "",
    };
  },

  toJSON(message: MsgCloseOrg): unknown {
    const obj: any = {};
    if (message.signer !== "") {
      obj.signer = message.signer;
    }
    if (message.orgId !== "") {
      obj.orgId = message.orgId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCloseOrg>, I>>(base?: I): MsgCloseOrg {
    return MsgCloseOrg.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCloseOrg>, I>>(object: I): MsgCloseOrg {
    const message = createBaseMsgCloseOrg();
    message.signer = object.signer ?? "";
    message.orgId = object.orgId ?? "";
    return message;
  },
};

function createBaseMsgCloseOrgResponse(): MsgCloseOrgResponse {
  return {};
}

export const MsgCloseOrgResponse: MessageFns<MsgCloseOrgResponse> = {
  encode(_: MsgCloseOrgResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgCloseOrgResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgCloseOrgResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgCloseOrgResponse {
    return {};
  },

  toJSON(_: MsgCloseOrgResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgCloseOrgResponse>, I>>(base?: I): MsgCloseOrgResponse {
    return MsgCloseOrgResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgCloseOrgResponse>, I>>(_: I): MsgCloseOrgResponse {
    const message = createBaseMsgCloseOrgResponse();
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
