// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               unknown
// source: wevibe/serve/v1/params.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "wevibe.serve.v1";

export interface Params {
  maxServesPerBatch: number;
  selfServeDiscountPercent: number;
  maxServesPerMemoryPerEpoch: number;
  minOrgAgeEpochs: string;
  diminishingReturnsThreshold: string;
}

function createBaseParams(): Params {
  return {
    maxServesPerBatch: 0,
    selfServeDiscountPercent: 0,
    maxServesPerMemoryPerEpoch: 0,
    minOrgAgeEpochs: "0",
    diminishingReturnsThreshold: "0",
  };
}

export const Params: MessageFns<Params> = {
  encode(message: Params, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.maxServesPerBatch !== 0) {
      writer.uint32(8).uint32(message.maxServesPerBatch);
    }
    if (message.selfServeDiscountPercent !== 0) {
      writer.uint32(16).uint32(message.selfServeDiscountPercent);
    }
    if (message.maxServesPerMemoryPerEpoch !== 0) {
      writer.uint32(24).uint32(message.maxServesPerMemoryPerEpoch);
    }
    if (message.minOrgAgeEpochs !== "0") {
      writer.uint32(32).uint64(message.minOrgAgeEpochs);
    }
    if (message.diminishingReturnsThreshold !== "0") {
      writer.uint32(40).uint64(message.diminishingReturnsThreshold);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Params {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.maxServesPerBatch = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.selfServeDiscountPercent = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.maxServesPerMemoryPerEpoch = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.minOrgAgeEpochs = reader.uint64().toString();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.diminishingReturnsThreshold = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Params {
    return {
      maxServesPerBatch: isSet(object.maxServesPerBatch)
        ? globalThis.Number(object.maxServesPerBatch)
        : isSet(object.max_serves_per_batch)
        ? globalThis.Number(object.max_serves_per_batch)
        : 0,
      selfServeDiscountPercent: isSet(object.selfServeDiscountPercent)
        ? globalThis.Number(object.selfServeDiscountPercent)
        : isSet(object.self_serve_discount_percent)
        ? globalThis.Number(object.self_serve_discount_percent)
        : 0,
      maxServesPerMemoryPerEpoch: isSet(object.maxServesPerMemoryPerEpoch)
        ? globalThis.Number(object.maxServesPerMemoryPerEpoch)
        : isSet(object.max_serves_per_memory_per_epoch)
        ? globalThis.Number(object.max_serves_per_memory_per_epoch)
        : 0,
      minOrgAgeEpochs: isSet(object.minOrgAgeEpochs)
        ? globalThis.String(object.minOrgAgeEpochs)
        : isSet(object.min_org_age_epochs)
        ? globalThis.String(object.min_org_age_epochs)
        : "0",
      diminishingReturnsThreshold: isSet(object.diminishingReturnsThreshold)
        ? globalThis.String(object.diminishingReturnsThreshold)
        : isSet(object.diminishing_returns_threshold)
        ? globalThis.String(object.diminishing_returns_threshold)
        : "0",
    };
  },

  toJSON(message: Params): unknown {
    const obj: any = {};
    if (message.maxServesPerBatch !== 0) {
      obj.maxServesPerBatch = Math.round(message.maxServesPerBatch);
    }
    if (message.selfServeDiscountPercent !== 0) {
      obj.selfServeDiscountPercent = Math.round(message.selfServeDiscountPercent);
    }
    if (message.maxServesPerMemoryPerEpoch !== 0) {
      obj.maxServesPerMemoryPerEpoch = Math.round(message.maxServesPerMemoryPerEpoch);
    }
    if (message.minOrgAgeEpochs !== "0") {
      obj.minOrgAgeEpochs = message.minOrgAgeEpochs;
    }
    if (message.diminishingReturnsThreshold !== "0") {
      obj.diminishingReturnsThreshold = message.diminishingReturnsThreshold;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Params>, I>>(base?: I): Params {
    return Params.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Params>, I>>(object: I): Params {
    const message = createBaseParams();
    message.maxServesPerBatch = object.maxServesPerBatch ?? 0;
    message.selfServeDiscountPercent = object.selfServeDiscountPercent ?? 0;
    message.maxServesPerMemoryPerEpoch = object.maxServesPerMemoryPerEpoch ?? 0;
    message.minOrgAgeEpochs = object.minOrgAgeEpochs ?? "0";
    message.diminishingReturnsThreshold = object.diminishingReturnsThreshold ?? "0";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
