// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               unknown
// source: wevibe/serve/v1/query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Params } from "./params";
import { StoredContributorEpochServes, StoredEpochServeStats } from "./state";

export const protobufPackage = "wevibe.serve.v1";

export interface QueryGetEpochServeStatsRequest {
  orgId: string;
  epoch: string;
}

export interface QueryGetEpochServeStatsResponse {
  stats?: StoredEpochServeStats | undefined;
}

export interface QueryGetContributorServesRequest {
  contributorId: string;
  epoch: string;
}

export interface QueryGetContributorServesResponse {
  serves?: StoredContributorEpochServes | undefined;
}

export interface QueryGetMemoryServeCountRequest {
  orgId: string;
  contentHash: Uint8Array;
  epoch: string;
}

export interface QueryGetMemoryServeCountResponse {
  count: string;
}

export interface QueryParamsRequest {
}

export interface QueryParamsResponse {
  params?: Params | undefined;
}

function createBaseQueryGetEpochServeStatsRequest(): QueryGetEpochServeStatsRequest {
  return { orgId: "", epoch: "0" };
}

export const QueryGetEpochServeStatsRequest: MessageFns<QueryGetEpochServeStatsRequest> = {
  encode(message: QueryGetEpochServeStatsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orgId !== "") {
      writer.uint32(10).string(message.orgId);
    }
    if (message.epoch !== "0") {
      writer.uint32(16).uint64(message.epoch);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetEpochServeStatsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetEpochServeStatsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orgId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.epoch = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetEpochServeStatsRequest {
    return {
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
        ? globalThis.String(object.org_id)
        : "",
      epoch: isSet(object.epoch) ? globalThis.String(object.epoch) : "0",
    };
  },

  toJSON(message: QueryGetEpochServeStatsRequest): unknown {
    const obj: any = {};
    if (message.orgId !== "") {
      obj.orgId = message.orgId;
    }
    if (message.epoch !== "0") {
      obj.epoch = message.epoch;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetEpochServeStatsRequest>, I>>(base?: I): QueryGetEpochServeStatsRequest {
    return QueryGetEpochServeStatsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetEpochServeStatsRequest>, I>>(
    object: I,
  ): QueryGetEpochServeStatsRequest {
    const message = createBaseQueryGetEpochServeStatsRequest();
    message.orgId = object.orgId ?? "";
    message.epoch = object.epoch ?? "0";
    return message;
  },
};

function createBaseQueryGetEpochServeStatsResponse(): QueryGetEpochServeStatsResponse {
  return { stats: undefined };
}

export const QueryGetEpochServeStatsResponse: MessageFns<QueryGetEpochServeStatsResponse> = {
  encode(message: QueryGetEpochServeStatsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stats !== undefined) {
      StoredEpochServeStats.encode(message.stats, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetEpochServeStatsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetEpochServeStatsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.stats = StoredEpochServeStats.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetEpochServeStatsResponse {
    return { stats: isSet(object.stats) ? StoredEpochServeStats.fromJSON(object.stats) : undefined };
  },

  toJSON(message: QueryGetEpochServeStatsResponse): unknown {
    const obj: any = {};
    if (message.stats !== undefined) {
      obj.stats = StoredEpochServeStats.toJSON(message.stats);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetEpochServeStatsResponse>, I>>(base?: I): QueryGetEpochServeStatsResponse {
    return QueryGetEpochServeStatsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetEpochServeStatsResponse>, I>>(
    object: I,
  ): QueryGetEpochServeStatsResponse {
    const message = createBaseQueryGetEpochServeStatsResponse();
    message.stats = (object.stats !== undefined && object.stats !== null)
      ? StoredEpochServeStats.fromPartial(object.stats)
      : undefined;
    return message;
  },
};

function createBaseQueryGetContributorServesRequest(): QueryGetContributorServesRequest {
  return { contributorId: "", epoch: "0" };
}

export const QueryGetContributorServesRequest: MessageFns<QueryGetContributorServesRequest> = {
  encode(message: QueryGetContributorServesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.contributorId !== "") {
      writer.uint32(10).string(message.contributorId);
    }
    if (message.epoch !== "0") {
      writer.uint32(16).uint64(message.epoch);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetContributorServesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetContributorServesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.contributorId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.epoch = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetContributorServesRequest {
    return {
      contributorId: isSet(object.contributorId)
        ? globalThis.String(object.contributorId)
        : isSet(object.contributor_id)
        ? globalThis.String(object.contributor_id)
        : "",
      epoch: isSet(object.epoch) ? globalThis.String(object.epoch) : "0",
    };
  },

  toJSON(message: QueryGetContributorServesRequest): unknown {
    const obj: any = {};
    if (message.contributorId !== "") {
      obj.contributorId = message.contributorId;
    }
    if (message.epoch !== "0") {
      obj.epoch = message.epoch;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetContributorServesRequest>, I>>(
    base?: I,
  ): QueryGetContributorServesRequest {
    return QueryGetContributorServesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetContributorServesRequest>, I>>(
    object: I,
  ): QueryGetContributorServesRequest {
    const message = createBaseQueryGetContributorServesRequest();
    message.contributorId = object.contributorId ?? "";
    message.epoch = object.epoch ?? "0";
    return message;
  },
};

function createBaseQueryGetContributorServesResponse(): QueryGetContributorServesResponse {
  return { serves: undefined };
}

export const QueryGetContributorServesResponse: MessageFns<QueryGetContributorServesResponse> = {
  encode(message: QueryGetContributorServesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serves !== undefined) {
      StoredContributorEpochServes.encode(message.serves, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetContributorServesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetContributorServesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serves = StoredContributorEpochServes.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetContributorServesResponse {
    return { serves: isSet(object.serves) ? StoredContributorEpochServes.fromJSON(object.serves) : undefined };
  },

  toJSON(message: QueryGetContributorServesResponse): unknown {
    const obj: any = {};
    if (message.serves !== undefined) {
      obj.serves = StoredContributorEpochServes.toJSON(message.serves);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetContributorServesResponse>, I>>(
    base?: I,
  ): QueryGetContributorServesResponse {
    return QueryGetContributorServesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetContributorServesResponse>, I>>(
    object: I,
  ): QueryGetContributorServesResponse {
    const message = createBaseQueryGetContributorServesResponse();
    message.serves = (object.serves !== undefined && object.serves !== null)
      ? StoredContributorEpochServes.fromPartial(object.serves)
      : undefined;
    return message;
  },
};

function createBaseQueryGetMemoryServeCountRequest(): QueryGetMemoryServeCountRequest {
  return { orgId: "", contentHash: new Uint8Array(0), epoch: "0" };
}

export const QueryGetMemoryServeCountRequest: MessageFns<QueryGetMemoryServeCountRequest> = {
  encode(message: QueryGetMemoryServeCountRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orgId !== "") {
      writer.uint32(10).string(message.orgId);
    }
    if (message.contentHash.length !== 0) {
      writer.uint32(18).bytes(message.contentHash);
    }
    if (message.epoch !== "0") {
      writer.uint32(24).uint64(message.epoch);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetMemoryServeCountRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetMemoryServeCountRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orgId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.contentHash = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.epoch = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetMemoryServeCountRequest {
    return {
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
        ? globalThis.String(object.org_id)
        : "",
      contentHash: isSet(object.contentHash)
        ? bytesFromBase64(object.contentHash)
        : isSet(object.content_hash)
        ? bytesFromBase64(object.content_hash)
        : new Uint8Array(0),
      epoch: isSet(object.epoch) ? globalThis.String(object.epoch) : "0",
    };
  },

  toJSON(message: QueryGetMemoryServeCountRequest): unknown {
    const obj: any = {};
    if (message.orgId !== "") {
      obj.orgId = message.orgId;
    }
    if (message.contentHash.length !== 0) {
      obj.contentHash = base64FromBytes(message.contentHash);
    }
    if (message.epoch !== "0") {
      obj.epoch = message.epoch;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetMemoryServeCountRequest>, I>>(base?: I): QueryGetMemoryServeCountRequest {
    return QueryGetMemoryServeCountRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetMemoryServeCountRequest>, I>>(
    object: I,
  ): QueryGetMemoryServeCountRequest {
    const message = createBaseQueryGetMemoryServeCountRequest();
    message.orgId = object.orgId ?? "";
    message.contentHash = object.contentHash ?? new Uint8Array(0);
    message.epoch = object.epoch ?? "0";
    return message;
  },
};

function createBaseQueryGetMemoryServeCountResponse(): QueryGetMemoryServeCountResponse {
  return { count: "0" };
}

export const QueryGetMemoryServeCountResponse: MessageFns<QueryGetMemoryServeCountResponse> = {
  encode(message: QueryGetMemoryServeCountResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.count !== "0") {
      writer.uint32(8).uint64(message.count);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetMemoryServeCountResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetMemoryServeCountResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.count = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetMemoryServeCountResponse {
    return { count: isSet(object.count) ? globalThis.String(object.count) : "0" };
  },

  toJSON(message: QueryGetMemoryServeCountResponse): unknown {
    const obj: any = {};
    if (message.count !== "0") {
      obj.count = message.count;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetMemoryServeCountResponse>, I>>(
    base?: I,
  ): QueryGetMemoryServeCountResponse {
    return QueryGetMemoryServeCountResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetMemoryServeCountResponse>, I>>(
    object: I,
  ): QueryGetMemoryServeCountResponse {
    const message = createBaseQueryGetMemoryServeCountResponse();
    message.count = object.count ?? "0";
    return message;
  },
};

function createBaseQueryParamsRequest(): QueryParamsRequest {
  return {};
}

export const QueryParamsRequest: MessageFns<QueryParamsRequest> = {
  encode(_: QueryParamsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryParamsRequest {
    return {};
  },

  toJSON(_: QueryParamsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(base?: I): QueryParamsRequest {
    return QueryParamsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(_: I): QueryParamsRequest {
    const message = createBaseQueryParamsRequest();
    return message;
  },
};

function createBaseQueryParamsResponse(): QueryParamsResponse {
  return { params: undefined };
}

export const QueryParamsResponse: MessageFns<QueryParamsResponse> = {
  encode(message: QueryParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryParamsResponse {
    return { params: isSet(object.params) ? Params.fromJSON(object.params) : undefined };
  },

  toJSON(message: QueryParamsResponse): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(base?: I): QueryParamsResponse {
    return QueryParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(object: I): QueryParamsResponse {
    const message = createBaseQueryParamsResponse();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
