// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: wevibe/serve/v1/state.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "wevibe.serve.v1";

export interface StoredServeReceipt {
  orgId: string;
  memoryContentHash: Uint8Array;
  contributorId: string;
  epoch: string;
  isSelfServe: boolean;
  modelId: string;
  turnCount: number;
  /**
   * Matched-keyword set captured from the originating serve TX.
   * Per D-4.2 Implementation Clarifications (DMO-007).
   */
  matchedKeywords: string[];
  serveKeyPubkey: Uint8Array;
  fingerprint: Uint8Array;
}

export interface StoredDenialReceipt {
  orgId: string;
  memoryHash: Uint8Array;
  denyKey: string;
  reason: string;
  epoch: string;
  serveFingerprint: Uint8Array;
  serveKeyPubkey: Uint8Array;
}

export interface StoredEpochServeStats {
  orgId: string;
  epoch: string;
  totalServes: string;
  uniqueMemoriesServed: string;
  uniqueServeKeys: string;
  selfServes: string;
  modelBreakdown: { [key: string]: string };
  totalDenials: string;
}

export interface StoredEpochServeStats_ModelBreakdownEntry {
  key: string;
  value: string;
}

export interface StoredContributorEpochServes {
  contributorId: string;
  epoch: string;
  serveCount: string;
  selfServeCount: string;
  orgIds: string[];
  totalTurns: string;
}

function createBaseStoredServeReceipt(): StoredServeReceipt {
  return {
    orgId: "",
    memoryContentHash: new Uint8Array(0),
    contributorId: "",
    epoch: "0",
    isSelfServe: false,
    modelId: "",
    turnCount: 0,
    matchedKeywords: [],
    serveKeyPubkey: new Uint8Array(0),
    fingerprint: new Uint8Array(0),
  };
}

export const StoredServeReceipt: MessageFns<StoredServeReceipt> = {
  encode(message: StoredServeReceipt, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orgId !== "") {
      writer.uint32(10).string(message.orgId);
    }
    if (message.memoryContentHash.length !== 0) {
      writer.uint32(18).bytes(message.memoryContentHash);
    }
    if (message.contributorId !== "") {
      writer.uint32(34).string(message.contributorId);
    }
    if (message.epoch !== "0") {
      writer.uint32(40).uint64(message.epoch);
    }
    if (message.isSelfServe !== false) {
      writer.uint32(56).bool(message.isSelfServe);
    }
    if (message.modelId !== "") {
      writer.uint32(66).string(message.modelId);
    }
    if (message.turnCount !== 0) {
      writer.uint32(72).uint32(message.turnCount);
    }
    for (const v of message.matchedKeywords) {
      writer.uint32(82).string(v!);
    }
    if (message.serveKeyPubkey.length !== 0) {
      writer.uint32(90).bytes(message.serveKeyPubkey);
    }
    if (message.fingerprint.length !== 0) {
      writer.uint32(98).bytes(message.fingerprint);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StoredServeReceipt {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoredServeReceipt();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orgId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.memoryContentHash = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.contributorId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.epoch = reader.uint64().toString();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.isSelfServe = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.modelId = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.turnCount = reader.uint32();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.matchedKeywords.push(reader.string());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.serveKeyPubkey = reader.bytes();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.fingerprint = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoredServeReceipt {
    return {
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
        ? globalThis.String(object.org_id)
        : "",
      memoryContentHash: isSet(object.memoryContentHash)
        ? bytesFromBase64(object.memoryContentHash)
        : isSet(object.memory_content_hash)
        ? bytesFromBase64(object.memory_content_hash)
        : new Uint8Array(0),
      contributorId: isSet(object.contributorId)
        ? globalThis.String(object.contributorId)
        : isSet(object.contributor_id)
        ? globalThis.String(object.contributor_id)
        : "",
      epoch: isSet(object.epoch) ? globalThis.String(object.epoch) : "0",
      isSelfServe: isSet(object.isSelfServe)
        ? globalThis.Boolean(object.isSelfServe)
        : isSet(object.is_self_serve)
        ? globalThis.Boolean(object.is_self_serve)
        : false,
      modelId: isSet(object.modelId)
        ? globalThis.String(object.modelId)
        : isSet(object.model_id)
        ? globalThis.String(object.model_id)
        : "",
      turnCount: isSet(object.turnCount)
        ? globalThis.Number(object.turnCount)
        : isSet(object.turn_count)
        ? globalThis.Number(object.turn_count)
        : 0,
      matchedKeywords: globalThis.Array.isArray(object?.matchedKeywords)
        ? object.matchedKeywords.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.matched_keywords)
        ? object.matched_keywords.map((e: any) => globalThis.String(e))
        : [],
      serveKeyPubkey: isSet(object.serveKeyPubkey)
        ? bytesFromBase64(object.serveKeyPubkey)
        : isSet(object.serve_key_pubkey)
        ? bytesFromBase64(object.serve_key_pubkey)
        : new Uint8Array(0),
      fingerprint: isSet(object.fingerprint) ? bytesFromBase64(object.fingerprint) : new Uint8Array(0),
    };
  },

  toJSON(message: StoredServeReceipt): unknown {
    const obj: any = {};
    if (message.orgId !== "") {
      obj.orgId = message.orgId;
    }
    if (message.memoryContentHash.length !== 0) {
      obj.memoryContentHash = base64FromBytes(message.memoryContentHash);
    }
    if (message.contributorId !== "") {
      obj.contributorId = message.contributorId;
    }
    if (message.epoch !== "0") {
      obj.epoch = message.epoch;
    }
    if (message.isSelfServe !== false) {
      obj.isSelfServe = message.isSelfServe;
    }
    if (message.modelId !== "") {
      obj.modelId = message.modelId;
    }
    if (message.turnCount !== 0) {
      obj.turnCount = Math.round(message.turnCount);
    }
    if (message.matchedKeywords?.length) {
      obj.matchedKeywords = message.matchedKeywords;
    }
    if (message.serveKeyPubkey.length !== 0) {
      obj.serveKeyPubkey = base64FromBytes(message.serveKeyPubkey);
    }
    if (message.fingerprint.length !== 0) {
      obj.fingerprint = base64FromBytes(message.fingerprint);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StoredServeReceipt>, I>>(base?: I): StoredServeReceipt {
    return StoredServeReceipt.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StoredServeReceipt>, I>>(object: I): StoredServeReceipt {
    const message = createBaseStoredServeReceipt();
    message.orgId = object.orgId ?? "";
    message.memoryContentHash = object.memoryContentHash ?? new Uint8Array(0);
    message.contributorId = object.contributorId ?? "";
    message.epoch = object.epoch ?? "0";
    message.isSelfServe = object.isSelfServe ?? false;
    message.modelId = object.modelId ?? "";
    message.turnCount = object.turnCount ?? 0;
    message.matchedKeywords = object.matchedKeywords?.map((e) => e) || [];
    message.serveKeyPubkey = object.serveKeyPubkey ?? new Uint8Array(0);
    message.fingerprint = object.fingerprint ?? new Uint8Array(0);
    return message;
  },
};

function createBaseStoredDenialReceipt(): StoredDenialReceipt {
  return {
    orgId: "",
    memoryHash: new Uint8Array(0),
    denyKey: "",
    reason: "",
    epoch: "0",
    serveFingerprint: new Uint8Array(0),
    serveKeyPubkey: new Uint8Array(0),
  };
}

export const StoredDenialReceipt: MessageFns<StoredDenialReceipt> = {
  encode(message: StoredDenialReceipt, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orgId !== "") {
      writer.uint32(10).string(message.orgId);
    }
    if (message.memoryHash.length !== 0) {
      writer.uint32(18).bytes(message.memoryHash);
    }
    if (message.denyKey !== "") {
      writer.uint32(26).string(message.denyKey);
    }
    if (message.reason !== "") {
      writer.uint32(34).string(message.reason);
    }
    if (message.epoch !== "0") {
      writer.uint32(40).uint64(message.epoch);
    }
    if (message.serveFingerprint.length !== 0) {
      writer.uint32(58).bytes(message.serveFingerprint);
    }
    if (message.serveKeyPubkey.length !== 0) {
      writer.uint32(66).bytes(message.serveKeyPubkey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StoredDenialReceipt {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoredDenialReceipt();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orgId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.memoryHash = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.denyKey = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.reason = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.epoch = reader.uint64().toString();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.serveFingerprint = reader.bytes();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.serveKeyPubkey = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoredDenialReceipt {
    return {
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
        ? globalThis.String(object.org_id)
        : "",
      memoryHash: isSet(object.memoryHash)
        ? bytesFromBase64(object.memoryHash)
        : isSet(object.memory_hash)
        ? bytesFromBase64(object.memory_hash)
        : new Uint8Array(0),
      denyKey: isSet(object.denyKey)
        ? globalThis.String(object.denyKey)
        : isSet(object.deny_key)
        ? globalThis.String(object.deny_key)
        : "",
      reason: isSet(object.reason) ? globalThis.String(object.reason) : "",
      epoch: isSet(object.epoch) ? globalThis.String(object.epoch) : "0",
      serveFingerprint: isSet(object.serveFingerprint)
        ? bytesFromBase64(object.serveFingerprint)
        : isSet(object.serve_fingerprint)
        ? bytesFromBase64(object.serve_fingerprint)
        : new Uint8Array(0),
      serveKeyPubkey: isSet(object.serveKeyPubkey)
        ? bytesFromBase64(object.serveKeyPubkey)
        : isSet(object.serve_key_pubkey)
        ? bytesFromBase64(object.serve_key_pubkey)
        : new Uint8Array(0),
    };
  },

  toJSON(message: StoredDenialReceipt): unknown {
    const obj: any = {};
    if (message.orgId !== "") {
      obj.orgId = message.orgId;
    }
    if (message.memoryHash.length !== 0) {
      obj.memoryHash = base64FromBytes(message.memoryHash);
    }
    if (message.denyKey !== "") {
      obj.denyKey = message.denyKey;
    }
    if (message.reason !== "") {
      obj.reason = message.reason;
    }
    if (message.epoch !== "0") {
      obj.epoch = message.epoch;
    }
    if (message.serveFingerprint.length !== 0) {
      obj.serveFingerprint = base64FromBytes(message.serveFingerprint);
    }
    if (message.serveKeyPubkey.length !== 0) {
      obj.serveKeyPubkey = base64FromBytes(message.serveKeyPubkey);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StoredDenialReceipt>, I>>(base?: I): StoredDenialReceipt {
    return StoredDenialReceipt.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StoredDenialReceipt>, I>>(object: I): StoredDenialReceipt {
    const message = createBaseStoredDenialReceipt();
    message.orgId = object.orgId ?? "";
    message.memoryHash = object.memoryHash ?? new Uint8Array(0);
    message.denyKey = object.denyKey ?? "";
    message.reason = object.reason ?? "";
    message.epoch = object.epoch ?? "0";
    message.serveFingerprint = object.serveFingerprint ?? new Uint8Array(0);
    message.serveKeyPubkey = object.serveKeyPubkey ?? new Uint8Array(0);
    return message;
  },
};

function createBaseStoredEpochServeStats(): StoredEpochServeStats {
  return {
    orgId: "",
    epoch: "0",
    totalServes: "0",
    uniqueMemoriesServed: "0",
    uniqueServeKeys: "0",
    selfServes: "0",
    modelBreakdown: {},
    totalDenials: "0",
  };
}

export const StoredEpochServeStats: MessageFns<StoredEpochServeStats> = {
  encode(message: StoredEpochServeStats, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orgId !== "") {
      writer.uint32(10).string(message.orgId);
    }
    if (message.epoch !== "0") {
      writer.uint32(16).uint64(message.epoch);
    }
    if (message.totalServes !== "0") {
      writer.uint32(24).uint64(message.totalServes);
    }
    if (message.uniqueMemoriesServed !== "0") {
      writer.uint32(32).uint64(message.uniqueMemoriesServed);
    }
    if (message.uniqueServeKeys !== "0") {
      writer.uint32(40).uint64(message.uniqueServeKeys);
    }
    if (message.selfServes !== "0") {
      writer.uint32(48).uint64(message.selfServes);
    }
    globalThis.Object.entries(message.modelBreakdown).forEach(([key, value]: [string, string]) => {
      StoredEpochServeStats_ModelBreakdownEntry.encode({ key: key as any, value }, writer.uint32(58).fork()).join();
    });
    if (message.totalDenials !== "0") {
      writer.uint32(64).uint64(message.totalDenials);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StoredEpochServeStats {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoredEpochServeStats();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orgId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.epoch = reader.uint64().toString();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.totalServes = reader.uint64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.uniqueMemoriesServed = reader.uint64().toString();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.uniqueServeKeys = reader.uint64().toString();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.selfServes = reader.uint64().toString();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          const entry7 = StoredEpochServeStats_ModelBreakdownEntry.decode(reader, reader.uint32());
          if (entry7.value !== undefined) {
            message.modelBreakdown[entry7.key] = entry7.value;
          }
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.totalDenials = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoredEpochServeStats {
    return {
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
        ? globalThis.String(object.org_id)
        : "",
      epoch: isSet(object.epoch) ? globalThis.String(object.epoch) : "0",
      totalServes: isSet(object.totalServes)
        ? globalThis.String(object.totalServes)
        : isSet(object.total_serves)
        ? globalThis.String(object.total_serves)
        : "0",
      uniqueMemoriesServed: isSet(object.uniqueMemoriesServed)
        ? globalThis.String(object.uniqueMemoriesServed)
        : isSet(object.unique_memories_served)
        ? globalThis.String(object.unique_memories_served)
        : "0",
      uniqueServeKeys: isSet(object.uniqueServeKeys)
        ? globalThis.String(object.uniqueServeKeys)
        : isSet(object.unique_serve_keys)
        ? globalThis.String(object.unique_serve_keys)
        : "0",
      selfServes: isSet(object.selfServes)
        ? globalThis.String(object.selfServes)
        : isSet(object.self_serves)
        ? globalThis.String(object.self_serves)
        : "0",
      modelBreakdown: isObject(object.modelBreakdown)
        ? (globalThis.Object.entries(object.modelBreakdown) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : isObject(object.model_breakdown)
        ? (globalThis.Object.entries(object.model_breakdown) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
      totalDenials: isSet(object.totalDenials)
        ? globalThis.String(object.totalDenials)
        : isSet(object.total_denials)
        ? globalThis.String(object.total_denials)
        : "0",
    };
  },

  toJSON(message: StoredEpochServeStats): unknown {
    const obj: any = {};
    if (message.orgId !== "") {
      obj.orgId = message.orgId;
    }
    if (message.epoch !== "0") {
      obj.epoch = message.epoch;
    }
    if (message.totalServes !== "0") {
      obj.totalServes = message.totalServes;
    }
    if (message.uniqueMemoriesServed !== "0") {
      obj.uniqueMemoriesServed = message.uniqueMemoriesServed;
    }
    if (message.uniqueServeKeys !== "0") {
      obj.uniqueServeKeys = message.uniqueServeKeys;
    }
    if (message.selfServes !== "0") {
      obj.selfServes = message.selfServes;
    }
    if (message.modelBreakdown) {
      const entries = globalThis.Object.entries(message.modelBreakdown) as [string, string][];
      if (entries.length > 0) {
        obj.modelBreakdown = {};
        entries.forEach(([k, v]) => {
          obj.modelBreakdown[k] = v;
        });
      }
    }
    if (message.totalDenials !== "0") {
      obj.totalDenials = message.totalDenials;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StoredEpochServeStats>, I>>(base?: I): StoredEpochServeStats {
    return StoredEpochServeStats.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StoredEpochServeStats>, I>>(object: I): StoredEpochServeStats {
    const message = createBaseStoredEpochServeStats();
    message.orgId = object.orgId ?? "";
    message.epoch = object.epoch ?? "0";
    message.totalServes = object.totalServes ?? "0";
    message.uniqueMemoriesServed = object.uniqueMemoriesServed ?? "0";
    message.uniqueServeKeys = object.uniqueServeKeys ?? "0";
    message.selfServes = object.selfServes ?? "0";
    message.modelBreakdown = (globalThis.Object.entries(object.modelBreakdown ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.totalDenials = object.totalDenials ?? "0";
    return message;
  },
};

function createBaseStoredEpochServeStats_ModelBreakdownEntry(): StoredEpochServeStats_ModelBreakdownEntry {
  return { key: "", value: "0" };
}

export const StoredEpochServeStats_ModelBreakdownEntry: MessageFns<StoredEpochServeStats_ModelBreakdownEntry> = {
  encode(message: StoredEpochServeStats_ModelBreakdownEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "0") {
      writer.uint32(16).uint64(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StoredEpochServeStats_ModelBreakdownEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoredEpochServeStats_ModelBreakdownEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.value = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoredEpochServeStats_ModelBreakdownEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "0",
    };
  },

  toJSON(message: StoredEpochServeStats_ModelBreakdownEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "0") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StoredEpochServeStats_ModelBreakdownEntry>, I>>(
    base?: I,
  ): StoredEpochServeStats_ModelBreakdownEntry {
    return StoredEpochServeStats_ModelBreakdownEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StoredEpochServeStats_ModelBreakdownEntry>, I>>(
    object: I,
  ): StoredEpochServeStats_ModelBreakdownEntry {
    const message = createBaseStoredEpochServeStats_ModelBreakdownEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "0";
    return message;
  },
};

function createBaseStoredContributorEpochServes(): StoredContributorEpochServes {
  return { contributorId: "", epoch: "0", serveCount: "0", selfServeCount: "0", orgIds: [], totalTurns: "0" };
}

export const StoredContributorEpochServes: MessageFns<StoredContributorEpochServes> = {
  encode(message: StoredContributorEpochServes, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.contributorId !== "") {
      writer.uint32(10).string(message.contributorId);
    }
    if (message.epoch !== "0") {
      writer.uint32(16).uint64(message.epoch);
    }
    if (message.serveCount !== "0") {
      writer.uint32(24).uint64(message.serveCount);
    }
    if (message.selfServeCount !== "0") {
      writer.uint32(32).uint64(message.selfServeCount);
    }
    for (const v of message.orgIds) {
      writer.uint32(42).string(v!);
    }
    if (message.totalTurns !== "0") {
      writer.uint32(48).uint64(message.totalTurns);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StoredContributorEpochServes {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoredContributorEpochServes();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.contributorId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.epoch = reader.uint64().toString();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.serveCount = reader.uint64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.selfServeCount = reader.uint64().toString();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.orgIds.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.totalTurns = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoredContributorEpochServes {
    return {
      contributorId: isSet(object.contributorId)
        ? globalThis.String(object.contributorId)
        : isSet(object.contributor_id)
        ? globalThis.String(object.contributor_id)
        : "",
      epoch: isSet(object.epoch) ? globalThis.String(object.epoch) : "0",
      serveCount: isSet(object.serveCount)
        ? globalThis.String(object.serveCount)
        : isSet(object.serve_count)
        ? globalThis.String(object.serve_count)
        : "0",
      selfServeCount: isSet(object.selfServeCount)
        ? globalThis.String(object.selfServeCount)
        : isSet(object.self_serve_count)
        ? globalThis.String(object.self_serve_count)
        : "0",
      orgIds: globalThis.Array.isArray(object?.orgIds)
        ? object.orgIds.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.org_ids)
        ? object.org_ids.map((e: any) => globalThis.String(e))
        : [],
      totalTurns: isSet(object.totalTurns)
        ? globalThis.String(object.totalTurns)
        : isSet(object.total_turns)
        ? globalThis.String(object.total_turns)
        : "0",
    };
  },

  toJSON(message: StoredContributorEpochServes): unknown {
    const obj: any = {};
    if (message.contributorId !== "") {
      obj.contributorId = message.contributorId;
    }
    if (message.epoch !== "0") {
      obj.epoch = message.epoch;
    }
    if (message.serveCount !== "0") {
      obj.serveCount = message.serveCount;
    }
    if (message.selfServeCount !== "0") {
      obj.selfServeCount = message.selfServeCount;
    }
    if (message.orgIds?.length) {
      obj.orgIds = message.orgIds;
    }
    if (message.totalTurns !== "0") {
      obj.totalTurns = message.totalTurns;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StoredContributorEpochServes>, I>>(base?: I): StoredContributorEpochServes {
    return StoredContributorEpochServes.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StoredContributorEpochServes>, I>>(object: I): StoredContributorEpochServes {
    const message = createBaseStoredContributorEpochServes();
    message.contributorId = object.contributorId ?? "";
    message.epoch = object.epoch ?? "0";
    message.serveCount = object.serveCount ?? "0";
    message.selfServeCount = object.selfServeCount ?? "0";
    message.orgIds = object.orgIds?.map((e) => e) || [];
    message.totalTurns = object.totalTurns ?? "0";
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
