// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               unknown
// source: wevibe/serve/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Params } from "./params";

export const protobufPackage = "wevibe.serve.v1";

export interface ServeEntry {
  memoryContentHash: Uint8Array;
  serveKey: string;
  contributorId: string;
  nullifier: Uint8Array;
  modelId: string;
  turnCount: number;
  contributorWallet: string;
}

export interface MsgSubmitServeBatch {
  signer: string;
  orgId: string;
  epoch: string;
  serves: ServeEntry[];
}

export interface MsgSubmitServeBatchResponse {
  accepted: string;
  rejectedDuplicate: string;
  rejectedInvalid: string;
}

export interface DenialEntry {
  memoryHash: Uint8Array;
  nullifier: Uint8Array;
  denyKey: string;
  reason: string;
}

export interface MsgSubmitDenialBatch {
  signer: string;
  orgId: string;
  epoch: string;
  entries: DenialEntry[];
}

export interface MsgSubmitDenialBatchResponse {
  accepted: string;
  rejected: string;
}

export interface MsgUpdateParams {
  authority: string;
  params?: Params | undefined;
}

export interface MsgUpdateParamsResponse {
}

function createBaseServeEntry(): ServeEntry {
  return {
    memoryContentHash: new Uint8Array(0),
    serveKey: "",
    contributorId: "",
    nullifier: new Uint8Array(0),
    modelId: "",
    turnCount: 0,
    contributorWallet: "",
  };
}

export const ServeEntry: MessageFns<ServeEntry> = {
  encode(message: ServeEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.memoryContentHash.length !== 0) {
      writer.uint32(10).bytes(message.memoryContentHash);
    }
    if (message.serveKey !== "") {
      writer.uint32(18).string(message.serveKey);
    }
    if (message.contributorId !== "") {
      writer.uint32(26).string(message.contributorId);
    }
    if (message.nullifier.length !== 0) {
      writer.uint32(34).bytes(message.nullifier);
    }
    if (message.modelId !== "") {
      writer.uint32(42).string(message.modelId);
    }
    if (message.turnCount !== 0) {
      writer.uint32(48).uint32(message.turnCount);
    }
    if (message.contributorWallet !== "") {
      writer.uint32(58).string(message.contributorWallet);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServeEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServeEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.memoryContentHash = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.serveKey = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.contributorId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.nullifier = reader.bytes();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.modelId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.turnCount = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.contributorWallet = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServeEntry {
    return {
      memoryContentHash: isSet(object.memoryContentHash)
        ? bytesFromBase64(object.memoryContentHash)
        : isSet(object.memory_content_hash)
        ? bytesFromBase64(object.memory_content_hash)
        : new Uint8Array(0),
      serveKey: isSet(object.serveKey)
        ? globalThis.String(object.serveKey)
        : isSet(object.serve_key)
        ? globalThis.String(object.serve_key)
        : "",
      contributorId: isSet(object.contributorId)
        ? globalThis.String(object.contributorId)
        : isSet(object.contributor_id)
        ? globalThis.String(object.contributor_id)
        : "",
      nullifier: isSet(object.nullifier) ? bytesFromBase64(object.nullifier) : new Uint8Array(0),
      modelId: isSet(object.modelId)
        ? globalThis.String(object.modelId)
        : isSet(object.model_id)
        ? globalThis.String(object.model_id)
        : "",
      turnCount: isSet(object.turnCount)
        ? globalThis.Number(object.turnCount)
        : isSet(object.turn_count)
        ? globalThis.Number(object.turn_count)
        : 0,
      contributorWallet: isSet(object.contributorWallet)
        ? globalThis.String(object.contributorWallet)
        : isSet(object.contributor_wallet)
        ? globalThis.String(object.contributor_wallet)
        : "",
    };
  },

  toJSON(message: ServeEntry): unknown {
    const obj: any = {};
    if (message.memoryContentHash.length !== 0) {
      obj.memoryContentHash = base64FromBytes(message.memoryContentHash);
    }
    if (message.serveKey !== "") {
      obj.serveKey = message.serveKey;
    }
    if (message.contributorId !== "") {
      obj.contributorId = message.contributorId;
    }
    if (message.nullifier.length !== 0) {
      obj.nullifier = base64FromBytes(message.nullifier);
    }
    if (message.modelId !== "") {
      obj.modelId = message.modelId;
    }
    if (message.turnCount !== 0) {
      obj.turnCount = Math.round(message.turnCount);
    }
    if (message.contributorWallet !== "") {
      obj.contributorWallet = message.contributorWallet;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServeEntry>, I>>(base?: I): ServeEntry {
    return ServeEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServeEntry>, I>>(object: I): ServeEntry {
    const message = createBaseServeEntry();
    message.memoryContentHash = object.memoryContentHash ?? new Uint8Array(0);
    message.serveKey = object.serveKey ?? "";
    message.contributorId = object.contributorId ?? "";
    message.nullifier = object.nullifier ?? new Uint8Array(0);
    message.modelId = object.modelId ?? "";
    message.turnCount = object.turnCount ?? 0;
    message.contributorWallet = object.contributorWallet ?? "";
    return message;
  },
};

function createBaseMsgSubmitServeBatch(): MsgSubmitServeBatch {
  return { signer: "", orgId: "", epoch: "0", serves: [] };
}

export const MsgSubmitServeBatch: MessageFns<MsgSubmitServeBatch> = {
  encode(message: MsgSubmitServeBatch, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.signer !== "") {
      writer.uint32(10).string(message.signer);
    }
    if (message.orgId !== "") {
      writer.uint32(18).string(message.orgId);
    }
    if (message.epoch !== "0") {
      writer.uint32(24).uint64(message.epoch);
    }
    for (const v of message.serves) {
      ServeEntry.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSubmitServeBatch {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSubmitServeBatch();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signer = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.orgId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.epoch = reader.uint64().toString();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.serves.push(ServeEntry.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgSubmitServeBatch {
    return {
      signer: isSet(object.signer) ? globalThis.String(object.signer) : "",
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
        ? globalThis.String(object.org_id)
        : "",
      epoch: isSet(object.epoch) ? globalThis.String(object.epoch) : "0",
      serves: globalThis.Array.isArray(object?.serves) ? object.serves.map((e: any) => ServeEntry.fromJSON(e)) : [],
    };
  },

  toJSON(message: MsgSubmitServeBatch): unknown {
    const obj: any = {};
    if (message.signer !== "") {
      obj.signer = message.signer;
    }
    if (message.orgId !== "") {
      obj.orgId = message.orgId;
    }
    if (message.epoch !== "0") {
      obj.epoch = message.epoch;
    }
    if (message.serves?.length) {
      obj.serves = message.serves.map((e) => ServeEntry.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSubmitServeBatch>, I>>(base?: I): MsgSubmitServeBatch {
    return MsgSubmitServeBatch.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSubmitServeBatch>, I>>(object: I): MsgSubmitServeBatch {
    const message = createBaseMsgSubmitServeBatch();
    message.signer = object.signer ?? "";
    message.orgId = object.orgId ?? "";
    message.epoch = object.epoch ?? "0";
    message.serves = object.serves?.map((e) => ServeEntry.fromPartial(e)) || [];
    return message;
  },
};

function createBaseMsgSubmitServeBatchResponse(): MsgSubmitServeBatchResponse {
  return { accepted: "0", rejectedDuplicate: "0", rejectedInvalid: "0" };
}

export const MsgSubmitServeBatchResponse: MessageFns<MsgSubmitServeBatchResponse> = {
  encode(message: MsgSubmitServeBatchResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.accepted !== "0") {
      writer.uint32(8).uint64(message.accepted);
    }
    if (message.rejectedDuplicate !== "0") {
      writer.uint32(16).uint64(message.rejectedDuplicate);
    }
    if (message.rejectedInvalid !== "0") {
      writer.uint32(24).uint64(message.rejectedInvalid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSubmitServeBatchResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSubmitServeBatchResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.accepted = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.rejectedDuplicate = reader.uint64().toString();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.rejectedInvalid = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgSubmitServeBatchResponse {
    return {
      accepted: isSet(object.accepted) ? globalThis.String(object.accepted) : "0",
      rejectedDuplicate: isSet(object.rejectedDuplicate)
        ? globalThis.String(object.rejectedDuplicate)
        : isSet(object.rejected_duplicate)
        ? globalThis.String(object.rejected_duplicate)
        : "0",
      rejectedInvalid: isSet(object.rejectedInvalid)
        ? globalThis.String(object.rejectedInvalid)
        : isSet(object.rejected_invalid)
        ? globalThis.String(object.rejected_invalid)
        : "0",
    };
  },

  toJSON(message: MsgSubmitServeBatchResponse): unknown {
    const obj: any = {};
    if (message.accepted !== "0") {
      obj.accepted = message.accepted;
    }
    if (message.rejectedDuplicate !== "0") {
      obj.rejectedDuplicate = message.rejectedDuplicate;
    }
    if (message.rejectedInvalid !== "0") {
      obj.rejectedInvalid = message.rejectedInvalid;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSubmitServeBatchResponse>, I>>(base?: I): MsgSubmitServeBatchResponse {
    return MsgSubmitServeBatchResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSubmitServeBatchResponse>, I>>(object: I): MsgSubmitServeBatchResponse {
    const message = createBaseMsgSubmitServeBatchResponse();
    message.accepted = object.accepted ?? "0";
    message.rejectedDuplicate = object.rejectedDuplicate ?? "0";
    message.rejectedInvalid = object.rejectedInvalid ?? "0";
    return message;
  },
};

function createBaseDenialEntry(): DenialEntry {
  return { memoryHash: new Uint8Array(0), nullifier: new Uint8Array(0), denyKey: "", reason: "" };
}

export const DenialEntry: MessageFns<DenialEntry> = {
  encode(message: DenialEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.memoryHash.length !== 0) {
      writer.uint32(10).bytes(message.memoryHash);
    }
    if (message.nullifier.length !== 0) {
      writer.uint32(18).bytes(message.nullifier);
    }
    if (message.denyKey !== "") {
      writer.uint32(26).string(message.denyKey);
    }
    if (message.reason !== "") {
      writer.uint32(34).string(message.reason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DenialEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDenialEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.memoryHash = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nullifier = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.denyKey = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.reason = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DenialEntry {
    return {
      memoryHash: isSet(object.memoryHash)
        ? bytesFromBase64(object.memoryHash)
        : isSet(object.memory_hash)
        ? bytesFromBase64(object.memory_hash)
        : new Uint8Array(0),
      nullifier: isSet(object.nullifier) ? bytesFromBase64(object.nullifier) : new Uint8Array(0),
      denyKey: isSet(object.denyKey)
        ? globalThis.String(object.denyKey)
        : isSet(object.deny_key)
        ? globalThis.String(object.deny_key)
        : "",
      reason: isSet(object.reason) ? globalThis.String(object.reason) : "",
    };
  },

  toJSON(message: DenialEntry): unknown {
    const obj: any = {};
    if (message.memoryHash.length !== 0) {
      obj.memoryHash = base64FromBytes(message.memoryHash);
    }
    if (message.nullifier.length !== 0) {
      obj.nullifier = base64FromBytes(message.nullifier);
    }
    if (message.denyKey !== "") {
      obj.denyKey = message.denyKey;
    }
    if (message.reason !== "") {
      obj.reason = message.reason;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DenialEntry>, I>>(base?: I): DenialEntry {
    return DenialEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DenialEntry>, I>>(object: I): DenialEntry {
    const message = createBaseDenialEntry();
    message.memoryHash = object.memoryHash ?? new Uint8Array(0);
    message.nullifier = object.nullifier ?? new Uint8Array(0);
    message.denyKey = object.denyKey ?? "";
    message.reason = object.reason ?? "";
    return message;
  },
};

function createBaseMsgSubmitDenialBatch(): MsgSubmitDenialBatch {
  return { signer: "", orgId: "", epoch: "0", entries: [] };
}

export const MsgSubmitDenialBatch: MessageFns<MsgSubmitDenialBatch> = {
  encode(message: MsgSubmitDenialBatch, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.signer !== "") {
      writer.uint32(10).string(message.signer);
    }
    if (message.orgId !== "") {
      writer.uint32(18).string(message.orgId);
    }
    if (message.epoch !== "0") {
      writer.uint32(24).uint64(message.epoch);
    }
    for (const v of message.entries) {
      DenialEntry.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSubmitDenialBatch {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSubmitDenialBatch();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signer = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.orgId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.epoch = reader.uint64().toString();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.entries.push(DenialEntry.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgSubmitDenialBatch {
    return {
      signer: isSet(object.signer) ? globalThis.String(object.signer) : "",
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
        ? globalThis.String(object.org_id)
        : "",
      epoch: isSet(object.epoch) ? globalThis.String(object.epoch) : "0",
      entries: globalThis.Array.isArray(object?.entries) ? object.entries.map((e: any) => DenialEntry.fromJSON(e)) : [],
    };
  },

  toJSON(message: MsgSubmitDenialBatch): unknown {
    const obj: any = {};
    if (message.signer !== "") {
      obj.signer = message.signer;
    }
    if (message.orgId !== "") {
      obj.orgId = message.orgId;
    }
    if (message.epoch !== "0") {
      obj.epoch = message.epoch;
    }
    if (message.entries?.length) {
      obj.entries = message.entries.map((e) => DenialEntry.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSubmitDenialBatch>, I>>(base?: I): MsgSubmitDenialBatch {
    return MsgSubmitDenialBatch.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSubmitDenialBatch>, I>>(object: I): MsgSubmitDenialBatch {
    const message = createBaseMsgSubmitDenialBatch();
    message.signer = object.signer ?? "";
    message.orgId = object.orgId ?? "";
    message.epoch = object.epoch ?? "0";
    message.entries = object.entries?.map((e) => DenialEntry.fromPartial(e)) || [];
    return message;
  },
};

function createBaseMsgSubmitDenialBatchResponse(): MsgSubmitDenialBatchResponse {
  return { accepted: "0", rejected: "0" };
}

export const MsgSubmitDenialBatchResponse: MessageFns<MsgSubmitDenialBatchResponse> = {
  encode(message: MsgSubmitDenialBatchResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.accepted !== "0") {
      writer.uint32(8).uint64(message.accepted);
    }
    if (message.rejected !== "0") {
      writer.uint32(16).uint64(message.rejected);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSubmitDenialBatchResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSubmitDenialBatchResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.accepted = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.rejected = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgSubmitDenialBatchResponse {
    return {
      accepted: isSet(object.accepted) ? globalThis.String(object.accepted) : "0",
      rejected: isSet(object.rejected) ? globalThis.String(object.rejected) : "0",
    };
  },

  toJSON(message: MsgSubmitDenialBatchResponse): unknown {
    const obj: any = {};
    if (message.accepted !== "0") {
      obj.accepted = message.accepted;
    }
    if (message.rejected !== "0") {
      obj.rejected = message.rejected;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSubmitDenialBatchResponse>, I>>(base?: I): MsgSubmitDenialBatchResponse {
    return MsgSubmitDenialBatchResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSubmitDenialBatchResponse>, I>>(object: I): MsgSubmitDenialBatchResponse {
    const message = createBaseMsgSubmitDenialBatchResponse();
    message.accepted = object.accepted ?? "0";
    message.rejected = object.rejected ?? "0";
    return message;
  },
};

function createBaseMsgUpdateParams(): MsgUpdateParams {
  return { authority: "", params: undefined };
}

export const MsgUpdateParams: MessageFns<MsgUpdateParams> = {
  encode(message: MsgUpdateParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.authority = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateParams {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
    };
  },

  toJSON(message: MsgUpdateParams): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(base?: I): MsgUpdateParams {
    return MsgUpdateParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(object: I): MsgUpdateParams {
    const message = createBaseMsgUpdateParams();
    message.authority = object.authority ?? "";
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseMsgUpdateParamsResponse(): MsgUpdateParamsResponse {
  return {};
}

export const MsgUpdateParamsResponse: MessageFns<MsgUpdateParamsResponse> = {
  encode(_: MsgUpdateParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgUpdateParamsResponse {
    return {};
  },

  toJSON(_: MsgUpdateParamsResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(base?: I): MsgUpdateParamsResponse {
    return MsgUpdateParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(_: I): MsgUpdateParamsResponse {
    const message = createBaseMsgUpdateParamsResponse();
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
