// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               unknown
// source: wevibe/memory/v1/params.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "wevibe.memory.v1";

export interface Params {
  maxPendingPerOrg: string;
  pendingRetentionEpochs: string;
  maxBlobSizeBytes: string;
  maxKeywordsPerMemory: number;
  contestWindowEpochs: string;
}

function createBaseParams(): Params {
  return {
    maxPendingPerOrg: "0",
    pendingRetentionEpochs: "0",
    maxBlobSizeBytes: "0",
    maxKeywordsPerMemory: 0,
    contestWindowEpochs: "0",
  };
}

export const Params: MessageFns<Params> = {
  encode(message: Params, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.maxPendingPerOrg !== "0") {
      writer.uint32(8).uint64(message.maxPendingPerOrg);
    }
    if (message.pendingRetentionEpochs !== "0") {
      writer.uint32(16).uint64(message.pendingRetentionEpochs);
    }
    if (message.maxBlobSizeBytes !== "0") {
      writer.uint32(24).uint64(message.maxBlobSizeBytes);
    }
    if (message.maxKeywordsPerMemory !== 0) {
      writer.uint32(32).uint32(message.maxKeywordsPerMemory);
    }
    if (message.contestWindowEpochs !== "0") {
      writer.uint32(80).uint64(message.contestWindowEpochs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Params {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.maxPendingPerOrg = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.pendingRetentionEpochs = reader.uint64().toString();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.maxBlobSizeBytes = reader.uint64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.maxKeywordsPerMemory = reader.uint32();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.contestWindowEpochs = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Params {
    return {
      maxPendingPerOrg: isSet(object.maxPendingPerOrg)
        ? globalThis.String(object.maxPendingPerOrg)
        : isSet(object.max_pending_per_org)
        ? globalThis.String(object.max_pending_per_org)
        : "0",
      pendingRetentionEpochs: isSet(object.pendingRetentionEpochs)
        ? globalThis.String(object.pendingRetentionEpochs)
        : isSet(object.pending_retention_epochs)
        ? globalThis.String(object.pending_retention_epochs)
        : "0",
      maxBlobSizeBytes: isSet(object.maxBlobSizeBytes)
        ? globalThis.String(object.maxBlobSizeBytes)
        : isSet(object.max_blob_size_bytes)
        ? globalThis.String(object.max_blob_size_bytes)
        : "0",
      maxKeywordsPerMemory: isSet(object.maxKeywordsPerMemory)
        ? globalThis.Number(object.maxKeywordsPerMemory)
        : isSet(object.max_keywords_per_memory)
        ? globalThis.Number(object.max_keywords_per_memory)
        : 0,
      contestWindowEpochs: isSet(object.contestWindowEpochs)
        ? globalThis.String(object.contestWindowEpochs)
        : isSet(object.contest_window_epochs)
        ? globalThis.String(object.contest_window_epochs)
        : "0",
    };
  },

  toJSON(message: Params): unknown {
    const obj: any = {};
    if (message.maxPendingPerOrg !== "0") {
      obj.maxPendingPerOrg = message.maxPendingPerOrg;
    }
    if (message.pendingRetentionEpochs !== "0") {
      obj.pendingRetentionEpochs = message.pendingRetentionEpochs;
    }
    if (message.maxBlobSizeBytes !== "0") {
      obj.maxBlobSizeBytes = message.maxBlobSizeBytes;
    }
    if (message.maxKeywordsPerMemory !== 0) {
      obj.maxKeywordsPerMemory = Math.round(message.maxKeywordsPerMemory);
    }
    if (message.contestWindowEpochs !== "0") {
      obj.contestWindowEpochs = message.contestWindowEpochs;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Params>, I>>(base?: I): Params {
    return Params.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Params>, I>>(object: I): Params {
    const message = createBaseParams();
    message.maxPendingPerOrg = object.maxPendingPerOrg ?? "0";
    message.pendingRetentionEpochs = object.pendingRetentionEpochs ?? "0";
    message.maxBlobSizeBytes = object.maxBlobSizeBytes ?? "0";
    message.maxKeywordsPerMemory = object.maxKeywordsPerMemory ?? 0;
    message.contestWindowEpochs = object.contestWindowEpochs ?? "0";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
