// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: wevibe/memory/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Params } from "./params";
import { KeywordWeight, MemoryType, memoryTypeFromJSON, memoryTypeToJSON } from "./state";

export const protobufPackage = "wevibe.memory.v1";

export interface MsgSubmitCommitment {
  signer: string;
  orgId: string;
  contentHash: Uint8Array;
  keywords: KeywordWeight[];
  contributorId: string;
  contributorWallet: string;
  memoryType: MemoryType;
}

export interface MsgSubmitCommitmentResponse {
}

export interface MsgApproveMemory {
  signer: string;
  orgId: string;
  contentHash: Uint8Array;
  encryptedBlob: Uint8Array;
  committingLeader: string;
  wrappedDekEnc: Uint8Array;
  memoryType: MemoryType;
  plaintextHash: Uint8Array;
  salt: Uint8Array;
  ciphertextHash: Uint8Array;
  contributorSig: Uint8Array;
}

export interface MsgApproveMemoryResponse {
}

export interface MsgUpdateParams {
  authority: string;
  params?: Params | undefined;
}

export interface MsgUpdateParamsResponse {
}

export interface MsgReportMemory {
  signer: string;
  orgId: string;
  contentHash: Uint8Array;
  contributorPubkey: string;
  approvingModerators: string[];
  upholdingModerators: string[];
  reporterPubkey: string;
  reason: string;
  plaintext: Uint8Array;
  ciphertext: Uint8Array;
  capsule: Uint8Array;
  plaintextHash: Uint8Array;
  plaintextOversized: boolean;
}

export interface MsgReportMemoryResponse {
}

function createBaseMsgSubmitCommitment(): MsgSubmitCommitment {
  return {
    signer: "",
    orgId: "",
    contentHash: new Uint8Array(0),
    keywords: [],
    contributorId: "",
    contributorWallet: "",
    memoryType: 0,
  };
}

export const MsgSubmitCommitment: MessageFns<MsgSubmitCommitment> = {
  encode(message: MsgSubmitCommitment, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.signer !== "") {
      writer.uint32(10).string(message.signer);
    }
    if (message.orgId !== "") {
      writer.uint32(18).string(message.orgId);
    }
    if (message.contentHash.length !== 0) {
      writer.uint32(26).bytes(message.contentHash);
    }
    for (const v of message.keywords) {
      KeywordWeight.encode(v!, writer.uint32(34).fork()).join();
    }
    if (message.contributorId !== "") {
      writer.uint32(42).string(message.contributorId);
    }
    if (message.contributorWallet !== "") {
      writer.uint32(50).string(message.contributorWallet);
    }
    if (message.memoryType !== 0) {
      writer.uint32(56).int32(message.memoryType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSubmitCommitment {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSubmitCommitment();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signer = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.orgId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.contentHash = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.keywords.push(KeywordWeight.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.contributorId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.contributorWallet = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.memoryType = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgSubmitCommitment {
    return {
      signer: isSet(object.signer) ? globalThis.String(object.signer) : "",
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
        ? globalThis.String(object.org_id)
        : "",
      contentHash: isSet(object.contentHash)
        ? bytesFromBase64(object.contentHash)
        : isSet(object.content_hash)
        ? bytesFromBase64(object.content_hash)
        : new Uint8Array(0),
      keywords: globalThis.Array.isArray(object?.keywords)
        ? object.keywords.map((e: any) => KeywordWeight.fromJSON(e))
        : [],
      contributorId: isSet(object.contributorId)
        ? globalThis.String(object.contributorId)
        : isSet(object.contributor_id)
        ? globalThis.String(object.contributor_id)
        : "",
      contributorWallet: isSet(object.contributorWallet)
        ? globalThis.String(object.contributorWallet)
        : isSet(object.contributor_wallet)
        ? globalThis.String(object.contributor_wallet)
        : "",
      memoryType: isSet(object.memoryType)
        ? memoryTypeFromJSON(object.memoryType)
        : isSet(object.memory_type)
        ? memoryTypeFromJSON(object.memory_type)
        : 0,
    };
  },

  toJSON(message: MsgSubmitCommitment): unknown {
    const obj: any = {};
    if (message.signer !== "") {
      obj.signer = message.signer;
    }
    if (message.orgId !== "") {
      obj.orgId = message.orgId;
    }
    if (message.contentHash.length !== 0) {
      obj.contentHash = base64FromBytes(message.contentHash);
    }
    if (message.keywords?.length) {
      obj.keywords = message.keywords.map((e) => KeywordWeight.toJSON(e));
    }
    if (message.contributorId !== "") {
      obj.contributorId = message.contributorId;
    }
    if (message.contributorWallet !== "") {
      obj.contributorWallet = message.contributorWallet;
    }
    if (message.memoryType !== 0) {
      obj.memoryType = memoryTypeToJSON(message.memoryType);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSubmitCommitment>, I>>(base?: I): MsgSubmitCommitment {
    return MsgSubmitCommitment.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSubmitCommitment>, I>>(object: I): MsgSubmitCommitment {
    const message = createBaseMsgSubmitCommitment();
    message.signer = object.signer ?? "";
    message.orgId = object.orgId ?? "";
    message.contentHash = object.contentHash ?? new Uint8Array(0);
    message.keywords = object.keywords?.map((e) => KeywordWeight.fromPartial(e)) || [];
    message.contributorId = object.contributorId ?? "";
    message.contributorWallet = object.contributorWallet ?? "";
    message.memoryType = object.memoryType ?? 0;
    return message;
  },
};

function createBaseMsgSubmitCommitmentResponse(): MsgSubmitCommitmentResponse {
  return {};
}

export const MsgSubmitCommitmentResponse: MessageFns<MsgSubmitCommitmentResponse> = {
  encode(_: MsgSubmitCommitmentResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSubmitCommitmentResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSubmitCommitmentResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgSubmitCommitmentResponse {
    return {};
  },

  toJSON(_: MsgSubmitCommitmentResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSubmitCommitmentResponse>, I>>(base?: I): MsgSubmitCommitmentResponse {
    return MsgSubmitCommitmentResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSubmitCommitmentResponse>, I>>(_: I): MsgSubmitCommitmentResponse {
    const message = createBaseMsgSubmitCommitmentResponse();
    return message;
  },
};

function createBaseMsgApproveMemory(): MsgApproveMemory {
  return {
    signer: "",
    orgId: "",
    contentHash: new Uint8Array(0),
    encryptedBlob: new Uint8Array(0),
    committingLeader: "",
    wrappedDekEnc: new Uint8Array(0),
    memoryType: 0,
    plaintextHash: new Uint8Array(0),
    salt: new Uint8Array(0),
    ciphertextHash: new Uint8Array(0),
    contributorSig: new Uint8Array(0),
  };
}

export const MsgApproveMemory: MessageFns<MsgApproveMemory> = {
  encode(message: MsgApproveMemory, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.signer !== "") {
      writer.uint32(10).string(message.signer);
    }
    if (message.orgId !== "") {
      writer.uint32(18).string(message.orgId);
    }
    if (message.contentHash.length !== 0) {
      writer.uint32(26).bytes(message.contentHash);
    }
    if (message.encryptedBlob.length !== 0) {
      writer.uint32(34).bytes(message.encryptedBlob);
    }
    if (message.committingLeader !== "") {
      writer.uint32(50).string(message.committingLeader);
    }
    if (message.wrappedDekEnc.length !== 0) {
      writer.uint32(58).bytes(message.wrappedDekEnc);
    }
    if (message.memoryType !== 0) {
      writer.uint32(64).int32(message.memoryType);
    }
    if (message.plaintextHash.length !== 0) {
      writer.uint32(74).bytes(message.plaintextHash);
    }
    if (message.salt.length !== 0) {
      writer.uint32(82).bytes(message.salt);
    }
    if (message.ciphertextHash.length !== 0) {
      writer.uint32(90).bytes(message.ciphertextHash);
    }
    if (message.contributorSig.length !== 0) {
      writer.uint32(98).bytes(message.contributorSig);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgApproveMemory {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgApproveMemory();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signer = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.orgId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.contentHash = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.encryptedBlob = reader.bytes();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.committingLeader = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.wrappedDekEnc = reader.bytes();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.memoryType = reader.int32() as any;
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.plaintextHash = reader.bytes();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.salt = reader.bytes();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.ciphertextHash = reader.bytes();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.contributorSig = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgApproveMemory {
    return {
      signer: isSet(object.signer) ? globalThis.String(object.signer) : "",
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
        ? globalThis.String(object.org_id)
        : "",
      contentHash: isSet(object.contentHash)
        ? bytesFromBase64(object.contentHash)
        : isSet(object.content_hash)
        ? bytesFromBase64(object.content_hash)
        : new Uint8Array(0),
      encryptedBlob: isSet(object.encryptedBlob)
        ? bytesFromBase64(object.encryptedBlob)
        : isSet(object.encrypted_blob)
        ? bytesFromBase64(object.encrypted_blob)
        : new Uint8Array(0),
      committingLeader: isSet(object.committingLeader)
        ? globalThis.String(object.committingLeader)
        : isSet(object.committing_leader)
        ? globalThis.String(object.committing_leader)
        : "",
      wrappedDekEnc: isSet(object.wrappedDekEnc)
        ? bytesFromBase64(object.wrappedDekEnc)
        : isSet(object.wrapped_dek_enc)
        ? bytesFromBase64(object.wrapped_dek_enc)
        : new Uint8Array(0),
      memoryType: isSet(object.memoryType)
        ? memoryTypeFromJSON(object.memoryType)
        : isSet(object.memory_type)
        ? memoryTypeFromJSON(object.memory_type)
        : 0,
      plaintextHash: isSet(object.plaintextHash)
        ? bytesFromBase64(object.plaintextHash)
        : isSet(object.plaintext_hash)
        ? bytesFromBase64(object.plaintext_hash)
        : new Uint8Array(0),
      salt: isSet(object.salt) ? bytesFromBase64(object.salt) : new Uint8Array(0),
      ciphertextHash: isSet(object.ciphertextHash)
        ? bytesFromBase64(object.ciphertextHash)
        : isSet(object.ciphertext_hash)
        ? bytesFromBase64(object.ciphertext_hash)
        : new Uint8Array(0),
      contributorSig: isSet(object.contributorSig)
        ? bytesFromBase64(object.contributorSig)
        : isSet(object.contributor_sig)
        ? bytesFromBase64(object.contributor_sig)
        : new Uint8Array(0),
    };
  },

  toJSON(message: MsgApproveMemory): unknown {
    const obj: any = {};
    if (message.signer !== "") {
      obj.signer = message.signer;
    }
    if (message.orgId !== "") {
      obj.orgId = message.orgId;
    }
    if (message.contentHash.length !== 0) {
      obj.contentHash = base64FromBytes(message.contentHash);
    }
    if (message.encryptedBlob.length !== 0) {
      obj.encryptedBlob = base64FromBytes(message.encryptedBlob);
    }
    if (message.committingLeader !== "") {
      obj.committingLeader = message.committingLeader;
    }
    if (message.wrappedDekEnc.length !== 0) {
      obj.wrappedDekEnc = base64FromBytes(message.wrappedDekEnc);
    }
    if (message.memoryType !== 0) {
      obj.memoryType = memoryTypeToJSON(message.memoryType);
    }
    if (message.plaintextHash.length !== 0) {
      obj.plaintextHash = base64FromBytes(message.plaintextHash);
    }
    if (message.salt.length !== 0) {
      obj.salt = base64FromBytes(message.salt);
    }
    if (message.ciphertextHash.length !== 0) {
      obj.ciphertextHash = base64FromBytes(message.ciphertextHash);
    }
    if (message.contributorSig.length !== 0) {
      obj.contributorSig = base64FromBytes(message.contributorSig);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgApproveMemory>, I>>(base?: I): MsgApproveMemory {
    return MsgApproveMemory.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgApproveMemory>, I>>(object: I): MsgApproveMemory {
    const message = createBaseMsgApproveMemory();
    message.signer = object.signer ?? "";
    message.orgId = object.orgId ?? "";
    message.contentHash = object.contentHash ?? new Uint8Array(0);
    message.encryptedBlob = object.encryptedBlob ?? new Uint8Array(0);
    message.committingLeader = object.committingLeader ?? "";
    message.wrappedDekEnc = object.wrappedDekEnc ?? new Uint8Array(0);
    message.memoryType = object.memoryType ?? 0;
    message.plaintextHash = object.plaintextHash ?? new Uint8Array(0);
    message.salt = object.salt ?? new Uint8Array(0);
    message.ciphertextHash = object.ciphertextHash ?? new Uint8Array(0);
    message.contributorSig = object.contributorSig ?? new Uint8Array(0);
    return message;
  },
};

function createBaseMsgApproveMemoryResponse(): MsgApproveMemoryResponse {
  return {};
}

export const MsgApproveMemoryResponse: MessageFns<MsgApproveMemoryResponse> = {
  encode(_: MsgApproveMemoryResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgApproveMemoryResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgApproveMemoryResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgApproveMemoryResponse {
    return {};
  },

  toJSON(_: MsgApproveMemoryResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgApproveMemoryResponse>, I>>(base?: I): MsgApproveMemoryResponse {
    return MsgApproveMemoryResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgApproveMemoryResponse>, I>>(_: I): MsgApproveMemoryResponse {
    const message = createBaseMsgApproveMemoryResponse();
    return message;
  },
};

function createBaseMsgUpdateParams(): MsgUpdateParams {
  return { authority: "", params: undefined };
}

export const MsgUpdateParams: MessageFns<MsgUpdateParams> = {
  encode(message: MsgUpdateParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.authority = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateParams {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
    };
  },

  toJSON(message: MsgUpdateParams): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(base?: I): MsgUpdateParams {
    return MsgUpdateParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(object: I): MsgUpdateParams {
    const message = createBaseMsgUpdateParams();
    message.authority = object.authority ?? "";
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseMsgUpdateParamsResponse(): MsgUpdateParamsResponse {
  return {};
}

export const MsgUpdateParamsResponse: MessageFns<MsgUpdateParamsResponse> = {
  encode(_: MsgUpdateParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgUpdateParamsResponse {
    return {};
  },

  toJSON(_: MsgUpdateParamsResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(base?: I): MsgUpdateParamsResponse {
    return MsgUpdateParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(_: I): MsgUpdateParamsResponse {
    const message = createBaseMsgUpdateParamsResponse();
    return message;
  },
};

function createBaseMsgReportMemory(): MsgReportMemory {
  return {
    signer: "",
    orgId: "",
    contentHash: new Uint8Array(0),
    contributorPubkey: "",
    approvingModerators: [],
    upholdingModerators: [],
    reporterPubkey: "",
    reason: "",
    plaintext: new Uint8Array(0),
    ciphertext: new Uint8Array(0),
    capsule: new Uint8Array(0),
    plaintextHash: new Uint8Array(0),
    plaintextOversized: false,
  };
}

export const MsgReportMemory: MessageFns<MsgReportMemory> = {
  encode(message: MsgReportMemory, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.signer !== "") {
      writer.uint32(10).string(message.signer);
    }
    if (message.orgId !== "") {
      writer.uint32(18).string(message.orgId);
    }
    if (message.contentHash.length !== 0) {
      writer.uint32(26).bytes(message.contentHash);
    }
    if (message.contributorPubkey !== "") {
      writer.uint32(34).string(message.contributorPubkey);
    }
    for (const v of message.approvingModerators) {
      writer.uint32(42).string(v!);
    }
    for (const v of message.upholdingModerators) {
      writer.uint32(50).string(v!);
    }
    if (message.reporterPubkey !== "") {
      writer.uint32(58).string(message.reporterPubkey);
    }
    if (message.reason !== "") {
      writer.uint32(66).string(message.reason);
    }
    if (message.plaintext.length !== 0) {
      writer.uint32(74).bytes(message.plaintext);
    }
    if (message.ciphertext.length !== 0) {
      writer.uint32(82).bytes(message.ciphertext);
    }
    if (message.capsule.length !== 0) {
      writer.uint32(90).bytes(message.capsule);
    }
    if (message.plaintextHash.length !== 0) {
      writer.uint32(98).bytes(message.plaintextHash);
    }
    if (message.plaintextOversized !== false) {
      writer.uint32(104).bool(message.plaintextOversized);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgReportMemory {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgReportMemory();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signer = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.orgId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.contentHash = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.contributorPubkey = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.approvingModerators.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.upholdingModerators.push(reader.string());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.reporterPubkey = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.reason = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.plaintext = reader.bytes();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.ciphertext = reader.bytes();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.capsule = reader.bytes();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.plaintextHash = reader.bytes();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.plaintextOversized = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgReportMemory {
    return {
      signer: isSet(object.signer) ? globalThis.String(object.signer) : "",
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
        ? globalThis.String(object.org_id)
        : "",
      contentHash: isSet(object.contentHash)
        ? bytesFromBase64(object.contentHash)
        : isSet(object.content_hash)
        ? bytesFromBase64(object.content_hash)
        : new Uint8Array(0),
      contributorPubkey: isSet(object.contributorPubkey)
        ? globalThis.String(object.contributorPubkey)
        : isSet(object.contributor_pubkey)
        ? globalThis.String(object.contributor_pubkey)
        : "",
      approvingModerators: globalThis.Array.isArray(object?.approvingModerators)
        ? object.approvingModerators.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.approving_moderators)
        ? object.approving_moderators.map((e: any) => globalThis.String(e))
        : [],
      upholdingModerators: globalThis.Array.isArray(object?.upholdingModerators)
        ? object.upholdingModerators.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.upholding_moderators)
        ? object.upholding_moderators.map((e: any) => globalThis.String(e))
        : [],
      reporterPubkey: isSet(object.reporterPubkey)
        ? globalThis.String(object.reporterPubkey)
        : isSet(object.reporter_pubkey)
        ? globalThis.String(object.reporter_pubkey)
        : "",
      reason: isSet(object.reason) ? globalThis.String(object.reason) : "",
      plaintext: isSet(object.plaintext) ? bytesFromBase64(object.plaintext) : new Uint8Array(0),
      ciphertext: isSet(object.ciphertext) ? bytesFromBase64(object.ciphertext) : new Uint8Array(0),
      capsule: isSet(object.capsule) ? bytesFromBase64(object.capsule) : new Uint8Array(0),
      plaintextHash: isSet(object.plaintextHash)
        ? bytesFromBase64(object.plaintextHash)
        : isSet(object.plaintext_hash)
        ? bytesFromBase64(object.plaintext_hash)
        : new Uint8Array(0),
      plaintextOversized: isSet(object.plaintextOversized)
        ? globalThis.Boolean(object.plaintextOversized)
        : isSet(object.plaintext_oversized)
        ? globalThis.Boolean(object.plaintext_oversized)
        : false,
    };
  },

  toJSON(message: MsgReportMemory): unknown {
    const obj: any = {};
    if (message.signer !== "") {
      obj.signer = message.signer;
    }
    if (message.orgId !== "") {
      obj.orgId = message.orgId;
    }
    if (message.contentHash.length !== 0) {
      obj.contentHash = base64FromBytes(message.contentHash);
    }
    if (message.contributorPubkey !== "") {
      obj.contributorPubkey = message.contributorPubkey;
    }
    if (message.approvingModerators?.length) {
      obj.approvingModerators = message.approvingModerators;
    }
    if (message.upholdingModerators?.length) {
      obj.upholdingModerators = message.upholdingModerators;
    }
    if (message.reporterPubkey !== "") {
      obj.reporterPubkey = message.reporterPubkey;
    }
    if (message.reason !== "") {
      obj.reason = message.reason;
    }
    if (message.plaintext.length !== 0) {
      obj.plaintext = base64FromBytes(message.plaintext);
    }
    if (message.ciphertext.length !== 0) {
      obj.ciphertext = base64FromBytes(message.ciphertext);
    }
    if (message.capsule.length !== 0) {
      obj.capsule = base64FromBytes(message.capsule);
    }
    if (message.plaintextHash.length !== 0) {
      obj.plaintextHash = base64FromBytes(message.plaintextHash);
    }
    if (message.plaintextOversized !== false) {
      obj.plaintextOversized = message.plaintextOversized;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgReportMemory>, I>>(base?: I): MsgReportMemory {
    return MsgReportMemory.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgReportMemory>, I>>(object: I): MsgReportMemory {
    const message = createBaseMsgReportMemory();
    message.signer = object.signer ?? "";
    message.orgId = object.orgId ?? "";
    message.contentHash = object.contentHash ?? new Uint8Array(0);
    message.contributorPubkey = object.contributorPubkey ?? "";
    message.approvingModerators = object.approvingModerators?.map((e) => e) || [];
    message.upholdingModerators = object.upholdingModerators?.map((e) => e) || [];
    message.reporterPubkey = object.reporterPubkey ?? "";
    message.reason = object.reason ?? "";
    message.plaintext = object.plaintext ?? new Uint8Array(0);
    message.ciphertext = object.ciphertext ?? new Uint8Array(0);
    message.capsule = object.capsule ?? new Uint8Array(0);
    message.plaintextHash = object.plaintextHash ?? new Uint8Array(0);
    message.plaintextOversized = object.plaintextOversized ?? false;
    return message;
  },
};

function createBaseMsgReportMemoryResponse(): MsgReportMemoryResponse {
  return {};
}

export const MsgReportMemoryResponse: MessageFns<MsgReportMemoryResponse> = {
  encode(_: MsgReportMemoryResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgReportMemoryResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgReportMemoryResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgReportMemoryResponse {
    return {};
  },

  toJSON(_: MsgReportMemoryResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgReportMemoryResponse>, I>>(base?: I): MsgReportMemoryResponse {
    return MsgReportMemoryResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgReportMemoryResponse>, I>>(_: I): MsgReportMemoryResponse {
    const message = createBaseMsgReportMemoryResponse();
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
