// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               unknown
// source: wevibe/emissions/v1/params.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "wevibe.emissions.v1";

export interface Params {
  dailyMintAmount: string;
  operatorSharePercent: string;
  validatorSharePercent: string;
  storageWeightPercent: string;
  retrievalWeightPercent: string;
  rarityMultiplierCap: string;
  bootstrapDurationEpochs: string;
}

function createBaseParams(): Params {
  return {
    dailyMintAmount: "0",
    operatorSharePercent: "0",
    validatorSharePercent: "0",
    storageWeightPercent: "0",
    retrievalWeightPercent: "0",
    rarityMultiplierCap: "",
    bootstrapDurationEpochs: "0",
  };
}

export const Params: MessageFns<Params> = {
  encode(message: Params, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.dailyMintAmount !== "0") {
      writer.uint32(8).uint64(message.dailyMintAmount);
    }
    if (message.operatorSharePercent !== "0") {
      writer.uint32(16).uint64(message.operatorSharePercent);
    }
    if (message.validatorSharePercent !== "0") {
      writer.uint32(24).uint64(message.validatorSharePercent);
    }
    if (message.storageWeightPercent !== "0") {
      writer.uint32(32).uint64(message.storageWeightPercent);
    }
    if (message.retrievalWeightPercent !== "0") {
      writer.uint32(40).uint64(message.retrievalWeightPercent);
    }
    if (message.rarityMultiplierCap !== "") {
      writer.uint32(50).string(message.rarityMultiplierCap);
    }
    if (message.bootstrapDurationEpochs !== "0") {
      writer.uint32(56).uint64(message.bootstrapDurationEpochs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Params {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.dailyMintAmount = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.operatorSharePercent = reader.uint64().toString();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.validatorSharePercent = reader.uint64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.storageWeightPercent = reader.uint64().toString();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.retrievalWeightPercent = reader.uint64().toString();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.rarityMultiplierCap = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.bootstrapDurationEpochs = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Params {
    return {
      dailyMintAmount: isSet(object.dailyMintAmount)
        ? globalThis.String(object.dailyMintAmount)
        : isSet(object.daily_mint_amount)
        ? globalThis.String(object.daily_mint_amount)
        : "0",
      operatorSharePercent: isSet(object.operatorSharePercent)
        ? globalThis.String(object.operatorSharePercent)
        : isSet(object.operator_share_percent)
        ? globalThis.String(object.operator_share_percent)
        : "0",
      validatorSharePercent: isSet(object.validatorSharePercent)
        ? globalThis.String(object.validatorSharePercent)
        : isSet(object.validator_share_percent)
        ? globalThis.String(object.validator_share_percent)
        : "0",
      storageWeightPercent: isSet(object.storageWeightPercent)
        ? globalThis.String(object.storageWeightPercent)
        : isSet(object.storage_weight_percent)
        ? globalThis.String(object.storage_weight_percent)
        : "0",
      retrievalWeightPercent: isSet(object.retrievalWeightPercent)
        ? globalThis.String(object.retrievalWeightPercent)
        : isSet(object.retrieval_weight_percent)
        ? globalThis.String(object.retrieval_weight_percent)
        : "0",
      rarityMultiplierCap: isSet(object.rarityMultiplierCap)
        ? globalThis.String(object.rarityMultiplierCap)
        : isSet(object.rarity_multiplier_cap)
        ? globalThis.String(object.rarity_multiplier_cap)
        : "",
      bootstrapDurationEpochs: isSet(object.bootstrapDurationEpochs)
        ? globalThis.String(object.bootstrapDurationEpochs)
        : isSet(object.bootstrap_duration_epochs)
        ? globalThis.String(object.bootstrap_duration_epochs)
        : "0",
    };
  },

  toJSON(message: Params): unknown {
    const obj: any = {};
    if (message.dailyMintAmount !== "0") {
      obj.dailyMintAmount = message.dailyMintAmount;
    }
    if (message.operatorSharePercent !== "0") {
      obj.operatorSharePercent = message.operatorSharePercent;
    }
    if (message.validatorSharePercent !== "0") {
      obj.validatorSharePercent = message.validatorSharePercent;
    }
    if (message.storageWeightPercent !== "0") {
      obj.storageWeightPercent = message.storageWeightPercent;
    }
    if (message.retrievalWeightPercent !== "0") {
      obj.retrievalWeightPercent = message.retrievalWeightPercent;
    }
    if (message.rarityMultiplierCap !== "") {
      obj.rarityMultiplierCap = message.rarityMultiplierCap;
    }
    if (message.bootstrapDurationEpochs !== "0") {
      obj.bootstrapDurationEpochs = message.bootstrapDurationEpochs;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Params>, I>>(base?: I): Params {
    return Params.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Params>, I>>(object: I): Params {
    const message = createBaseParams();
    message.dailyMintAmount = object.dailyMintAmount ?? "0";
    message.operatorSharePercent = object.operatorSharePercent ?? "0";
    message.validatorSharePercent = object.validatorSharePercent ?? "0";
    message.storageWeightPercent = object.storageWeightPercent ?? "0";
    message.retrievalWeightPercent = object.retrievalWeightPercent ?? "0";
    message.rarityMultiplierCap = object.rarityMultiplierCap ?? "";
    message.bootstrapDurationEpochs = object.bootstrapDurationEpochs ?? "0";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
