// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: wevibe/emissions/v1/query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Params } from "./params";

export const protobufPackage = "wevibe.emissions.v1";

export interface QueryGetEmissionPoolRequest {
}

export interface QueryGetEmissionPoolResponse {
  totalSupply: string;
  dailyMint: string;
  operatorShare: string;
  validatorShare: string;
  epoch: string;
}

export interface QueryParamsRequest {
}

export interface QueryParamsResponse {
  params?: Params | undefined;
}

export interface QueryContributorRewardRequest {
  pubkey: string;
}

export interface QueryContributorRewardResponse {
  pendingWithdrawal: string;
  allTimeEarnings: string;
}

function createBaseQueryGetEmissionPoolRequest(): QueryGetEmissionPoolRequest {
  return {};
}

export const QueryGetEmissionPoolRequest: MessageFns<QueryGetEmissionPoolRequest> = {
  encode(_: QueryGetEmissionPoolRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetEmissionPoolRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetEmissionPoolRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryGetEmissionPoolRequest {
    return {};
  },

  toJSON(_: QueryGetEmissionPoolRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetEmissionPoolRequest>, I>>(base?: I): QueryGetEmissionPoolRequest {
    return QueryGetEmissionPoolRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetEmissionPoolRequest>, I>>(_: I): QueryGetEmissionPoolRequest {
    const message = createBaseQueryGetEmissionPoolRequest();
    return message;
  },
};

function createBaseQueryGetEmissionPoolResponse(): QueryGetEmissionPoolResponse {
  return { totalSupply: "0", dailyMint: "0", operatorShare: "0", validatorShare: "0", epoch: "0" };
}

export const QueryGetEmissionPoolResponse: MessageFns<QueryGetEmissionPoolResponse> = {
  encode(message: QueryGetEmissionPoolResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.totalSupply !== "0") {
      writer.uint32(8).uint64(message.totalSupply);
    }
    if (message.dailyMint !== "0") {
      writer.uint32(16).uint64(message.dailyMint);
    }
    if (message.operatorShare !== "0") {
      writer.uint32(24).uint64(message.operatorShare);
    }
    if (message.validatorShare !== "0") {
      writer.uint32(32).uint64(message.validatorShare);
    }
    if (message.epoch !== "0") {
      writer.uint32(40).uint64(message.epoch);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryGetEmissionPoolResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryGetEmissionPoolResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.totalSupply = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.dailyMint = reader.uint64().toString();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.operatorShare = reader.uint64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.validatorShare = reader.uint64().toString();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.epoch = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryGetEmissionPoolResponse {
    return {
      totalSupply: isSet(object.totalSupply)
        ? globalThis.String(object.totalSupply)
        : isSet(object.total_supply)
        ? globalThis.String(object.total_supply)
        : "0",
      dailyMint: isSet(object.dailyMint)
        ? globalThis.String(object.dailyMint)
        : isSet(object.daily_mint)
        ? globalThis.String(object.daily_mint)
        : "0",
      operatorShare: isSet(object.operatorShare)
        ? globalThis.String(object.operatorShare)
        : isSet(object.operator_share)
        ? globalThis.String(object.operator_share)
        : "0",
      validatorShare: isSet(object.validatorShare)
        ? globalThis.String(object.validatorShare)
        : isSet(object.validator_share)
        ? globalThis.String(object.validator_share)
        : "0",
      epoch: isSet(object.epoch) ? globalThis.String(object.epoch) : "0",
    };
  },

  toJSON(message: QueryGetEmissionPoolResponse): unknown {
    const obj: any = {};
    if (message.totalSupply !== "0") {
      obj.totalSupply = message.totalSupply;
    }
    if (message.dailyMint !== "0") {
      obj.dailyMint = message.dailyMint;
    }
    if (message.operatorShare !== "0") {
      obj.operatorShare = message.operatorShare;
    }
    if (message.validatorShare !== "0") {
      obj.validatorShare = message.validatorShare;
    }
    if (message.epoch !== "0") {
      obj.epoch = message.epoch;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryGetEmissionPoolResponse>, I>>(base?: I): QueryGetEmissionPoolResponse {
    return QueryGetEmissionPoolResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryGetEmissionPoolResponse>, I>>(object: I): QueryGetEmissionPoolResponse {
    const message = createBaseQueryGetEmissionPoolResponse();
    message.totalSupply = object.totalSupply ?? "0";
    message.dailyMint = object.dailyMint ?? "0";
    message.operatorShare = object.operatorShare ?? "0";
    message.validatorShare = object.validatorShare ?? "0";
    message.epoch = object.epoch ?? "0";
    return message;
  },
};

function createBaseQueryParamsRequest(): QueryParamsRequest {
  return {};
}

export const QueryParamsRequest: MessageFns<QueryParamsRequest> = {
  encode(_: QueryParamsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): QueryParamsRequest {
    return {};
  },

  toJSON(_: QueryParamsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(base?: I): QueryParamsRequest {
    return QueryParamsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsRequest>, I>>(_: I): QueryParamsRequest {
    const message = createBaseQueryParamsRequest();
    return message;
  },
};

function createBaseQueryParamsResponse(): QueryParamsResponse {
  return { params: undefined };
}

export const QueryParamsResponse: MessageFns<QueryParamsResponse> = {
  encode(message: QueryParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryParamsResponse {
    return { params: isSet(object.params) ? Params.fromJSON(object.params) : undefined };
  },

  toJSON(message: QueryParamsResponse): unknown {
    const obj: any = {};
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(base?: I): QueryParamsResponse {
    return QueryParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryParamsResponse>, I>>(object: I): QueryParamsResponse {
    const message = createBaseQueryParamsResponse();
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseQueryContributorRewardRequest(): QueryContributorRewardRequest {
  return { pubkey: "" };
}

export const QueryContributorRewardRequest: MessageFns<QueryContributorRewardRequest> = {
  encode(message: QueryContributorRewardRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pubkey !== "") {
      writer.uint32(10).string(message.pubkey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryContributorRewardRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryContributorRewardRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pubkey = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryContributorRewardRequest {
    return { pubkey: isSet(object.pubkey) ? globalThis.String(object.pubkey) : "" };
  },

  toJSON(message: QueryContributorRewardRequest): unknown {
    const obj: any = {};
    if (message.pubkey !== "") {
      obj.pubkey = message.pubkey;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryContributorRewardRequest>, I>>(base?: I): QueryContributorRewardRequest {
    return QueryContributorRewardRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryContributorRewardRequest>, I>>(
    object: I,
  ): QueryContributorRewardRequest {
    const message = createBaseQueryContributorRewardRequest();
    message.pubkey = object.pubkey ?? "";
    return message;
  },
};

function createBaseQueryContributorRewardResponse(): QueryContributorRewardResponse {
  return { pendingWithdrawal: "0", allTimeEarnings: "0" };
}

export const QueryContributorRewardResponse: MessageFns<QueryContributorRewardResponse> = {
  encode(message: QueryContributorRewardResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pendingWithdrawal !== "0") {
      writer.uint32(8).uint64(message.pendingWithdrawal);
    }
    if (message.allTimeEarnings !== "0") {
      writer.uint32(16).uint64(message.allTimeEarnings);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QueryContributorRewardResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQueryContributorRewardResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.pendingWithdrawal = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.allTimeEarnings = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QueryContributorRewardResponse {
    return {
      pendingWithdrawal: isSet(object.pendingWithdrawal)
        ? globalThis.String(object.pendingWithdrawal)
        : isSet(object.pending_withdrawal)
        ? globalThis.String(object.pending_withdrawal)
        : "0",
      allTimeEarnings: isSet(object.allTimeEarnings)
        ? globalThis.String(object.allTimeEarnings)
        : isSet(object.all_time_earnings)
        ? globalThis.String(object.all_time_earnings)
        : "0",
    };
  },

  toJSON(message: QueryContributorRewardResponse): unknown {
    const obj: any = {};
    if (message.pendingWithdrawal !== "0") {
      obj.pendingWithdrawal = message.pendingWithdrawal;
    }
    if (message.allTimeEarnings !== "0") {
      obj.allTimeEarnings = message.allTimeEarnings;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QueryContributorRewardResponse>, I>>(base?: I): QueryContributorRewardResponse {
    return QueryContributorRewardResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QueryContributorRewardResponse>, I>>(
    object: I,
  ): QueryContributorRewardResponse {
    const message = createBaseQueryContributorRewardResponse();
    message.pendingWithdrawal = object.pendingWithdrawal ?? "0";
    message.allTimeEarnings = object.allTimeEarnings ?? "0";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
