// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               unknown
// source: wevibe/emissions/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Params } from "./params";

export const protobufPackage = "wevibe.emissions.v1";

export interface MsgMintDailyEmission {
  authority: string;
  epoch: string;
}

export interface MsgMintDailyEmissionResponse {
  totalEmitted: string;
  operatorShare: string;
  validatorShare: string;
}

export interface MsgUpdateParams {
  authority: string;
  params?: Params | undefined;
}

export interface MsgUpdateParamsResponse {
}

export interface MsgClaimContributorReward {
  /** wallet bech32 — the cosmos tx signer; must equal the migrated wallet for passkey_pubkey */
  signer: string;
  /** the ed25519 identity whose accrued reward is being claimed */
  passkeyPubkey: string;
}

export interface MsgClaimContributorRewardResponse {
  amountClaimed: string;
}

function createBaseMsgMintDailyEmission(): MsgMintDailyEmission {
  return { authority: "", epoch: "0" };
}

export const MsgMintDailyEmission: MessageFns<MsgMintDailyEmission> = {
  encode(message: MsgMintDailyEmission, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.epoch !== "0") {
      writer.uint32(16).uint64(message.epoch);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgMintDailyEmission {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgMintDailyEmission();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.authority = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.epoch = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgMintDailyEmission {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      epoch: isSet(object.epoch) ? globalThis.String(object.epoch) : "0",
    };
  },

  toJSON(message: MsgMintDailyEmission): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.epoch !== "0") {
      obj.epoch = message.epoch;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgMintDailyEmission>, I>>(base?: I): MsgMintDailyEmission {
    return MsgMintDailyEmission.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgMintDailyEmission>, I>>(object: I): MsgMintDailyEmission {
    const message = createBaseMsgMintDailyEmission();
    message.authority = object.authority ?? "";
    message.epoch = object.epoch ?? "0";
    return message;
  },
};

function createBaseMsgMintDailyEmissionResponse(): MsgMintDailyEmissionResponse {
  return { totalEmitted: "0", operatorShare: "0", validatorShare: "0" };
}

export const MsgMintDailyEmissionResponse: MessageFns<MsgMintDailyEmissionResponse> = {
  encode(message: MsgMintDailyEmissionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.totalEmitted !== "0") {
      writer.uint32(8).uint64(message.totalEmitted);
    }
    if (message.operatorShare !== "0") {
      writer.uint32(16).uint64(message.operatorShare);
    }
    if (message.validatorShare !== "0") {
      writer.uint32(24).uint64(message.validatorShare);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgMintDailyEmissionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgMintDailyEmissionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.totalEmitted = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.operatorShare = reader.uint64().toString();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.validatorShare = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgMintDailyEmissionResponse {
    return {
      totalEmitted: isSet(object.totalEmitted)
        ? globalThis.String(object.totalEmitted)
        : isSet(object.total_emitted)
        ? globalThis.String(object.total_emitted)
        : "0",
      operatorShare: isSet(object.operatorShare)
        ? globalThis.String(object.operatorShare)
        : isSet(object.operator_share)
        ? globalThis.String(object.operator_share)
        : "0",
      validatorShare: isSet(object.validatorShare)
        ? globalThis.String(object.validatorShare)
        : isSet(object.validator_share)
        ? globalThis.String(object.validator_share)
        : "0",
    };
  },

  toJSON(message: MsgMintDailyEmissionResponse): unknown {
    const obj: any = {};
    if (message.totalEmitted !== "0") {
      obj.totalEmitted = message.totalEmitted;
    }
    if (message.operatorShare !== "0") {
      obj.operatorShare = message.operatorShare;
    }
    if (message.validatorShare !== "0") {
      obj.validatorShare = message.validatorShare;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgMintDailyEmissionResponse>, I>>(base?: I): MsgMintDailyEmissionResponse {
    return MsgMintDailyEmissionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgMintDailyEmissionResponse>, I>>(object: I): MsgMintDailyEmissionResponse {
    const message = createBaseMsgMintDailyEmissionResponse();
    message.totalEmitted = object.totalEmitted ?? "0";
    message.operatorShare = object.operatorShare ?? "0";
    message.validatorShare = object.validatorShare ?? "0";
    return message;
  },
};

function createBaseMsgUpdateParams(): MsgUpdateParams {
  return { authority: "", params: undefined };
}

export const MsgUpdateParams: MessageFns<MsgUpdateParams> = {
  encode(message: MsgUpdateParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.authority = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateParams {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
    };
  },

  toJSON(message: MsgUpdateParams): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(base?: I): MsgUpdateParams {
    return MsgUpdateParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(object: I): MsgUpdateParams {
    const message = createBaseMsgUpdateParams();
    message.authority = object.authority ?? "";
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseMsgUpdateParamsResponse(): MsgUpdateParamsResponse {
  return {};
}

export const MsgUpdateParamsResponse: MessageFns<MsgUpdateParamsResponse> = {
  encode(_: MsgUpdateParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgUpdateParamsResponse {
    return {};
  },

  toJSON(_: MsgUpdateParamsResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(base?: I): MsgUpdateParamsResponse {
    return MsgUpdateParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(_: I): MsgUpdateParamsResponse {
    const message = createBaseMsgUpdateParamsResponse();
    return message;
  },
};

function createBaseMsgClaimContributorReward(): MsgClaimContributorReward {
  return { signer: "", passkeyPubkey: "" };
}

export const MsgClaimContributorReward: MessageFns<MsgClaimContributorReward> = {
  encode(message: MsgClaimContributorReward, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.signer !== "") {
      writer.uint32(10).string(message.signer);
    }
    if (message.passkeyPubkey !== "") {
      writer.uint32(18).string(message.passkeyPubkey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgClaimContributorReward {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgClaimContributorReward();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signer = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.passkeyPubkey = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgClaimContributorReward {
    return {
      signer: isSet(object.signer) ? globalThis.String(object.signer) : "",
      passkeyPubkey: isSet(object.passkeyPubkey)
        ? globalThis.String(object.passkeyPubkey)
        : isSet(object.passkey_pubkey)
        ? globalThis.String(object.passkey_pubkey)
        : "",
    };
  },

  toJSON(message: MsgClaimContributorReward): unknown {
    const obj: any = {};
    if (message.signer !== "") {
      obj.signer = message.signer;
    }
    if (message.passkeyPubkey !== "") {
      obj.passkeyPubkey = message.passkeyPubkey;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgClaimContributorReward>, I>>(base?: I): MsgClaimContributorReward {
    return MsgClaimContributorReward.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgClaimContributorReward>, I>>(object: I): MsgClaimContributorReward {
    const message = createBaseMsgClaimContributorReward();
    message.signer = object.signer ?? "";
    message.passkeyPubkey = object.passkeyPubkey ?? "";
    return message;
  },
};

function createBaseMsgClaimContributorRewardResponse(): MsgClaimContributorRewardResponse {
  return { amountClaimed: "0" };
}

export const MsgClaimContributorRewardResponse: MessageFns<MsgClaimContributorRewardResponse> = {
  encode(message: MsgClaimContributorRewardResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.amountClaimed !== "0") {
      writer.uint32(8).uint64(message.amountClaimed);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgClaimContributorRewardResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgClaimContributorRewardResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.amountClaimed = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgClaimContributorRewardResponse {
    return {
      amountClaimed: isSet(object.amountClaimed)
        ? globalThis.String(object.amountClaimed)
        : isSet(object.amount_claimed)
        ? globalThis.String(object.amount_claimed)
        : "0",
    };
  },

  toJSON(message: MsgClaimContributorRewardResponse): unknown {
    const obj: any = {};
    if (message.amountClaimed !== "0") {
      obj.amountClaimed = message.amountClaimed;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgClaimContributorRewardResponse>, I>>(
    base?: I,
  ): MsgClaimContributorRewardResponse {
    return MsgClaimContributorRewardResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgClaimContributorRewardResponse>, I>>(
    object: I,
  ): MsgClaimContributorRewardResponse {
    const message = createBaseMsgClaimContributorRewardResponse();
    message.amountClaimed = object.amountClaimed ?? "0";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
