// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               unknown
// source: wevibe/emissions/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Params } from "./params";

export const protobufPackage = "wevibe.emissions.v1";

export interface MsgMintDailyEmission {
  authority: string;
  epoch: string;
}

export interface MsgMintDailyEmissionResponse {
  totalEmitted: string;
  operatorShare: string;
  validatorShare: string;
}

export interface MsgDistributeOperatorRewards {
  signer: string;
  rewards: OperatorRewardEntry[];
  epoch: string;
}

export interface OperatorRewardEntry {
  operatorId: string;
  amount: string;
}

export interface MsgDistributeOperatorRewardsResponse {
}

export interface MsgUpdateParams {
  authority: string;
  params?: Params | undefined;
}

export interface MsgUpdateParamsResponse {
}

function createBaseMsgMintDailyEmission(): MsgMintDailyEmission {
  return { authority: "", epoch: "0" };
}

export const MsgMintDailyEmission: MessageFns<MsgMintDailyEmission> = {
  encode(message: MsgMintDailyEmission, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.epoch !== "0") {
      writer.uint32(16).uint64(message.epoch);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgMintDailyEmission {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgMintDailyEmission();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.authority = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.epoch = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgMintDailyEmission {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      epoch: isSet(object.epoch) ? globalThis.String(object.epoch) : "0",
    };
  },

  toJSON(message: MsgMintDailyEmission): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.epoch !== "0") {
      obj.epoch = message.epoch;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgMintDailyEmission>, I>>(base?: I): MsgMintDailyEmission {
    return MsgMintDailyEmission.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgMintDailyEmission>, I>>(object: I): MsgMintDailyEmission {
    const message = createBaseMsgMintDailyEmission();
    message.authority = object.authority ?? "";
    message.epoch = object.epoch ?? "0";
    return message;
  },
};

function createBaseMsgMintDailyEmissionResponse(): MsgMintDailyEmissionResponse {
  return { totalEmitted: "0", operatorShare: "0", validatorShare: "0" };
}

export const MsgMintDailyEmissionResponse: MessageFns<MsgMintDailyEmissionResponse> = {
  encode(message: MsgMintDailyEmissionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.totalEmitted !== "0") {
      writer.uint32(8).uint64(message.totalEmitted);
    }
    if (message.operatorShare !== "0") {
      writer.uint32(16).uint64(message.operatorShare);
    }
    if (message.validatorShare !== "0") {
      writer.uint32(24).uint64(message.validatorShare);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgMintDailyEmissionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgMintDailyEmissionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.totalEmitted = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.operatorShare = reader.uint64().toString();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.validatorShare = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgMintDailyEmissionResponse {
    return {
      totalEmitted: isSet(object.totalEmitted)
        ? globalThis.String(object.totalEmitted)
        : isSet(object.total_emitted)
        ? globalThis.String(object.total_emitted)
        : "0",
      operatorShare: isSet(object.operatorShare)
        ? globalThis.String(object.operatorShare)
        : isSet(object.operator_share)
        ? globalThis.String(object.operator_share)
        : "0",
      validatorShare: isSet(object.validatorShare)
        ? globalThis.String(object.validatorShare)
        : isSet(object.validator_share)
        ? globalThis.String(object.validator_share)
        : "0",
    };
  },

  toJSON(message: MsgMintDailyEmissionResponse): unknown {
    const obj: any = {};
    if (message.totalEmitted !== "0") {
      obj.totalEmitted = message.totalEmitted;
    }
    if (message.operatorShare !== "0") {
      obj.operatorShare = message.operatorShare;
    }
    if (message.validatorShare !== "0") {
      obj.validatorShare = message.validatorShare;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgMintDailyEmissionResponse>, I>>(base?: I): MsgMintDailyEmissionResponse {
    return MsgMintDailyEmissionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgMintDailyEmissionResponse>, I>>(object: I): MsgMintDailyEmissionResponse {
    const message = createBaseMsgMintDailyEmissionResponse();
    message.totalEmitted = object.totalEmitted ?? "0";
    message.operatorShare = object.operatorShare ?? "0";
    message.validatorShare = object.validatorShare ?? "0";
    return message;
  },
};

function createBaseMsgDistributeOperatorRewards(): MsgDistributeOperatorRewards {
  return { signer: "", rewards: [], epoch: "0" };
}

export const MsgDistributeOperatorRewards: MessageFns<MsgDistributeOperatorRewards> = {
  encode(message: MsgDistributeOperatorRewards, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.signer !== "") {
      writer.uint32(10).string(message.signer);
    }
    for (const v of message.rewards) {
      OperatorRewardEntry.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.epoch !== "0") {
      writer.uint32(24).uint64(message.epoch);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgDistributeOperatorRewards {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgDistributeOperatorRewards();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.signer = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.rewards.push(OperatorRewardEntry.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.epoch = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgDistributeOperatorRewards {
    return {
      signer: isSet(object.signer) ? globalThis.String(object.signer) : "",
      rewards: globalThis.Array.isArray(object?.rewards)
        ? object.rewards.map((e: any) => OperatorRewardEntry.fromJSON(e))
        : [],
      epoch: isSet(object.epoch) ? globalThis.String(object.epoch) : "0",
    };
  },

  toJSON(message: MsgDistributeOperatorRewards): unknown {
    const obj: any = {};
    if (message.signer !== "") {
      obj.signer = message.signer;
    }
    if (message.rewards?.length) {
      obj.rewards = message.rewards.map((e) => OperatorRewardEntry.toJSON(e));
    }
    if (message.epoch !== "0") {
      obj.epoch = message.epoch;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgDistributeOperatorRewards>, I>>(base?: I): MsgDistributeOperatorRewards {
    return MsgDistributeOperatorRewards.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgDistributeOperatorRewards>, I>>(object: I): MsgDistributeOperatorRewards {
    const message = createBaseMsgDistributeOperatorRewards();
    message.signer = object.signer ?? "";
    message.rewards = object.rewards?.map((e) => OperatorRewardEntry.fromPartial(e)) || [];
    message.epoch = object.epoch ?? "0";
    return message;
  },
};

function createBaseOperatorRewardEntry(): OperatorRewardEntry {
  return { operatorId: "", amount: "0" };
}

export const OperatorRewardEntry: MessageFns<OperatorRewardEntry> = {
  encode(message: OperatorRewardEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.operatorId !== "") {
      writer.uint32(10).string(message.operatorId);
    }
    if (message.amount !== "0") {
      writer.uint32(16).uint64(message.amount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OperatorRewardEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOperatorRewardEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.operatorId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.amount = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OperatorRewardEntry {
    return {
      operatorId: isSet(object.operatorId)
        ? globalThis.String(object.operatorId)
        : isSet(object.operator_id)
        ? globalThis.String(object.operator_id)
        : "",
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "0",
    };
  },

  toJSON(message: OperatorRewardEntry): unknown {
    const obj: any = {};
    if (message.operatorId !== "") {
      obj.operatorId = message.operatorId;
    }
    if (message.amount !== "0") {
      obj.amount = message.amount;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OperatorRewardEntry>, I>>(base?: I): OperatorRewardEntry {
    return OperatorRewardEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OperatorRewardEntry>, I>>(object: I): OperatorRewardEntry {
    const message = createBaseOperatorRewardEntry();
    message.operatorId = object.operatorId ?? "";
    message.amount = object.amount ?? "0";
    return message;
  },
};

function createBaseMsgDistributeOperatorRewardsResponse(): MsgDistributeOperatorRewardsResponse {
  return {};
}

export const MsgDistributeOperatorRewardsResponse: MessageFns<MsgDistributeOperatorRewardsResponse> = {
  encode(_: MsgDistributeOperatorRewardsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgDistributeOperatorRewardsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgDistributeOperatorRewardsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgDistributeOperatorRewardsResponse {
    return {};
  },

  toJSON(_: MsgDistributeOperatorRewardsResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgDistributeOperatorRewardsResponse>, I>>(
    base?: I,
  ): MsgDistributeOperatorRewardsResponse {
    return MsgDistributeOperatorRewardsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgDistributeOperatorRewardsResponse>, I>>(
    _: I,
  ): MsgDistributeOperatorRewardsResponse {
    const message = createBaseMsgDistributeOperatorRewardsResponse();
    return message;
  },
};

function createBaseMsgUpdateParams(): MsgUpdateParams {
  return { authority: "", params: undefined };
}

export const MsgUpdateParams: MessageFns<MsgUpdateParams> = {
  encode(message: MsgUpdateParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.authority = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.params = Params.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgUpdateParams {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
    };
  },

  toJSON(message: MsgUpdateParams): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(base?: I): MsgUpdateParams {
    return MsgUpdateParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(object: I): MsgUpdateParams {
    const message = createBaseMsgUpdateParams();
    message.authority = object.authority ?? "";
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseMsgUpdateParamsResponse(): MsgUpdateParamsResponse {
  return {};
}

export const MsgUpdateParamsResponse: MessageFns<MsgUpdateParamsResponse> = {
  encode(_: MsgUpdateParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgUpdateParamsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgUpdateParamsResponse {
    return {};
  },

  toJSON(_: MsgUpdateParamsResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(base?: I): MsgUpdateParamsResponse {
    return MsgUpdateParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(_: I): MsgUpdateParamsResponse {
    const message = createBaseMsgUpdateParamsResponse();
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
