// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.7
//   protoc               unknown
// source: wevibe/reputation/v1/state.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "wevibe.reputation.v1";

export interface StoredReputationStats {
  developerId: string;
  memoryCount: string;
  difficultyBucket: string[];
  domainTags: { [key: string]: string };
  provenanceBreakdown: { [key: string]: string };
  xp: string;
  serveCount: string;
  selfServeCount: string;
  orgBreadth: string;
  firstSeenEpoch: string;
  serveXp: string;
}

export interface StoredReputationStats_DomainTagsEntry {
  key: string;
  value: string;
}

export interface StoredReputationStats_ProvenanceBreakdownEntry {
  key: string;
  value: string;
}

export interface StoredAttestedMemory {
  developer: Uint8Array;
  memoryCid: string;
  difficulty: number;
  quality: number;
  domainTags: string[];
  provenance: string;
}

export interface StoredContributorOrgSet {
  contributorId: string;
  orgIds: string[];
}

export interface OrgMembership {
  orgId: string;
  role: string;
  joinedEpoch: string;
  active: boolean;
}

export interface StoredContributorProfile {
  contributorId: string;
  totalApprovedMemories: string;
  totalServesReceived: string;
  totalDenialsReceived: string;
  totalReportsFiledAgainst: string;
  totalReportsUpheldAgainst: string;
  memberships: OrgMembership[];
  firstContributionEpoch: string;
  lastContributionEpoch: string;
}

export interface StoredModeratorProfile {
  moderatorPubkey: string;
  orgId: string;
  totalApprovals: string;
  approvalsLaterUpheldCount: string;
  approvedMemoryHashes: Uint8Array[];
  firstApprovalEpoch: string;
  lastApprovalEpoch: string;
}

export interface EpochRotation {
  epoch: string;
  reason: string;
  timestamp: string;
}

export interface StoredLeaderProfile {
  leaderPubkey: string;
  orgId: string;
  totalChainCommitsSigned: string;
  totalUpheldReportsCommitted: string;
  epochRotations: EpochRotation[];
  firstLeadershipEpoch: string;
  currentLeader: boolean;
}

function createBaseStoredReputationStats(): StoredReputationStats {
  return {
    developerId: "",
    memoryCount: "0",
    difficultyBucket: [],
    domainTags: {},
    provenanceBreakdown: {},
    xp: "0",
    serveCount: "0",
    selfServeCount: "0",
    orgBreadth: "0",
    firstSeenEpoch: "0",
    serveXp: "0",
  };
}

export const StoredReputationStats: MessageFns<StoredReputationStats> = {
  encode(message: StoredReputationStats, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.developerId !== "") {
      writer.uint32(10).string(message.developerId);
    }
    if (message.memoryCount !== "0") {
      writer.uint32(16).uint64(message.memoryCount);
    }
    writer.uint32(26).fork();
    for (const v of message.difficultyBucket) {
      writer.uint64(v);
    }
    writer.join();
    globalThis.Object.entries(message.domainTags).forEach(([key, value]: [string, string]) => {
      StoredReputationStats_DomainTagsEntry.encode({ key: key as any, value }, writer.uint32(34).fork()).join();
    });
    globalThis.Object.entries(message.provenanceBreakdown).forEach(([key, value]: [string, string]) => {
      StoredReputationStats_ProvenanceBreakdownEntry.encode({ key: key as any, value }, writer.uint32(42).fork())
        .join();
    });
    if (message.xp !== "0") {
      writer.uint32(48).uint64(message.xp);
    }
    if (message.serveCount !== "0") {
      writer.uint32(56).uint64(message.serveCount);
    }
    if (message.selfServeCount !== "0") {
      writer.uint32(64).uint64(message.selfServeCount);
    }
    if (message.orgBreadth !== "0") {
      writer.uint32(72).uint64(message.orgBreadth);
    }
    if (message.firstSeenEpoch !== "0") {
      writer.uint32(80).uint64(message.firstSeenEpoch);
    }
    if (message.serveXp !== "0") {
      writer.uint32(88).uint64(message.serveXp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StoredReputationStats {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoredReputationStats();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.developerId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.memoryCount = reader.uint64().toString();
          continue;
        }
        case 3: {
          if (tag === 24) {
            message.difficultyBucket.push(reader.uint64().toString());

            continue;
          }

          if (tag === 26) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.difficultyBucket.push(reader.uint64().toString());
            }

            continue;
          }

          break;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const entry4 = StoredReputationStats_DomainTagsEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.domainTags[entry4.key] = entry4.value;
          }
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          const entry5 = StoredReputationStats_ProvenanceBreakdownEntry.decode(reader, reader.uint32());
          if (entry5.value !== undefined) {
            message.provenanceBreakdown[entry5.key] = entry5.value;
          }
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.xp = reader.uint64().toString();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.serveCount = reader.uint64().toString();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.selfServeCount = reader.uint64().toString();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.orgBreadth = reader.uint64().toString();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.firstSeenEpoch = reader.uint64().toString();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.serveXp = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoredReputationStats {
    return {
      developerId: isSet(object.developerId)
        ? globalThis.String(object.developerId)
        : isSet(object.developer_id)
        ? globalThis.String(object.developer_id)
        : "",
      memoryCount: isSet(object.memoryCount)
        ? globalThis.String(object.memoryCount)
        : isSet(object.memory_count)
        ? globalThis.String(object.memory_count)
        : "0",
      difficultyBucket: globalThis.Array.isArray(object?.difficultyBucket)
        ? object.difficultyBucket.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.difficulty_bucket)
        ? object.difficulty_bucket.map((e: any) => globalThis.String(e))
        : [],
      domainTags: isObject(object.domainTags)
        ? (globalThis.Object.entries(object.domainTags) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : isObject(object.domain_tags)
        ? (globalThis.Object.entries(object.domain_tags) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
      provenanceBreakdown: isObject(object.provenanceBreakdown)
        ? (globalThis.Object.entries(object.provenanceBreakdown) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : isObject(object.provenance_breakdown)
        ? (globalThis.Object.entries(object.provenance_breakdown) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
      xp: isSet(object.xp) ? globalThis.String(object.xp) : "0",
      serveCount: isSet(object.serveCount)
        ? globalThis.String(object.serveCount)
        : isSet(object.serve_count)
        ? globalThis.String(object.serve_count)
        : "0",
      selfServeCount: isSet(object.selfServeCount)
        ? globalThis.String(object.selfServeCount)
        : isSet(object.self_serve_count)
        ? globalThis.String(object.self_serve_count)
        : "0",
      orgBreadth: isSet(object.orgBreadth)
        ? globalThis.String(object.orgBreadth)
        : isSet(object.org_breadth)
        ? globalThis.String(object.org_breadth)
        : "0",
      firstSeenEpoch: isSet(object.firstSeenEpoch)
        ? globalThis.String(object.firstSeenEpoch)
        : isSet(object.first_seen_epoch)
        ? globalThis.String(object.first_seen_epoch)
        : "0",
      serveXp: isSet(object.serveXp)
        ? globalThis.String(object.serveXp)
        : isSet(object.serve_xp)
        ? globalThis.String(object.serve_xp)
        : "0",
    };
  },

  toJSON(message: StoredReputationStats): unknown {
    const obj: any = {};
    if (message.developerId !== "") {
      obj.developerId = message.developerId;
    }
    if (message.memoryCount !== "0") {
      obj.memoryCount = message.memoryCount;
    }
    if (message.difficultyBucket?.length) {
      obj.difficultyBucket = message.difficultyBucket;
    }
    if (message.domainTags) {
      const entries = globalThis.Object.entries(message.domainTags) as [string, string][];
      if (entries.length > 0) {
        obj.domainTags = {};
        entries.forEach(([k, v]) => {
          obj.domainTags[k] = v;
        });
      }
    }
    if (message.provenanceBreakdown) {
      const entries = globalThis.Object.entries(message.provenanceBreakdown) as [string, string][];
      if (entries.length > 0) {
        obj.provenanceBreakdown = {};
        entries.forEach(([k, v]) => {
          obj.provenanceBreakdown[k] = v;
        });
      }
    }
    if (message.xp !== "0") {
      obj.xp = message.xp;
    }
    if (message.serveCount !== "0") {
      obj.serveCount = message.serveCount;
    }
    if (message.selfServeCount !== "0") {
      obj.selfServeCount = message.selfServeCount;
    }
    if (message.orgBreadth !== "0") {
      obj.orgBreadth = message.orgBreadth;
    }
    if (message.firstSeenEpoch !== "0") {
      obj.firstSeenEpoch = message.firstSeenEpoch;
    }
    if (message.serveXp !== "0") {
      obj.serveXp = message.serveXp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StoredReputationStats>, I>>(base?: I): StoredReputationStats {
    return StoredReputationStats.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StoredReputationStats>, I>>(object: I): StoredReputationStats {
    const message = createBaseStoredReputationStats();
    message.developerId = object.developerId ?? "";
    message.memoryCount = object.memoryCount ?? "0";
    message.difficultyBucket = object.difficultyBucket?.map((e) => e) || [];
    message.domainTags = (globalThis.Object.entries(object.domainTags ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.provenanceBreakdown = (globalThis.Object.entries(object.provenanceBreakdown ?? {}) as [string, string][])
      .reduce((acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      }, {});
    message.xp = object.xp ?? "0";
    message.serveCount = object.serveCount ?? "0";
    message.selfServeCount = object.selfServeCount ?? "0";
    message.orgBreadth = object.orgBreadth ?? "0";
    message.firstSeenEpoch = object.firstSeenEpoch ?? "0";
    message.serveXp = object.serveXp ?? "0";
    return message;
  },
};

function createBaseStoredReputationStats_DomainTagsEntry(): StoredReputationStats_DomainTagsEntry {
  return { key: "", value: "0" };
}

export const StoredReputationStats_DomainTagsEntry: MessageFns<StoredReputationStats_DomainTagsEntry> = {
  encode(message: StoredReputationStats_DomainTagsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "0") {
      writer.uint32(16).uint64(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StoredReputationStats_DomainTagsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoredReputationStats_DomainTagsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.value = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoredReputationStats_DomainTagsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "0",
    };
  },

  toJSON(message: StoredReputationStats_DomainTagsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "0") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StoredReputationStats_DomainTagsEntry>, I>>(
    base?: I,
  ): StoredReputationStats_DomainTagsEntry {
    return StoredReputationStats_DomainTagsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StoredReputationStats_DomainTagsEntry>, I>>(
    object: I,
  ): StoredReputationStats_DomainTagsEntry {
    const message = createBaseStoredReputationStats_DomainTagsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "0";
    return message;
  },
};

function createBaseStoredReputationStats_ProvenanceBreakdownEntry(): StoredReputationStats_ProvenanceBreakdownEntry {
  return { key: "", value: "0" };
}

export const StoredReputationStats_ProvenanceBreakdownEntry: MessageFns<
  StoredReputationStats_ProvenanceBreakdownEntry
> = {
  encode(
    message: StoredReputationStats_ProvenanceBreakdownEntry,
    writer: BinaryWriter = new BinaryWriter(),
  ): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "0") {
      writer.uint32(16).uint64(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StoredReputationStats_ProvenanceBreakdownEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoredReputationStats_ProvenanceBreakdownEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.value = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoredReputationStats_ProvenanceBreakdownEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "0",
    };
  },

  toJSON(message: StoredReputationStats_ProvenanceBreakdownEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "0") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StoredReputationStats_ProvenanceBreakdownEntry>, I>>(
    base?: I,
  ): StoredReputationStats_ProvenanceBreakdownEntry {
    return StoredReputationStats_ProvenanceBreakdownEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StoredReputationStats_ProvenanceBreakdownEntry>, I>>(
    object: I,
  ): StoredReputationStats_ProvenanceBreakdownEntry {
    const message = createBaseStoredReputationStats_ProvenanceBreakdownEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "0";
    return message;
  },
};

function createBaseStoredAttestedMemory(): StoredAttestedMemory {
  return { developer: new Uint8Array(0), memoryCid: "", difficulty: 0, quality: 0, domainTags: [], provenance: "" };
}

export const StoredAttestedMemory: MessageFns<StoredAttestedMemory> = {
  encode(message: StoredAttestedMemory, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.developer.length !== 0) {
      writer.uint32(10).bytes(message.developer);
    }
    if (message.memoryCid !== "") {
      writer.uint32(18).string(message.memoryCid);
    }
    if (message.difficulty !== 0) {
      writer.uint32(24).uint32(message.difficulty);
    }
    if (message.quality !== 0) {
      writer.uint32(32).uint32(message.quality);
    }
    for (const v of message.domainTags) {
      writer.uint32(42).string(v!);
    }
    if (message.provenance !== "") {
      writer.uint32(50).string(message.provenance);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StoredAttestedMemory {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoredAttestedMemory();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.developer = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.memoryCid = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.difficulty = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.quality = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.domainTags.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.provenance = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoredAttestedMemory {
    return {
      developer: isSet(object.developer) ? bytesFromBase64(object.developer) : new Uint8Array(0),
      memoryCid: isSet(object.memoryCid)
        ? globalThis.String(object.memoryCid)
        : isSet(object.memory_cid)
        ? globalThis.String(object.memory_cid)
        : "",
      difficulty: isSet(object.difficulty) ? globalThis.Number(object.difficulty) : 0,
      quality: isSet(object.quality) ? globalThis.Number(object.quality) : 0,
      domainTags: globalThis.Array.isArray(object?.domainTags)
        ? object.domainTags.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.domain_tags)
        ? object.domain_tags.map((e: any) => globalThis.String(e))
        : [],
      provenance: isSet(object.provenance) ? globalThis.String(object.provenance) : "",
    };
  },

  toJSON(message: StoredAttestedMemory): unknown {
    const obj: any = {};
    if (message.developer.length !== 0) {
      obj.developer = base64FromBytes(message.developer);
    }
    if (message.memoryCid !== "") {
      obj.memoryCid = message.memoryCid;
    }
    if (message.difficulty !== 0) {
      obj.difficulty = Math.round(message.difficulty);
    }
    if (message.quality !== 0) {
      obj.quality = Math.round(message.quality);
    }
    if (message.domainTags?.length) {
      obj.domainTags = message.domainTags;
    }
    if (message.provenance !== "") {
      obj.provenance = message.provenance;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StoredAttestedMemory>, I>>(base?: I): StoredAttestedMemory {
    return StoredAttestedMemory.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StoredAttestedMemory>, I>>(object: I): StoredAttestedMemory {
    const message = createBaseStoredAttestedMemory();
    message.developer = object.developer ?? new Uint8Array(0);
    message.memoryCid = object.memoryCid ?? "";
    message.difficulty = object.difficulty ?? 0;
    message.quality = object.quality ?? 0;
    message.domainTags = object.domainTags?.map((e) => e) || [];
    message.provenance = object.provenance ?? "";
    return message;
  },
};

function createBaseStoredContributorOrgSet(): StoredContributorOrgSet {
  return { contributorId: "", orgIds: [] };
}

export const StoredContributorOrgSet: MessageFns<StoredContributorOrgSet> = {
  encode(message: StoredContributorOrgSet, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.contributorId !== "") {
      writer.uint32(10).string(message.contributorId);
    }
    for (const v of message.orgIds) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StoredContributorOrgSet {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoredContributorOrgSet();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.contributorId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.orgIds.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoredContributorOrgSet {
    return {
      contributorId: isSet(object.contributorId)
        ? globalThis.String(object.contributorId)
        : isSet(object.contributor_id)
        ? globalThis.String(object.contributor_id)
        : "",
      orgIds: globalThis.Array.isArray(object?.orgIds)
        ? object.orgIds.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.org_ids)
        ? object.org_ids.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: StoredContributorOrgSet): unknown {
    const obj: any = {};
    if (message.contributorId !== "") {
      obj.contributorId = message.contributorId;
    }
    if (message.orgIds?.length) {
      obj.orgIds = message.orgIds;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StoredContributorOrgSet>, I>>(base?: I): StoredContributorOrgSet {
    return StoredContributorOrgSet.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StoredContributorOrgSet>, I>>(object: I): StoredContributorOrgSet {
    const message = createBaseStoredContributorOrgSet();
    message.contributorId = object.contributorId ?? "";
    message.orgIds = object.orgIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseOrgMembership(): OrgMembership {
  return { orgId: "", role: "", joinedEpoch: "0", active: false };
}

export const OrgMembership: MessageFns<OrgMembership> = {
  encode(message: OrgMembership, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orgId !== "") {
      writer.uint32(10).string(message.orgId);
    }
    if (message.role !== "") {
      writer.uint32(18).string(message.role);
    }
    if (message.joinedEpoch !== "0") {
      writer.uint32(24).uint64(message.joinedEpoch);
    }
    if (message.active !== false) {
      writer.uint32(32).bool(message.active);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OrgMembership {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOrgMembership();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orgId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.role = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.joinedEpoch = reader.uint64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.active = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OrgMembership {
    return {
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
        ? globalThis.String(object.org_id)
        : "",
      role: isSet(object.role) ? globalThis.String(object.role) : "",
      joinedEpoch: isSet(object.joinedEpoch)
        ? globalThis.String(object.joinedEpoch)
        : isSet(object.joined_epoch)
        ? globalThis.String(object.joined_epoch)
        : "0",
      active: isSet(object.active) ? globalThis.Boolean(object.active) : false,
    };
  },

  toJSON(message: OrgMembership): unknown {
    const obj: any = {};
    if (message.orgId !== "") {
      obj.orgId = message.orgId;
    }
    if (message.role !== "") {
      obj.role = message.role;
    }
    if (message.joinedEpoch !== "0") {
      obj.joinedEpoch = message.joinedEpoch;
    }
    if (message.active !== false) {
      obj.active = message.active;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OrgMembership>, I>>(base?: I): OrgMembership {
    return OrgMembership.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OrgMembership>, I>>(object: I): OrgMembership {
    const message = createBaseOrgMembership();
    message.orgId = object.orgId ?? "";
    message.role = object.role ?? "";
    message.joinedEpoch = object.joinedEpoch ?? "0";
    message.active = object.active ?? false;
    return message;
  },
};

function createBaseStoredContributorProfile(): StoredContributorProfile {
  return {
    contributorId: "",
    totalApprovedMemories: "0",
    totalServesReceived: "0",
    totalDenialsReceived: "0",
    totalReportsFiledAgainst: "0",
    totalReportsUpheldAgainst: "0",
    memberships: [],
    firstContributionEpoch: "0",
    lastContributionEpoch: "0",
  };
}

export const StoredContributorProfile: MessageFns<StoredContributorProfile> = {
  encode(message: StoredContributorProfile, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.contributorId !== "") {
      writer.uint32(10).string(message.contributorId);
    }
    if (message.totalApprovedMemories !== "0") {
      writer.uint32(16).uint64(message.totalApprovedMemories);
    }
    if (message.totalServesReceived !== "0") {
      writer.uint32(24).uint64(message.totalServesReceived);
    }
    if (message.totalDenialsReceived !== "0") {
      writer.uint32(32).uint64(message.totalDenialsReceived);
    }
    if (message.totalReportsFiledAgainst !== "0") {
      writer.uint32(40).uint64(message.totalReportsFiledAgainst);
    }
    if (message.totalReportsUpheldAgainst !== "0") {
      writer.uint32(48).uint64(message.totalReportsUpheldAgainst);
    }
    for (const v of message.memberships) {
      OrgMembership.encode(v!, writer.uint32(58).fork()).join();
    }
    if (message.firstContributionEpoch !== "0") {
      writer.uint32(64).uint64(message.firstContributionEpoch);
    }
    if (message.lastContributionEpoch !== "0") {
      writer.uint32(72).uint64(message.lastContributionEpoch);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StoredContributorProfile {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoredContributorProfile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.contributorId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.totalApprovedMemories = reader.uint64().toString();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.totalServesReceived = reader.uint64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.totalDenialsReceived = reader.uint64().toString();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.totalReportsFiledAgainst = reader.uint64().toString();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.totalReportsUpheldAgainst = reader.uint64().toString();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.memberships.push(OrgMembership.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.firstContributionEpoch = reader.uint64().toString();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.lastContributionEpoch = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoredContributorProfile {
    return {
      contributorId: isSet(object.contributorId)
        ? globalThis.String(object.contributorId)
        : isSet(object.contributor_id)
        ? globalThis.String(object.contributor_id)
        : "",
      totalApprovedMemories: isSet(object.totalApprovedMemories)
        ? globalThis.String(object.totalApprovedMemories)
        : isSet(object.total_approved_memories)
        ? globalThis.String(object.total_approved_memories)
        : "0",
      totalServesReceived: isSet(object.totalServesReceived)
        ? globalThis.String(object.totalServesReceived)
        : isSet(object.total_serves_received)
        ? globalThis.String(object.total_serves_received)
        : "0",
      totalDenialsReceived: isSet(object.totalDenialsReceived)
        ? globalThis.String(object.totalDenialsReceived)
        : isSet(object.total_denials_received)
        ? globalThis.String(object.total_denials_received)
        : "0",
      totalReportsFiledAgainst: isSet(object.totalReportsFiledAgainst)
        ? globalThis.String(object.totalReportsFiledAgainst)
        : isSet(object.total_reports_filed_against)
        ? globalThis.String(object.total_reports_filed_against)
        : "0",
      totalReportsUpheldAgainst: isSet(object.totalReportsUpheldAgainst)
        ? globalThis.String(object.totalReportsUpheldAgainst)
        : isSet(object.total_reports_upheld_against)
        ? globalThis.String(object.total_reports_upheld_against)
        : "0",
      memberships: globalThis.Array.isArray(object?.memberships)
        ? object.memberships.map((e: any) => OrgMembership.fromJSON(e))
        : [],
      firstContributionEpoch: isSet(object.firstContributionEpoch)
        ? globalThis.String(object.firstContributionEpoch)
        : isSet(object.first_contribution_epoch)
        ? globalThis.String(object.first_contribution_epoch)
        : "0",
      lastContributionEpoch: isSet(object.lastContributionEpoch)
        ? globalThis.String(object.lastContributionEpoch)
        : isSet(object.last_contribution_epoch)
        ? globalThis.String(object.last_contribution_epoch)
        : "0",
    };
  },

  toJSON(message: StoredContributorProfile): unknown {
    const obj: any = {};
    if (message.contributorId !== "") {
      obj.contributorId = message.contributorId;
    }
    if (message.totalApprovedMemories !== "0") {
      obj.totalApprovedMemories = message.totalApprovedMemories;
    }
    if (message.totalServesReceived !== "0") {
      obj.totalServesReceived = message.totalServesReceived;
    }
    if (message.totalDenialsReceived !== "0") {
      obj.totalDenialsReceived = message.totalDenialsReceived;
    }
    if (message.totalReportsFiledAgainst !== "0") {
      obj.totalReportsFiledAgainst = message.totalReportsFiledAgainst;
    }
    if (message.totalReportsUpheldAgainst !== "0") {
      obj.totalReportsUpheldAgainst = message.totalReportsUpheldAgainst;
    }
    if (message.memberships?.length) {
      obj.memberships = message.memberships.map((e) => OrgMembership.toJSON(e));
    }
    if (message.firstContributionEpoch !== "0") {
      obj.firstContributionEpoch = message.firstContributionEpoch;
    }
    if (message.lastContributionEpoch !== "0") {
      obj.lastContributionEpoch = message.lastContributionEpoch;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StoredContributorProfile>, I>>(base?: I): StoredContributorProfile {
    return StoredContributorProfile.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StoredContributorProfile>, I>>(object: I): StoredContributorProfile {
    const message = createBaseStoredContributorProfile();
    message.contributorId = object.contributorId ?? "";
    message.totalApprovedMemories = object.totalApprovedMemories ?? "0";
    message.totalServesReceived = object.totalServesReceived ?? "0";
    message.totalDenialsReceived = object.totalDenialsReceived ?? "0";
    message.totalReportsFiledAgainst = object.totalReportsFiledAgainst ?? "0";
    message.totalReportsUpheldAgainst = object.totalReportsUpheldAgainst ?? "0";
    message.memberships = object.memberships?.map((e) => OrgMembership.fromPartial(e)) || [];
    message.firstContributionEpoch = object.firstContributionEpoch ?? "0";
    message.lastContributionEpoch = object.lastContributionEpoch ?? "0";
    return message;
  },
};

function createBaseStoredModeratorProfile(): StoredModeratorProfile {
  return {
    moderatorPubkey: "",
    orgId: "",
    totalApprovals: "0",
    approvalsLaterUpheldCount: "0",
    approvedMemoryHashes: [],
    firstApprovalEpoch: "0",
    lastApprovalEpoch: "0",
  };
}

export const StoredModeratorProfile: MessageFns<StoredModeratorProfile> = {
  encode(message: StoredModeratorProfile, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.moderatorPubkey !== "") {
      writer.uint32(10).string(message.moderatorPubkey);
    }
    if (message.orgId !== "") {
      writer.uint32(18).string(message.orgId);
    }
    if (message.totalApprovals !== "0") {
      writer.uint32(24).uint64(message.totalApprovals);
    }
    if (message.approvalsLaterUpheldCount !== "0") {
      writer.uint32(32).uint64(message.approvalsLaterUpheldCount);
    }
    for (const v of message.approvedMemoryHashes) {
      writer.uint32(42).bytes(v!);
    }
    if (message.firstApprovalEpoch !== "0") {
      writer.uint32(48).uint64(message.firstApprovalEpoch);
    }
    if (message.lastApprovalEpoch !== "0") {
      writer.uint32(56).uint64(message.lastApprovalEpoch);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StoredModeratorProfile {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoredModeratorProfile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.moderatorPubkey = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.orgId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.totalApprovals = reader.uint64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.approvalsLaterUpheldCount = reader.uint64().toString();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.approvedMemoryHashes.push(reader.bytes());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.firstApprovalEpoch = reader.uint64().toString();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.lastApprovalEpoch = reader.uint64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoredModeratorProfile {
    return {
      moderatorPubkey: isSet(object.moderatorPubkey)
        ? globalThis.String(object.moderatorPubkey)
        : isSet(object.moderator_pubkey)
        ? globalThis.String(object.moderator_pubkey)
        : "",
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
        ? globalThis.String(object.org_id)
        : "",
      totalApprovals: isSet(object.totalApprovals)
        ? globalThis.String(object.totalApprovals)
        : isSet(object.total_approvals)
        ? globalThis.String(object.total_approvals)
        : "0",
      approvalsLaterUpheldCount: isSet(object.approvalsLaterUpheldCount)
        ? globalThis.String(object.approvalsLaterUpheldCount)
        : isSet(object.approvals_later_upheld_count)
        ? globalThis.String(object.approvals_later_upheld_count)
        : "0",
      approvedMemoryHashes: globalThis.Array.isArray(object?.approvedMemoryHashes)
        ? object.approvedMemoryHashes.map((e: any) => bytesFromBase64(e))
        : globalThis.Array.isArray(object?.approved_memory_hashes)
        ? object.approved_memory_hashes.map((e: any) => bytesFromBase64(e))
        : [],
      firstApprovalEpoch: isSet(object.firstApprovalEpoch)
        ? globalThis.String(object.firstApprovalEpoch)
        : isSet(object.first_approval_epoch)
        ? globalThis.String(object.first_approval_epoch)
        : "0",
      lastApprovalEpoch: isSet(object.lastApprovalEpoch)
        ? globalThis.String(object.lastApprovalEpoch)
        : isSet(object.last_approval_epoch)
        ? globalThis.String(object.last_approval_epoch)
        : "0",
    };
  },

  toJSON(message: StoredModeratorProfile): unknown {
    const obj: any = {};
    if (message.moderatorPubkey !== "") {
      obj.moderatorPubkey = message.moderatorPubkey;
    }
    if (message.orgId !== "") {
      obj.orgId = message.orgId;
    }
    if (message.totalApprovals !== "0") {
      obj.totalApprovals = message.totalApprovals;
    }
    if (message.approvalsLaterUpheldCount !== "0") {
      obj.approvalsLaterUpheldCount = message.approvalsLaterUpheldCount;
    }
    if (message.approvedMemoryHashes?.length) {
      obj.approvedMemoryHashes = message.approvedMemoryHashes.map((e) => base64FromBytes(e));
    }
    if (message.firstApprovalEpoch !== "0") {
      obj.firstApprovalEpoch = message.firstApprovalEpoch;
    }
    if (message.lastApprovalEpoch !== "0") {
      obj.lastApprovalEpoch = message.lastApprovalEpoch;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StoredModeratorProfile>, I>>(base?: I): StoredModeratorProfile {
    return StoredModeratorProfile.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StoredModeratorProfile>, I>>(object: I): StoredModeratorProfile {
    const message = createBaseStoredModeratorProfile();
    message.moderatorPubkey = object.moderatorPubkey ?? "";
    message.orgId = object.orgId ?? "";
    message.totalApprovals = object.totalApprovals ?? "0";
    message.approvalsLaterUpheldCount = object.approvalsLaterUpheldCount ?? "0";
    message.approvedMemoryHashes = object.approvedMemoryHashes?.map((e) => e) || [];
    message.firstApprovalEpoch = object.firstApprovalEpoch ?? "0";
    message.lastApprovalEpoch = object.lastApprovalEpoch ?? "0";
    return message;
  },
};

function createBaseEpochRotation(): EpochRotation {
  return { epoch: "0", reason: "", timestamp: "0" };
}

export const EpochRotation: MessageFns<EpochRotation> = {
  encode(message: EpochRotation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.epoch !== "0") {
      writer.uint32(8).uint64(message.epoch);
    }
    if (message.reason !== "") {
      writer.uint32(18).string(message.reason);
    }
    if (message.timestamp !== "0") {
      writer.uint32(24).int64(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EpochRotation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEpochRotation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.epoch = reader.uint64().toString();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.reason = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.timestamp = reader.int64().toString();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EpochRotation {
    return {
      epoch: isSet(object.epoch) ? globalThis.String(object.epoch) : "0",
      reason: isSet(object.reason) ? globalThis.String(object.reason) : "",
      timestamp: isSet(object.timestamp) ? globalThis.String(object.timestamp) : "0",
    };
  },

  toJSON(message: EpochRotation): unknown {
    const obj: any = {};
    if (message.epoch !== "0") {
      obj.epoch = message.epoch;
    }
    if (message.reason !== "") {
      obj.reason = message.reason;
    }
    if (message.timestamp !== "0") {
      obj.timestamp = message.timestamp;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EpochRotation>, I>>(base?: I): EpochRotation {
    return EpochRotation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EpochRotation>, I>>(object: I): EpochRotation {
    const message = createBaseEpochRotation();
    message.epoch = object.epoch ?? "0";
    message.reason = object.reason ?? "";
    message.timestamp = object.timestamp ?? "0";
    return message;
  },
};

function createBaseStoredLeaderProfile(): StoredLeaderProfile {
  return {
    leaderPubkey: "",
    orgId: "",
    totalChainCommitsSigned: "0",
    totalUpheldReportsCommitted: "0",
    epochRotations: [],
    firstLeadershipEpoch: "0",
    currentLeader: false,
  };
}

export const StoredLeaderProfile: MessageFns<StoredLeaderProfile> = {
  encode(message: StoredLeaderProfile, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.leaderPubkey !== "") {
      writer.uint32(10).string(message.leaderPubkey);
    }
    if (message.orgId !== "") {
      writer.uint32(18).string(message.orgId);
    }
    if (message.totalChainCommitsSigned !== "0") {
      writer.uint32(24).uint64(message.totalChainCommitsSigned);
    }
    if (message.totalUpheldReportsCommitted !== "0") {
      writer.uint32(32).uint64(message.totalUpheldReportsCommitted);
    }
    for (const v of message.epochRotations) {
      EpochRotation.encode(v!, writer.uint32(42).fork()).join();
    }
    if (message.firstLeadershipEpoch !== "0") {
      writer.uint32(48).uint64(message.firstLeadershipEpoch);
    }
    if (message.currentLeader !== false) {
      writer.uint32(56).bool(message.currentLeader);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StoredLeaderProfile {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoredLeaderProfile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.leaderPubkey = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.orgId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.totalChainCommitsSigned = reader.uint64().toString();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.totalUpheldReportsCommitted = reader.uint64().toString();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.epochRotations.push(EpochRotation.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.firstLeadershipEpoch = reader.uint64().toString();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.currentLeader = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoredLeaderProfile {
    return {
      leaderPubkey: isSet(object.leaderPubkey)
        ? globalThis.String(object.leaderPubkey)
        : isSet(object.leader_pubkey)
        ? globalThis.String(object.leader_pubkey)
        : "",
      orgId: isSet(object.orgId)
        ? globalThis.String(object.orgId)
        : isSet(object.org_id)
        ? globalThis.String(object.org_id)
        : "",
      totalChainCommitsSigned: isSet(object.totalChainCommitsSigned)
        ? globalThis.String(object.totalChainCommitsSigned)
        : isSet(object.total_chain_commits_signed)
        ? globalThis.String(object.total_chain_commits_signed)
        : "0",
      totalUpheldReportsCommitted: isSet(object.totalUpheldReportsCommitted)
        ? globalThis.String(object.totalUpheldReportsCommitted)
        : isSet(object.total_upheld_reports_committed)
        ? globalThis.String(object.total_upheld_reports_committed)
        : "0",
      epochRotations: globalThis.Array.isArray(object?.epochRotations)
        ? object.epochRotations.map((e: any) => EpochRotation.fromJSON(e))
        : globalThis.Array.isArray(object?.epoch_rotations)
        ? object.epoch_rotations.map((e: any) => EpochRotation.fromJSON(e))
        : [],
      firstLeadershipEpoch: isSet(object.firstLeadershipEpoch)
        ? globalThis.String(object.firstLeadershipEpoch)
        : isSet(object.first_leadership_epoch)
        ? globalThis.String(object.first_leadership_epoch)
        : "0",
      currentLeader: isSet(object.currentLeader)
        ? globalThis.Boolean(object.currentLeader)
        : isSet(object.current_leader)
        ? globalThis.Boolean(object.current_leader)
        : false,
    };
  },

  toJSON(message: StoredLeaderProfile): unknown {
    const obj: any = {};
    if (message.leaderPubkey !== "") {
      obj.leaderPubkey = message.leaderPubkey;
    }
    if (message.orgId !== "") {
      obj.orgId = message.orgId;
    }
    if (message.totalChainCommitsSigned !== "0") {
      obj.totalChainCommitsSigned = message.totalChainCommitsSigned;
    }
    if (message.totalUpheldReportsCommitted !== "0") {
      obj.totalUpheldReportsCommitted = message.totalUpheldReportsCommitted;
    }
    if (message.epochRotations?.length) {
      obj.epochRotations = message.epochRotations.map((e) => EpochRotation.toJSON(e));
    }
    if (message.firstLeadershipEpoch !== "0") {
      obj.firstLeadershipEpoch = message.firstLeadershipEpoch;
    }
    if (message.currentLeader !== false) {
      obj.currentLeader = message.currentLeader;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StoredLeaderProfile>, I>>(base?: I): StoredLeaderProfile {
    return StoredLeaderProfile.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StoredLeaderProfile>, I>>(object: I): StoredLeaderProfile {
    const message = createBaseStoredLeaderProfile();
    message.leaderPubkey = object.leaderPubkey ?? "";
    message.orgId = object.orgId ?? "";
    message.totalChainCommitsSigned = object.totalChainCommitsSigned ?? "0";
    message.totalUpheldReportsCommitted = object.totalUpheldReportsCommitted ?? "0";
    message.epochRotations = object.epochRotations?.map((e) => EpochRotation.fromPartial(e)) || [];
    message.firstLeadershipEpoch = object.firstLeadershipEpoch ?? "0";
    message.currentLeader = object.currentLeader ?? false;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
